// kanji/grade5.js - 5年生の漢字データ（185字）
// 各漢字: kanji, readings(読み方), meaning(意味), strokes(画数), example(例文), hint(覚え方ヒント), example_reading(例文での読み方)

const GRADE5_KANJI = [
    // --- あ行 ---
    { kanji: "移", readings: ["うつ(る)", "イ"], meaning: "うつる", strokes: 11, example: "移動 する", hint: "のぎへん に 多", example_reading: ["い"] },
    { kanji: "圧", readings: ["アツ"], meaning: "おしつける", strokes: 5, example: "血圧 をはかる", hint: "がんだれ に 土", example_reading: ["あつ"] },
    { kanji: "因", readings: ["イン"], meaning: "もとになること", strokes: 6, example: "原因 をさぐる", hint: "くにがまえ に 大", example_reading: ["いん"] },
    { kanji: "永", readings: ["なが(い)", "エイ"], meaning: "じかんがながい", strokes: 5, example: "永遠に続く", hint: "水 にてん がつく", example_reading: ["えい"] },
    { kanji: "営", readings: ["いとな(む)", "エイ"], meaning: "しごとをする", strokes: 12, example: "営業 時間", hint: "ツ と ワ と 呂", example_reading: ["えい"] },
    { kanji: "液", readings: ["エキ"], meaning: "しる", strokes: 11, example: "液体と固体", hint: "さんずい に 夜", example_reading: ["えき"] },
    { kanji: "演", readings: ["エン"], meaning: "やってみせる", strokes: 14, example: "演技 をする", hint: "さんずい に 寅", example_reading: ["えん"] },
    { kanji: "衛", readings: ["エイ"], meaning: "まもる", strokes: 16, example: "人工 衛星", hint: "行 のなかに 韋", example_reading: ["えい"] },
    { kanji: "易", readings: ["やさ(しい)", "エキ"], meaning: "かんたん", strokes: 8, example: "容易 なもんだい", hint: "日 と 勿", example_reading: ["い"] },
    { kanji: "益", readings: ["エキ"], meaning: "ためになること", strokes: 10, example: "利益", hint: "八 と 王 と 皿", example_reading: ["えき"] },
    { kanji: "応", readings: ["こた(える)", "オウ"], meaning: "こたえる", strokes: 7, example: "応援 する", hint: "まだれ と 心", example_reading: ["おう"] },
    { kanji: "往", readings: ["オウ"], meaning: "いく", strokes: 8, example: "往復", hint: "ぎょうにんべん に 主", example_reading: ["おう"] },
    { kanji: "桜", readings: ["さくら", "オウ"], meaning: "さくらのき", strokes: 10, example: "桜 の花", hint: "木へん に ツ と 女", example_reading: ["さくら"] },
    { kanji: "恩", readings: ["オン"], meaning: "ありがたいこと", strokes: 10, example: "恩返し", hint: "因 と 心", example_reading: ["おん"] },

    // --- か行 ---
    { kanji: "可", readings: ["カ"], meaning: "よい", strokes: 5, example: "可能性がある", hint: "丁 と 口", example_reading: ["か"] },
    { kanji: "仮", readings: ["かり", "カ"], meaning: "かり", strokes: 6, example: "仮 のすがた", hint: "にんべん に 反", example_reading: ["かり"] },
    { kanji: "価", readings: ["あたい", "カ"], meaning: "ねだん", strokes: 8, example: "価値 がある", hint: "にんべん に 西", example_reading: ["か"] },
    { kanji: "河", readings: ["かわ", "カ"], meaning: "おおきなかわ", strokes: 8, example: "一級河川", hint: "さんずい に 可", example_reading: ["か"] },
    { kanji: "過", readings: ["す(ぎる)", "カ"], meaning: "すぎる", strokes: 12, example: "過去 のこと", hint: "しんにょう に 咼", example_reading: ["か"] },
    { kanji: "賀", readings: ["ガ"], meaning: "いわう", strokes: 12, example: "年賀状をだす", hint: "加 と 貝", example_reading: ["が"] },
    { kanji: "快", readings: ["こころよ(い)", "カイ"], meaning: "きもちいい", strokes: 7, example: "快適", hint: "りっしんべん に 夬", example_reading: ["かい"] },
    { kanji: "解", readings: ["と(く)", "カイ"], meaning: "わかる、ほどく", strokes: 13, example: "解決 する", hint: "角 と 刀 と 牛", example_reading: ["かい"] },
    { kanji: "格", readings: ["カク"], meaning: "きまり", strokes: 10, example: "合格をいのる", hint: "木へん に 各", example_reading: ["かく"] },
    { kanji: "確", readings: ["たし(か)", "カク"], meaning: "たしか", strokes: 15, example: "確認 する", hint: "石へん に 隺", example_reading: ["かく"] },
    { kanji: "額", readings: ["ひたい", "ガク"], meaning: "ひたい、おかね", strokes: 18, example: "金額", hint: "客 と 頁", example_reading: ["がく"] },
    { kanji: "刊", readings: ["カン"], meaning: "ほんをだす", strokes: 5, example: "朝刊 をよむ", hint: "干 と 刂", example_reading: ["かん"] },
    { kanji: "眼", readings: ["め", "ガン"], meaning: "め", strokes: 11, example: "眼科にいく", hint: "目へん に 艮", example_reading: ["がん"] },
    { kanji: "基", readings: ["もと", "キ"], meaning: "もと", strokes: 11, example: "基本が大切", hint: "其 と 土", example_reading: ["き"] },
    { kanji: "寄", readings: ["よ(る)", "キ"], meaning: "よる", strokes: 11, example: "立ち 寄る", hint: "うかんむり に 奇", example_reading: ["よ"] },
    { kanji: "慣", readings: ["な(れる)", "カン"], meaning: "なれる", strokes: 14, example: "生活習慣", hint: "りっしんべん に 貫", example_reading: ["かん"] },
    { kanji: "幹", readings: ["みき", "カン"], meaning: "みき", strokes: 13, example: "新幹線に乗る", hint: "幸 のなかに 木", example_reading: ["かん"] },
    { kanji: "逆", readings: ["さか(らう)", "ギャク"], meaning: "はんたい", strokes: 9, example: "逆立ち", hint: "しんにょう に 屰", example_reading: ["さか"] },
    { kanji: "規", readings: ["キ"], meaning: "きまり", strokes: 11, example: "規則 をまもる", hint: "夫 と 見", example_reading: ["き"] },
    { kanji: "技", readings: ["わざ", "ギ"], meaning: "わざ", strokes: 7, example: "技術", hint: "てへん に 支", example_reading: ["ぎ"] },
    { kanji: "義", readings: ["ギ"], meaning: "ただしい", strokes: 13, example: "正義をつらぬく", hint: "羊 と 我", example_reading: ["ぎ"] },
    { kanji: "境", readings: ["さかい", "キョウ"], meaning: "さかいめ", strokes: 14, example: "国境をこえる", hint: "土へん に 竟", example_reading: ["きょう"] },
    { kanji: "旧", readings: ["キュウ"], meaning: "ふるい", strokes: 5, example: "旧正月", hint: "1 と 日", example_reading: ["きゅう"] },
    { kanji: "居", readings: ["い(る)", "キョ"], meaning: "いる", strokes: 8, example: "居間でねる", hint: "しかばね に 古", example_reading: ["い"] },
    { kanji: "久", readings: ["ひさ(しい)", "キュウ"], meaning: "ながいじかん", strokes: 3, example: "久しぶり", hint: "ク と ノ", example_reading: ["ひさ"] },
    { kanji: "許", readings: ["ゆる(す)", "キョ"], meaning: "ゆるす", strokes: 11, example: "許可 をとる", hint: "ごんべん に 午", example_reading: ["きょ"] },
    { kanji: "均", readings: ["キン"], meaning: "おなじ", strokes: 7, example: "平均をこえる", hint: "土へん に 匀", example_reading: ["きん"] },
    { kanji: "禁", readings: ["キン"], meaning: "してはいけない", strokes: 13, example: "それは禁止だ", hint: "林 と 示", example_reading: ["きん"] },
    { kanji: "句", readings: ["ク"], meaning: "ことば", strokes: 5, example: "俳句 をよむ", hint: "勹 に 口", example_reading: ["く"] },
    { kanji: "群", readings: ["むれ", "グン"], meaning: "むれ", strokes: 13, example: "群れ をなす", hint: "君 と 羊", example_reading: ["む"] },
    { kanji: "経", readings: ["へ(る)", "ケイ"], meaning: "とおる", strokes: 11, example: "経験をつむ", hint: "いとへん に 巠", example_reading: ["けい"] },
    { kanji: "潔", readings: ["ケツ"], meaning: "きれい", strokes: 15, example: "清潔をたもつ", hint: "さんずい に 絜", example_reading: ["けつ"] },
    { kanji: "件", readings: ["ケン"], meaning: "ことがら", strokes: 6, example: "事件を解決する", hint: "にんべん に 牛", example_reading: ["けん"] },
    { kanji: "券", readings: ["ケン"], meaning: "チケット", strokes: 8, example: "乗車券を買う", hint: "龹 と 刀", example_reading: ["けん"] },
    { kanji: "険", readings: ["けわ(しい)", "ケン"], meaning: "けわしい", strokes: 11, example: "危険な場所", hint: "こざとへん に 僉", example_reading: ["けん"] },
    { kanji: "検", readings: ["ケン"], meaning: "しらべる", strokes: 12, example: "検査 する", hint: "木へん に 僉", example_reading: ["けん"] },
    { kanji: "限", readings: ["かぎ(る)", "ゲン"], meaning: "かぎり", strokes: 9, example: "限界を突破する", hint: "こざとへん に 艮", example_reading: ["げん"] },
    { kanji: "現", readings: ["あらわ(れる)", "ゲン"], meaning: "あらわれる", strokes: 11, example: "現在の時刻", hint: "王へん に 見", example_reading: ["げん"] },
    { kanji: "減", readings: ["へ(る)", "ゲン"], meaning: "へる", strokes: 12, example: "減少 する", hint: "さんずい に 咸", example_reading: ["げん"] },
    { kanji: "故", readings: ["ゆえ", "コ"], meaning: "むかし、わけ", strokes: 9, example: "事故を起こす", hint: "古 と 攵", example_reading: ["こ"] },
    { kanji: "個", readings: ["コ"], meaning: "ひとつ", strokes: 10, example: "個人情報を守る", hint: "にんべん に 固", example_reading: ["こ"] },
    { kanji: "効", readings: ["き(く)", "コウ"], meaning: "ききめ", strokes: 8, example: "効果はバツグンだ", hint: "交 と 力", example_reading: ["こう"] },
    { kanji: "護", readings: ["ゴ"], meaning: "まもる", strokes: 20, example: "保護 する", hint: "ごんべん と 蒦", example_reading: ["ご"] },
    { kanji: "鉱", readings: ["コウ"], meaning: "こうぶつ", strokes: 13, example: "鉱石を採くつする", hint: "かねへん に 広", example_reading: ["こう"] },
    { kanji: "耕", readings: ["たがや(す)", "コウ"], meaning: "たがやす", strokes: 10, example: "畑を耕す", hint: "耒 と 井", example_reading: ["たがや"] },
    { kanji: "厚", readings: ["あつ(い)", "コウ"], meaning: "ぶあつい", strokes: 9, example: "ぶ厚い 本", hint: "がんだれ に 日 と 子", example_reading: ["あつ"] },

    // --- さ行 ---
    { kanji: "興", readings: ["キョウ"], meaning: "おこす", strokes: 16, example: "興味 をもつ", hint: "同 のまわりに いろいろ", example_reading: ["きょう"] },
    { kanji: "構", readings: ["かま(える)", "コウ"], meaning: "かまえる、くみたてる", strokes: 14, example: "構造を見直す", hint: "木へん に 冓", example_reading: ["こう"] },
    { kanji: "講", readings: ["コウ"], meaning: "はなす", strokes: 17, example: "講演会をひらく", hint: "ごんべん に 冓", example_reading: ["こう"] },
    { kanji: "混", readings: ["ま(ざる)", "コン"], meaning: "まざる", strokes: 11, example: "混雑をさける", hint: "さんずい に 昆", example_reading: ["こん"] },
    { kanji: "査", readings: ["サ"], meaning: "しらべる", strokes: 9, example: "事件の調査をする", hint: "木 と 且", example_reading: ["さ"] },
    { kanji: "再", readings: ["ふたた(び)", "サイ"], meaning: "もういちど", strokes: 6, example: "再びたちあがる", hint: "一 と 冂 と 王", example_reading: ["ふたた"] },
    { kanji: "災", readings: ["わざわ(い)", "サイ"], meaning: "わざわい", strokes: 7, example: "災害にそなえる", hint: "く と く と く と 火", example_reading: ["さい"] },
    { kanji: "妻", readings: ["つま", "サイ"], meaning: "おくさん", strokes: 8, example: "妻を紹介します", hint: "十 と ヨ と 女", example_reading: ["つま"] },
    { kanji: "採", readings: ["と(る)", "サイ"], meaning: "とる", strokes: 11, example: "昆虫 採集", hint: "てへん に 采", example_reading: ["さい"] },
    { kanji: "際", readings: ["きわ", "サイ"], meaning: "きわ、〜のとき", strokes: 14, example: "国際電話", hint: "こざとへん に 祭", example_reading: ["さい"] },
    { kanji: "在", readings: ["あ(る)", "ザイ"], meaning: "ある", strokes: 6, example: "存在をかくす", hint: "ナ と ノ と 土", example_reading: ["ざい"] },
    { kanji: "罪", readings: ["つみ", "ザイ"], meaning: "つみ", strokes: 13, example: "犯罪をぼくめつする", hint: "四 みたい なのと 非", example_reading: ["ざい"] },
    { kanji: "雑", readings: ["ザツ"], meaning: "まざる", strokes: 14, example: "複雑な気持ち", hint: "九 と 木 と 隹", example_reading: ["ざつ"] },
    { kanji: "財", readings: ["ザイ"], meaning: "おかね", strokes: 10, example: "財布をおとす", hint: "貝へん に 才", example_reading: ["さい"] },
    { kanji: "酸", readings: ["サン"], meaning: "すっぱい", strokes: 14, example: "酸素カプセル", hint: "酉へん に 夋", example_reading: ["さん"] },
    { kanji: "賛", readings: ["サン"], meaning: "さんせいする", strokes: 15, example: "賛成と反対", hint: "夫 と 夫 と 貝", example_reading: ["さん"] },
    { kanji: "支", readings: ["ささ(える)", "シ"], meaning: "ささえる", strokes: 4, example: "支持率を気にする", hint: "十 と 又", example_reading: ["し"] },
    { kanji: "志", readings: ["こころざし", "シ"], meaning: "こころざし", strokes: 7, example: "意志をまげる", hint: "士 と 心", example_reading: ["し"] },
    { kanji: "枝", readings: ["えだ", "シ"], meaning: "えだ", strokes: 8, example: "木の 枝", hint: "木へん に 支", example_reading: ["えだ"] },
    { kanji: "師", readings: ["シ"], meaning: "先生", strokes: 10, example: "医師になる", hint: "𠂤 と 帀", example_reading: ["し"] },
    { kanji: "資", readings: ["シ"], meaning: "もとで", strokes: 13, example: "資金が底をつく", hint: "次 と 貝", example_reading: ["し"] },
    { kanji: "飼", readings: ["か(う)", "シ"], meaning: "えさをあげる", strokes: 13, example: "ペットを飼育する", hint: "食へん に 司", example_reading: ["し"] },
    { kanji: "示", readings: ["しめ(す)", "シ"], meaning: "しめす", strokes: 5, example: "指示を出す", hint: "二 と 小", example_reading: ["じ"] },
    { kanji: "似", readings: ["に(る)", "ジ"], meaning: "にている", strokes: 7, example: "似顔絵をかく", hint: "にんべん に 以", example_reading: ["に"] },
    { kanji: "識", readings: ["シキ"], meaning: "しる", strokes: 19, example: "知識を身につける", hint: "ごんべん に 音 と 戈", example_reading: ["しき"] },
    { kanji: "質", readings: ["シツ"], meaning: "なかみ", strokes: 15, example: "質問をまとめる", hint: "斤 と 斤 と 貝", example_reading: ["しつ"] },
    { kanji: "述", readings: ["の(べる)", "ジュツ"], meaning: "はなす", strokes: 8, example: "意見を述べる", hint: "しんにょう に 朮", example_reading: ["の"] },
    { kanji: "修", readings: ["おさ(める)", "シュウ"], meaning: "なおす", strokes: 10, example: "修理してもらう", hint: "イ と ｜ と 攵 と 彡", example_reading: ["しゅう"] },
    { kanji: "準", readings: ["ジュン"], meaning: "めやす", strokes: 13, example: "準備をおこたる", hint: "さんずい と 隹 と 十", example_reading: ["じゅん"] },
    { kanji: "舎", readings: ["シャ"], meaning: "いえ", strokes: 8, example: "思い出の校舎", hint: "人 と 舌", example_reading: ["しゃ"] },
    { kanji: "術", readings: ["ジュツ"], meaning: "わざ", strokes: 11, example: "手術のあと", hint: "行 のなかに 朮", example_reading: ["じゅつ"] },
    { kanji: "謝", readings: ["あやま(る)", "シャ"], meaning: "あやまる", strokes: 17, example: "感謝の気持ち", hint: "ごんべん に 射", example_reading: ["しゃ"] },
    { kanji: "授", readings: ["さず(ける)", "ジュ"], meaning: "あたえる", strokes: 11, example: "授業にでる", hint: "てへん に 受", example_reading: ["じゅ"] },
    { kanji: "招", readings: ["まね(く)", "ショウ"], meaning: "よぶ", strokes: 8, example: "パーティの招待状", hint: "てへん に 召", example_reading: ["しょう"] },
    { kanji: "序", readings: ["ジョ"], meaning: "じゅんばん", strokes: 7, example: "順序が逆です", hint: "まだれ に 予", example_reading: ["じょ"] },
    { kanji: "証", readings: ["ショウ"], meaning: "しょうめいする", strokes: 12, example: "無実を証明する", hint: "ごんべん に 正", example_reading: ["しょう"] },
    { kanji: "承", readings: ["うけたまわ(る)", "ショウ"], meaning: "うける", strokes: 8, example: "承知しました", hint: "乙 と 水 みたいなかたち", example_reading: ["しょう"] },
    { kanji: "常", readings: ["つね", "ジョウ"], meaning: "いつも", strokes: 11, example: "日常を大切にする", hint: "尚 と 巾", example_reading: ["じょう"] },
    { kanji: "条", readings: ["ジョウ"], meaning: "すじ", strokes: 7, example: "条件を考える", hint: "夂 と 木", example_reading: ["じょう"] },
    { kanji: "状", readings: ["ジョウ"], meaning: "ようす", strokes: 7, example: "状況を説明する", hint: "冫 と 犬", example_reading: ["じょう"] },
    { kanji: "情", readings: ["なさ(け)", "ジョウ"], meaning: "きもち", strokes: 11, example: "友情パワー", hint: "りっしんべん に 青", example_reading: ["じょう"] },
    { kanji: "職", readings: ["ショク"], meaning: "しごと", strokes: 18, example: "色々な職業を知る", hint: "耳 と 音 と 戈", example_reading: ["しょく"] },
    { kanji: "織", readings: ["お(る)", "シキ"], meaning: "ぬのを おる", strokes: 18, example: "組織のメンバー", hint: "いとへん に 音 と 戈", example_reading: ["しき"] },
    { kanji: "制", readings: ["セイ"], meaning: "きまり", strokes: 8, example: "制度づくり", hint: "牛 と 巾 と 刂", example_reading: ["せい"] },
    { kanji: "性", readings: ["セイ", "ショウ"], meaning: "うまれつきの せいしつ", strokes: 8, example: "性格が良い", hint: "りっしんべん に 生", example_reading: ["せい"] },
    { kanji: "政", readings: ["まつりごと", "セイ"], meaning: "くにを おさめる", strokes: 9, example: "政治に関心をもつ", hint: "正 と 攵", example_reading: ["せい"] },
    { kanji: "勢", readings: ["いきお(い)", "セイ"], meaning: "いきおい", strokes: 13, example: "勢い がある", hint: "執 のしたに 力", example_reading: ["いきお"] },
    { kanji: "精", readings: ["セイ", "ショウ"], meaning: "まじりけのない", strokes: 14, example: "妖精を探す物語", hint: "米へん に 青", example_reading: ["せい"] },
    { kanji: "製", readings: ["セイ"], meaning: "つくる", strokes: 14, example: "製品発表会", hint: "制 のしたに 衣", example_reading: ["せい"] },
    { kanji: "税", readings: ["ゼイ"], meaning: "くにに おさめるおかね", strokes: 12, example: "消費税", hint: "のぎへん に 兌", example_reading: ["ぜい"] },
    { kanji: "責", readings: ["せ(める)", "セキ"], meaning: "せめる、つとめ", strokes: 11, example: "責任 をもつ", hint: "主 と 貝", example_reading: ["せき"] },
    { kanji: "績", readings: ["セキ"], meaning: "つむぐ、てがら", strokes: 17, example: "成績を残す", hint: "いとへん に 責", example_reading: ["せき"] },
    { kanji: "接", readings: ["つ(ぐ)", "セツ"], meaning: "くっつく", strokes: 11, example: "直接 教える", hint: "てへん に 妾", example_reading: ["せつ"] },
    { kanji: "設", readings: ["もう(ける)", "セツ"], meaning: "つくる", strokes: 11, example: "設計 する", hint: "ごんべん に 殳", example_reading: ["せっ"] },
    { kanji: "舌", readings: ["した", "ゼツ"], meaning: "した", strokes: 6, example: "舌 をだす", hint: "千 と 口", example_reading: ["した"] },
    { kanji: "絶", readings: ["た(える)", "ゼツ"], meaning: "たえる", strokes: 12, example: "絶対に やめる", hint: "いとへん に 色", example_reading: ["ぜっ"] },
    { kanji: "総", readings: ["ソウ"], meaning: "すべて", strokes: 14, example: "総合的に考える", hint: "いとへん に 公 と 心", example_reading: ["そう"] },
    { kanji: "素", readings: ["ソ", "ス"], meaning: "もと", strokes: 10, example: "素直 なこころ", hint: "主 と 糸", example_reading: ["す"] },
    { kanji: "祖", readings: ["ソ"], meaning: "ごせんぞさま", strokes: 9, example: "祖父に会いに行く", hint: "しめすへん に 且", example_reading: ["そ"] },
    { kanji: "銭", readings: ["ぜに", "セン"], meaning: "おかね", strokes: 14, example: "サイフに小銭がたまる", hint: "かねへん に 戔", example_reading: ["ぜに"] },

    // --- た行 ---
    { kanji: "造", readings: ["つく(る)", "ゾウ"], meaning: "つくる", strokes: 10, example: "造形を学ぶ", hint: "しんにょう に 告", example_reading: ["ぞう"] },
    { kanji: "像", readings: ["ゾウ"], meaning: "かたち、すがた", strokes: 14, example: "想像 する", hint: "にんべん に 象", example_reading: ["ぞう"] },
    { kanji: "増", readings: ["ふ(える)", "ゾウ"], meaning: "ふえる", strokes: 14, example: "増加する", hint: "土へん に 曽", example_reading: ["ぞう"] },
    { kanji: "則", readings: ["ソク"], meaning: "きまり", strokes: 9, example: "規則を守る", hint: "貝 と 刂", example_reading: ["そく"] },
    { kanji: "測", readings: ["はか(る)", "ソク"], meaning: "はかる", strokes: 12, example: "身長を測定する", hint: "さんずい に 則", example_reading: ["そく"] },
    { kanji: "損", readings: ["そこ(なう)", "ソン"], meaning: "へる、わるくする", strokes: 13, example: "損害をこうむる", hint: "てへん に 員", example_reading: ["そん"] },
    { kanji: "退", readings: ["しりぞ(く)", "タイ"], meaning: "さがる", strokes: 9, example: "高校を退学した", hint: "しんにょう に 艮", example_reading: ["たい"] },
    { kanji: "属", readings: ["ゾク"], meaning: "なかまに はいる", strokes: 12, example: "クラブに所属する", hint: "尸 と 禹", example_reading: ["ぞく"] },
    { kanji: "率", readings: ["ひき(いる)", "ソツ", "リツ"], meaning: "ひきいる、わりあい", strokes: 11, example: "確率", hint: "玄 のまわりに 点々 と 十", example_reading: ["りつ"] },
    { kanji: "貸", readings: ["か(す)", "タイ"], meaning: "かす", strokes: 12, example: "本の貸し出し", hint: "代 と 貝", example_reading: ["か"] },
    { kanji: "態", readings: ["タイ"], meaning: "ようす", strokes: 14, example: "態度にあらわれる", hint: "能 と 心", example_reading: ["たい"] },
    { kanji: "築", readings: ["きず(く)", "チク"], meaning: "たてる", strokes: 16, example: "建築家をめざす", hint: "竹 と 筑 と 木", example_reading: ["ちく"] },
    { kanji: "断", readings: ["た(つ)", "ダン"], meaning: "きる、ことわる", strokes: 11, example: "横断 歩道", hint: "米 と L と 斤", example_reading: ["だん"] },
    { kanji: "団", readings: ["ダン"], meaning: "あつまり", strokes: 6, example: "団体に所属する", hint: "くにがまえ に 寸", example_reading: ["だん"] },
    { kanji: "張", readings: ["は(る)", "チョウ"], meaning: "はる", strokes: 11, example: "ぼくは頑張る", hint: "弓へん に 長", example_reading: ["ば"] },
    { kanji: "程", readings: ["ほど", "テイ"], meaning: "めやす、きまり", strokes: 12, example: "ある程度", hint: "のぎへん に 呈", example_reading: ["てい"] },
    { kanji: "提", readings: ["さ(げる)", "テイ"], meaning: "だす", strokes: 12, example: "提出 する", hint: "てへん に 是", example_reading: ["てい"] },
    { kanji: "適", readings: ["テキ"], meaning: "あてはまる", strokes: 14, example: "適当に答える", hint: "しんにょう に 啇", example_reading: ["てき"] },
    { kanji: "敵", readings: ["てき", "テキ"], meaning: "あいて", strokes: 15, example: "ライバルは 敵", hint: "啇 と 攵", example_reading: ["てき"] },
    { kanji: "統", readings: ["す(べる)", "トウ"], meaning: "まとめる", strokes: 12, example: "統一", hint: "いとへん に 充", example_reading: ["とう"] },
    { kanji: "銅", readings: ["ドウ"], meaning: "あかがね", strokes: 14, example: "銅メダル", hint: "かねへん に 同", example_reading: ["どう"] },
    { kanji: "導", readings: ["みちび(く)", "ドウ"], meaning: "みちびく", strokes: 15, example: "案内して 導く", hint: "道 のしたに 寸", example_reading: ["みちび"] },
    { kanji: "徳", readings: ["トク"], meaning: "りっぱなおこない", strokes: 14, example: "道徳を考える", hint: "ぎょうにんべん に 悳", example_reading: ["とく"] },
    { kanji: "独", readings: ["ひと(り)", "ドク"], meaning: "ひとり", strokes: 9, example: "独立する", hint: "けものへん に 虫", example_reading: ["どく"] },

    // --- な行 ---
    { kanji: "任", readings: ["まか(せる)", "ニン"], meaning: "まかせる", strokes: 6, example: "担任 の先生", hint: "にんべん に 壬", example_reading: ["にん"] },
    { kanji: "燃", readings: ["も(える)", "ネン"], meaning: "もえる", strokes: 16, example: "燃える ゴミ", hint: "火へん に 然", example_reading: ["も"] },
    { kanji: "能", readings: ["ノウ"], meaning: "できる、はたらき", strokes: 10, example: "可能 性", hint: "ム と 月 と ヒ ２つ", example_reading: ["のう"] },

    // --- は行 ---
    { kanji: "破", readings: ["やぶ(る)", "ハ"], meaning: "やぶる", strokes: 10, example: "紙を 破る", hint: "石へん に 皮", example_reading: ["やぶ"] },
    { kanji: "犯", readings: ["おか(す)", "ハン"], meaning: "きまりを やぶる", strokes: 5, example: "犯人をみた", hint: "けものへん に 卩", example_reading: ["はん"] },
    { kanji: "判", readings: ["ハン"], meaning: "みわける", strokes: 7, example: "判断 する", hint: "半 と 刂", example_reading: ["はん"] },
    { kanji: "版", readings: ["ハン"], meaning: "いた、いんさつ", strokes: 8, example: "本を出版する", hint: "片 と 反", example_reading: ["ぱん"] },
    { kanji: "比", readings: ["くら(べる)", "ヒ"], meaning: "くらべる", strokes: 4, example: "比較 する", hint: "ヒ が ２つ", example_reading: ["ひ"] },
    { kanji: "備", readings: ["そな(える)", "ビ"], meaning: "よういする", strokes: 12, example: "準備をおこたるな", hint: "にんべん に 𤰔", example_reading: ["び"] },
    { kanji: "非", readings: ["ヒ"], meaning: "あらず", strokes: 8, example: "非常口を確認する", hint: "はね みたい なかたち", example_reading: ["ひ"] },
    { kanji: "肥", readings: ["こ(える)", "ヒ"], meaning: "ふとる、こえる", strokes: 8, example: "畑に肥料をまく", hint: "月へん に 巴", example_reading: ["ひ"] },
    { kanji: "評", readings: ["ヒョウ"], meaning: "ねうちをきめる", strokes: 12, example: "評判が良い", hint: "ごんべん に 平", example_reading: ["ひょう"] },
    { kanji: "俵", readings: ["たわら", "ヒョウ"], meaning: "たわら", strokes: 10, example: "米俵をかつぐ", hint: "にんべん に 表", example_reading: ["だわら"] },
    { kanji: "婦", readings: ["フ"], meaning: "おんなのひと", strokes: 11, example: "仲良し夫婦", hint: "女へん に 帚", example_reading: ["ふ"] },
    { kanji: "布", readings: ["ぬの", "フ"], meaning: "ぬの", strokes: 5, example: "毛布にくるまる", hint: "ナ と 巾", example_reading: ["ふ"] },
    { kanji: "貧", readings: ["まず(しい)", "ヒン"], meaning: "まずしい", strokes: 11, example: "金持ちと貧乏", hint: "分 と 貝", example_reading: ["びん"] },
    { kanji: "武", readings: ["ブ", "ム"], meaning: "たたかい", strokes: 8, example: "武士にあこがれる", hint: "一 と 止 と 戈", example_reading: ["ぶ"] },
    { kanji: "復", readings: ["フク"], meaning: "もとに もどる", strokes: 12, example: "復習 する", hint: "ぎょうにんべん に 複 の右側", example_reading: ["ふく"] },
    { kanji: "富", readings: ["とみ", "フ"], meaning: "ゆたかになる", strokes: 12, example: "富士 山にのぼる", hint: "うかんむり に 畐", example_reading: ["ふ"] },
    { kanji: "複", readings: ["フク"], meaning: "かさなる", strokes: 14, example: "複雑なきもち", hint: "ころもへん に 復 の右側", example_reading: ["ふく"] },
    { kanji: "仏", readings: ["ほとけ", "ブツ"], meaning: "ほとけさま", strokes: 4, example: "大仏をみにいく", hint: "にんべん に ム", example_reading: ["ぶつ"] },
    { kanji: "編", readings: ["あ(む)", "ヘン"], meaning: "あむ、まとめる", strokes: 15, example: "毛糸を 編む", hint: "いとへん に 扁", example_reading: ["あ"] },
    { kanji: "弁", readings: ["ベン"], meaning: "はなす、わける", strokes: 5, example: "お弁当をたべる", hint: "ム と 廾", example_reading: ["べん"] },
    { kanji: "貿", readings: ["ボウ"], meaning: "やりとりする", strokes: 12, example: "貿易をはじめる", hint: "卯 と 貝", example_reading: ["ぼう"] },
    { kanji: "防", readings: ["ふせ(ぐ)", "ボウ"], meaning: "ふせぐ", strokes: 7, example: "かぜを予防する", hint: "こざとへん に 方", example_reading: ["ぼう"] },
    { kanji: "保", readings: ["たも(つ)", "ホ"], meaning: "まもる、たもつ", strokes: 9, example: "保健 室", hint: "にんべん に 呆", example_reading: ["ほ"] },
    { kanji: "墓", readings: ["はか", "ボ"], meaning: "おはか", strokes: 13, example: "お墓 まいり", hint: "莫 のしたに 土", example_reading: ["はか"] },
    { kanji: "報", readings: ["むく(いる)", "ホウ"], meaning: "しらせる", strokes: 12, example: "報告 する", hint: "幸 と 丸 みたい なの と 又", example_reading: ["ほう"] },
    { kanji: "豊", readings: ["ゆた(か)", "ホウ"], meaning: "ゆたか", strokes: 13, example: "豊か なしぜん", hint: "曲 と 豆", example_reading: ["ゆた"] },

    // --- ま行 ---
    { kanji: "務", readings: ["つと(める)", "ム"], meaning: "つとめ", strokes: 11, example: "事務所に入る", hint: "矛 と 攵 と 力", example_reading: ["む"] },
    { kanji: "暴", readings: ["あば(れる)", "ボウ"], meaning: "あばれる", strokes: 15, example: "乱暴な言い方", hint: "日 と 共 と 水 みたい", example_reading: ["ぼう"] },
    { kanji: "夢", readings: ["ゆめ", "ム"], meaning: "ゆめ", strokes: 13, example: "夢 をみる", hint: "くさかんむり と 罒 と ワ と 夕", example_reading: ["ゆめ"] },
    { kanji: "迷", readings: ["まよ(う)", "メイ"], meaning: "まよう", strokes: 9, example: "迷子のこども", hint: "しんにょう に 米", example_reading: ["まい"] },
    { kanji: "綿", readings: ["わた", "メン"], meaning: "わた", strokes: 14, example: "綿 あめを食べる", hint: "いとへん に 白 と 巾", example_reading: ["わた"] },

    // --- や行 ---
    { kanji: "輸", readings: ["ユ"], meaning: "はこぶ", strokes: 16, example: "輸入ものの車", hint: "車へん に 兪", example_reading: ["ゆ"] },
    { kanji: "余", readings: ["あま(る)", "ヨ"], meaning: "あまる", strokes: 7, example: "余裕をみせる", hint: "人 と 一 と ホ", example_reading: ["よ"] },
    { kanji: "預", readings: ["あず(ける)", "ヨ"], meaning: "あずける", strokes: 13, example: "銀行預金", hint: "予 と 頁", example_reading: ["よ"] },
    { kanji: "容", readings: ["ヨウ"], meaning: "かたち、いれる", strokes: 10, example: "内容を確認する", hint: "うかんむり に 谷", example_reading: ["よう"] },

    // --- ら行 ---
    { kanji: "略", readings: ["リャク"], meaning: "はぶく", strokes: 11, example: "省略 する", hint: "田 と 各", example_reading: ["りゃく"] },
    { kanji: "留", readings: ["と(める)", "リュウ"], meaning: "とどめる", strokes: 10, example: "留守 番", hint: "卯 と 田", example_reading: ["る"] },
    { kanji: "領", readings: ["リョウ"], meaning: "おさめる", strokes: 14, example: "領収 書をもらう", hint: "令 と 頁", example_reading: ["りょう"] }
];