// kanji/grade3.js - 3年生の漢字データ（完全版：200字）
// 各漢字: kanji, readings(読み方), meaning(意味), strokes(画数), example(例文), hint(覚え方ヒント), example_reading(例文での読み方)

const GRADE3_KANJI = [
    // --- 自然・天候・植物 ---
    { kanji: "氷", readings: ["こおり", "ヒョウ"], meaning: "みずがこおったもの", strokes: 5, example: "氷 をいれる", hint: "水 にてん", example_reading: ["こおり"] },
    { kanji: "波", readings: ["なみ", "ハ"], meaning: "うみのなみ", strokes: 8, example: "波 がたかい", hint: "さんずい に 皮", example_reading: ["なみ"] },
    { kanji: "島", readings: ["しま", "トウ"], meaning: "うみにうかぶ りくち", strokes: 10, example: "南の 島", hint: "鳥 のしたに 山", example_reading: ["しま"] },
    { kanji: "岸", readings: ["きし", "ガン"], meaning: "うみやかわの ふち", strokes: 8, example: "川の 岸 をあるく", hint: "山 と 厂 と 干", example_reading: ["きし"] },
    { kanji: "湖", readings: ["みずうみ", "コ"], meaning: "おおきな みずうみ", strokes: 12, example: "湖 でボートにのる", hint: "さんずい と 古 と 月", example_reading: ["みずうみ"] },
    { kanji: "港", readings: ["みなと", "コウ"], meaning: "ふねがとまる ところ", strokes: 12, example: "港 にふねがつく", hint: "さんずい と 巷", example_reading: ["みなと"] },
    { kanji: "陽", readings: ["ヨウ"], meaning: "おひさま、ひかり", strokes: 12, example: "太陽 がまぶしい", hint: "こざとへん に 昜", example_reading: ["よう"] },
    { kanji: "緑", readings: ["みどり", "リョク"], meaning: "みどりいろ", strokes: 14, example: "緑 のはっぱ", hint: "いとへん に 彔", example_reading: ["みどり"] },
    { kanji: "葉", readings: ["は", "ヨウ"], meaning: "はっぱ", strokes: 12, example: "木の 葉", hint: "くさかんむり と 世 と 木", example_reading: ["は"] },
    { kanji: "根", readings: ["ね", "コン"], meaning: "きのねっこ", strokes: 10, example: "木の 根 がはる", hint: "木へん に 艮", example_reading: ["ね"] },
    { kanji: "畑", readings: ["はたけ", "はた"], meaning: "やさいをそだてる ところ", strokes: 9, example: "畑 でやさいをつくる", hint: "火 と 田", example_reading: ["はたけ"] },
    { kanji: "農", readings: ["ノウ"], meaning: "はたけしごと", strokes: 13, example: "農家 のひと", hint: "曲 と 辰", example_reading: ["のう"] },

    // --- 場所・建物・町 ---
    { kanji: "橋", readings: ["はし", "キョウ"], meaning: "かわをわたる はし", strokes: 16, example: "橋 をわたる", hint: "木へん に 喬", example_reading: ["はし"] },
    { kanji: "坂", readings: ["さか", "ハン"], meaning: "ななめのみち", strokes: 7, example: "坂 をのぼる", hint: "土へん に 反", example_reading: ["さか"] },
    { kanji: "路", readings: ["じ", "ロ"], meaning: "みち", strokes: 13, example: "道路 をはしる", hint: "足へん に 各", example_reading: ["ろ"] },
    { kanji: "駅", readings: ["エキ"], meaning: "でんしゃがとまるところ", strokes: 14, example: "駅 でまちあわせ", hint: "馬へん に 尺", example_reading: ["えき"] },
    { kanji: "庭", readings: ["にわ", "テイ"], meaning: "おうちのにわ", strokes: 10, example: "庭 であそぶ", hint: "まだれ に 廷", example_reading: ["にわ"] },
    { kanji: "館", readings: ["やかた", "カン"], meaning: "おおきなたてもの", strokes: 16, example: "図書館 にいく", hint: "食へん に 官", example_reading: ["かん"] },
    { kanji: "宮", readings: ["みや", "キュウ"], meaning: "かみさまや おうさまのいえ", strokes: 10, example: "お宮まいり", hint: "うかんむり に 呂", example_reading: ["みや"] },
    { kanji: "屋", readings: ["や", "オク"], meaning: "おみせ、いえ", strokes: 9, example: "本屋 にいく", hint: "や", example_reading: ["や"] },
    { kanji: "局", readings: ["キョク"], meaning: "やくしょ、きまったところ", strokes: 7, example: "郵便局 にいく", hint: "しかばね に 句", example_reading: ["きょく"] },
    { kanji: "庫", readings: ["コ"], meaning: "ものをしまう ところ", strokes: 10, example: "金庫 をあける", hint: "まだれ に 車", example_reading: ["こ"] },
    { kanji: "階", readings: ["カイ"], meaning: "たてもののだん", strokes: 12, example: "二階 にあがる", hint: "こざとへん に 皆", example_reading: ["かい"] },
    { kanji: "都", readings: ["みやこ", "ト"], meaning: "おおきなまち", strokes: 11, example: "東京都", hint: "者 と こざとへん", example_reading: ["と"] },
    { kanji: "県", readings: ["ケン"], meaning: "くにをわけるなまえ", strokes: 9, example: "青森県", hint: "目 と L と 小", example_reading: ["けん"] },
    { kanji: "区", readings: ["ク"], meaning: "まちをわけるなまえ", strokes: 4, example: "区役所", hint: "匚 に メ", example_reading: ["く"] },
    { kanji: "州", readings: ["シュウ"], meaning: "くにをわける おおきなばしょ", strokes: 6, example: "本州", hint: "川 のなかに てん３つ", example_reading: ["しゅう"] },
    { kanji: "界", readings: ["カイ"], meaning: "せかい、さかいめ", strokes: 9, example: "世界 はひろい", hint: "田 と 介", example_reading: ["かい"] },
    { kanji: "所", readings: ["ところ", "ショ"], meaning: "ばしょ", strokes: 8, example: "近所の 場所", hint: "戸 と 斤", example_reading: ["しょ"] },

    // --- 人・体・家族 ---
    { kanji: "君", readings: ["きみ", "クン"], meaning: "きみ、おとこのこ", strokes: 7, example: "君 がすき", hint: "尹 と 口", example_reading: ["きみ"] },
    { kanji: "者", readings: ["もの", "シャ"], meaning: "ひと", strokes: 8, example: "医者 にみてもらう", hint: "老 のしたに 日", example_reading: ["しゃ"] },
    { kanji: "主", readings: ["ぬし", "シュ"], meaning: "あるじ、メイン", strokes: 5, example: "主人", hint: "王 にてん", example_reading: ["しゅ"] },
    { kanji: "族", readings: ["ゾク"], meaning: "おなじ なかま", strokes: 11, example: "家族 ででかける", hint: "方 と 矢 と ひとやね", example_reading: ["ぞく"] },
    { kanji: "童", readings: ["わらべ", "ドウ"], meaning: "こども", strokes: 12, example: "児童館 にいく", hint: "立 と 里", example_reading: ["どう"] },
    { kanji: "客", readings: ["キャク"], meaning: "おきゃくさん", strokes: 9, example: "お客 さんがくる", hint: "うかんむり に 各", example_reading: ["きゃく"] },
    { kanji: "員", readings: ["イン"], meaning: "はたらくひと", strokes: 10, example: "全員 あつまる", hint: "口 と 貝", example_reading: ["いん"] },
    { kanji: "医", readings: ["イ"], meaning: "おいしゃさん", strokes: 7, example: "歯医者 にいく", hint: "匚 に 矢", example_reading: ["い"] },
    { kanji: "命", readings: ["いのち", "メイ"], meaning: "いのち", strokes: 8, example: "命 をたいせつに", hint: "人 と 一 と 口 と 卩", example_reading: ["いのち"] },
    { kanji: "血", readings: ["ち", "ケツ"], meaning: "ち", strokes: 6, example: "血 がでる", hint: "ノ と 皿", example_reading: ["ち"] },
    { kanji: "指", readings: ["ゆび", "シ"], meaning: "ゆび、さす", strokes: 9, example: "指 をさす", hint: "てへん に 旨", example_reading: ["ゆび"] },
    { kanji: "歯", readings: ["は", "シ"], meaning: "は", strokes: 12, example: "歯 をみがく", hint: "止 のしたに 米 みたいないっぱい", example_reading: ["は"] },
    { kanji: "鼻", readings: ["はな", "ビ"], meaning: "はな", strokes: 14, example: "鼻 がたかい", hint: "自 と 田 と 廾", example_reading: ["はな"] },
    { kanji: "身", readings: ["み", "シン"], meaning: "からだ、じぶん", strokes: 7, example: "身長 をはかる", hint: "からだのかたち", example_reading: ["しん"] },
    { kanji: "息", readings: ["いき", "ソク"], meaning: "いき", strokes: 10, example: "息 をする", hint: "自 と 心", example_reading: ["いき"] },
    { kanji: "死", readings: ["し(ぬ)", "シ"], meaning: "しぬ、いのちがおわる", strokes: 6, example: "必死 にがんばる", hint: "一 と 夕 と ヒ", example_reading: ["し"] },

    // --- 心・状態・様子 ---
    { kanji: "悲", readings: ["かな(しい)", "ヒ"], meaning: "かなしい", strokes: 12, example: "悲しい きもち", hint: "非 と 心", example_reading: ["かな"] },
    { kanji: "苦", readings: ["くる(しい)", "ク"], meaning: "くるしい、にがい", strokes: 8, example: "苦い くすり", hint: "くさかんむり に 古", example_reading: ["にが"] },
    { kanji: "幸", readings: ["しあわ(せ)", "コウ"], meaning: "しあわせ", strokes: 8, example: "幸せ なかぞく", hint: "土 と ￥ みたい", example_reading: ["しあわ"] },
    { kanji: "神", readings: ["かみ", "シン"], meaning: "かみさま", strokes: 9, example: "神様 にいのる", hint: "しめすへん に 申", example_reading: ["かみ"] },
    { kanji: "安", readings: ["やす(い)", "アン"], meaning: "やすい、あんしん", strokes: 6, example: "安全 なみち", hint: "うかんむり に 女", example_reading: ["あん"] },
    { kanji: "暗", readings: ["くら(い)", "アン"], meaning: "くらい", strokes: 13, example: "暗い へや", hint: "日 と 音", example_reading: ["くら"] },
    { kanji: "寒", readings: ["さむ(い)", "カン"], meaning: "さむい", strokes: 12, example: "寒い ふゆ", hint: "うかんむり と 井 と 灬", example_reading: ["さむ"] },
    { kanji: "温", readings: ["あたた(かい)", "オン"], meaning: "あたたかい", strokes: 12, example: "温かい おちゃ", hint: "さんずい と 日 と 皿", example_reading: ["あたた"] },
    { kanji: "暑", readings: ["あつ(い)", "ショ"], meaning: "あつい", strokes: 12, example: "暑い なつ", hint: "日 と 者", example_reading: ["あつ"] },
    { kanji: "美", readings: ["うつく(しい)", "ビ"], meaning: "きれい、うつくしい", strokes: 9, example: "美しい はな", hint: "羊 と 大", example_reading: ["うつく"] },
    { kanji: "悪", readings: ["わる(い)", "アク"], meaning: "わるい", strokes: 11, example: "悪い ことをしない", hint: "亜 と 心", example_reading: ["わる"] },
    { kanji: "重", readings: ["おも(い)", "ジュウ"], meaning: "おもたい", strokes: 9, example: "重い にもつ", hint: "千 と 里", example_reading: ["おも"] },
    { kanji: "深", readings: ["ふか(い)", "シン"], meaning: "ふかい", strokes: 11, example: "深い うみ", hint: "さんずい に 罙", example_reading: ["ふか"] },
    { kanji: "軽", readings: ["かる(い)", "ケイ"], meaning: "かるい", strokes: 12, example: "軽い にもつ", hint: "車 と 圣", example_reading: ["かる"] },

    // --- 動き・行動 ---
    { kanji: "起", readings: ["お(きる)", "キ"], meaning: "おきる", strokes: 10, example: "朝 はやく 起きる", hint: "走 と 己", example_reading: ["お"] },
    { kanji: "遊", readings: ["あそ(ぶ)", "ユウ"], meaning: "あそぶ", strokes: 12, example: "公園 で 遊ぶ", hint: "しんにょう に 方 と 人 と 子", example_reading: ["あそ"] },
    { kanji: "泳", readings: ["およ(ぐ)", "エイ"], meaning: "およぐ", strokes: 8, example: "プール で 泳ぐ", hint: "さんずい に 永", example_reading: ["およ"] },
    { kanji: "飲", readings: ["の(む)", "イン"], meaning: "のむ", strokes: 12, example: "水 を 飲む", hint: "食へん に 欠", example_reading: ["の"] },
    { kanji: "打", readings: ["う(つ)", "ダ"], meaning: "うつ、たたく", strokes: 5, example: "ボール を 打つ", hint: "てへん に 丁", example_reading: ["う"] },
    { kanji: "乗", readings: ["の(る)", "ジョウ"], meaning: "のる", strokes: 9, example: "電車 に 乗る", hint: "ノ と 木 と 北 みたい", example_reading: ["の"] },
    { kanji: "落", readings: ["お(ちる)", "ラク"], meaning: "おちる", strokes: 12, example: "葉 が 落ちる", hint: "くさかんむり と さんずい と 各", example_reading: ["お"] },
    { kanji: "流", readings: ["なが(れる)", "リュウ"], meaning: "ながれる", strokes: 10, example: "川 が 流れる", hint: "さんずい と 充", example_reading: ["なが"] },
    { kanji: "動", readings: ["うご(く)", "ドウ"], meaning: "うごく", strokes: 11, example: "動物", hint: "重 と 力", example_reading: ["どう"] },
    { kanji: "運", readings: ["はこ(ぶ)", "ウン"], meaning: "はこぶ", strokes: 12, example: "運動会", hint: "しんにょう に 軍", example_reading: ["うん"] },
    { kanji: "送", readings: ["おく(る)", "ソウ"], meaning: "おくる", strokes: 9, example: "手紙 を 送る", hint: "しんにょう に 关", example_reading: ["おく"] },
    { kanji: "待", readings: ["ま(つ)", "タイ"], meaning: "まつ", strokes: 9, example: "友だち を 待つ", hint: "ぎょうにんべん に 寺", example_reading: ["ま"] },
    { kanji: "決", readings: ["き(める)", "ケツ"], meaning: "きめる", strokes: 7, example: "ルール を 決める", hint: "にすい に 夬", example_reading: ["き"] },
    { kanji: "勝", readings: ["か(つ)", "ショウ"], meaning: "かつ", strokes: 12, example: "試合 に 勝つ", hint: "月 と 券 みたい", example_reading: ["か"] },
    { kanji: "負", readings: ["ま(ける)", "フ"], meaning: "まける", strokes: 9, example: "勝負 に まける", hint: "ク と 貝", example_reading: ["ぶ"] },
    { kanji: "取", readings: ["と(る)", "シュ"], meaning: "とる", strokes: 8, example: "点 を 取る", hint: "耳 と 又", example_reading: ["と"] },
    { kanji: "受", readings: ["う(ける)", "ジュ"], meaning: "うける", strokes: 8, example: "テスト を 受ける", hint: "ノ と ツ と ワ と 又", example_reading: ["う"] },
    { kanji: "拾", readings: ["ひろ(う)", "シュウ"], meaning: "ひろう", strokes: 9, example: "ゴミ を 拾う", hint: "てへん に 合", example_reading: ["ひろ"] },
    { kanji: "守", readings: ["まも(る)", "シュ"], meaning: "まもる", strokes: 6, example: "約束 を 守る", hint: "うかんむり に 寸", example_reading: ["まも"] },
    { kanji: "使", readings: ["つか(う)", "シ"], meaning: "つかう", strokes: 8, example: "えんぴつ を 使う", hint: "にんべん に 吏", example_reading: ["つか"] },
    { kanji: "持", readings: ["も(つ)", "ジ"], meaning: "もつ", strokes: 9, example: "荷物 を 持つ", hint: "てへん に 寺", example_reading: ["も"] },
    { kanji: "仕", readings: ["シ"], meaning: "つかえる、すること", strokes: 5, example: "仕事 をする", hint: "にんべん に 士", example_reading: ["し"] },
    { kanji: "事", readings: ["こと", "ジ"], meaning: "こと", strokes: 8, example: "食事 をする", hint: "一 と 口 と ヨ と 亅", example_reading: ["じ"] },
    { kanji: "住", readings: ["す(む)", "ジュウ"], meaning: "すむ", strokes: 7, example: "家 に 住む", hint: "にんべん に 主", example_reading: ["す"] },
    { kanji: "植", readings: ["う(える)", "ショク"], meaning: "うえる", strokes: 12, example: "花 を 植える", hint: "木へん に 直", example_reading: ["う"] },
    { kanji: "申", readings: ["もう(す)", "シン"], meaning: "いう", strokes: 5, example: "申しわけ ない", hint: "日 のまんなかに たてぼう", example_reading: ["もう"] },
    { kanji: "進", readings: ["すす(む)", "シン"], meaning: "すすむ", strokes: 11, example: "前 に 進む", hint: "しんにょう に 隹", example_reading: ["すす"] },
    { kanji: "追", readings: ["お(う)", "ツイ"], meaning: "おう", strokes: 9, example: "ボール を 追う", hint: "しんにょう に 𠂤", example_reading: ["お"] },
    { kanji: "登", readings: ["のぼ(る)", "トウ"], meaning: "のぼる", strokes: 12, example: "山 に 登る", hint: "癶 と 豆", example_reading: ["のぼ"] },
    { kanji: "投", readings: ["な(げる)", "トウ"], meaning: "なげる", strokes: 7, example: "ボール を 投げる", hint: "てへん に 殳", example_reading: ["な"] },
    { kanji: "発", readings: ["ハツ"], meaning: "でる、はじまる", strokes: 9, example: "出発 する", hint: "癶 と 弓 と 殳", example_reading: ["ぱつ"] },
    { kanji: "返", readings: ["かえ(す)", "ヘン"], meaning: "かえす", strokes: 7, example: "本 を 返す", hint: "しんにょう に 反", example_reading: ["かえ"] },
    { kanji: "放", readings: ["はな(す)", "ホウ"], meaning: "はなす、てばなす", strokes: 8, example: "放送 する", hint: "方 と 攵", example_reading: ["ほう"] },
    { kanji: "練", readings: ["ね(る)", "レン"], meaning: "くりかえし する", strokes: 14, example: "練習 をする", hint: "いとへん に 東", example_reading: ["れん"] },
    { kanji: "集", readings: ["あつ(める)", "シュウ"], meaning: "あつめる", strokes: 12, example: "切手 を 集める", hint: "隹 のしたに 木", example_reading: ["あつ"] },
    { kanji: "宿", readings: ["やど", "シュク"], meaning: "とまるところ", strokes: 11, example: "宿題 をする", hint: "うかんむり と ひとやね と 百", example_reading: ["しゅく"] },
    { kanji: "助", readings: ["たす(ける)", "ジョ"], meaning: "たすける", strokes: 7, example: "友だち を 助ける", hint: "且 と 力", example_reading: ["たす"] },
    { kanji: "消", readings: ["き(える)", "ショウ"], meaning: "けす、きえる", strokes: 10, example: "火が 消える", hint: "さんずい に 肖", example_reading: ["き"] },
    { kanji: "整", readings: ["ととの(える)", "セイ"], meaning: "ととのえる", strokes: 16, example: "整理 する", hint: "束 と 攵 と 正", example_reading: ["せい"] },
    { kanji: "対", readings: ["タイ"], meaning: "むかう、ペア", strokes: 7, example: "反対 する", hint: "文 と 寸", example_reading: ["たい"] },
    { kanji: "転", readings: ["ころ(がる)", "テン"], meaning: "ころがる", strokes: 11, example: "自転車", hint: "車 と 云", example_reading: ["てん"] },
    { kanji: "配", readings: ["くば(る)", "ハイ"], meaning: "くばる", strokes: 10, example: "プリントを 配る", hint: "酉 と 己", example_reading: ["くば"] },
    { kanji: "反", readings: ["そ(る)", "ハン"], meaning: "かえる、そむく", strokes: 4, example: "反対 する", hint: "厂 に 又", example_reading: ["はん"] },
    { kanji: "開", readings: ["あ(ける)", "カイ"], meaning: "あける", strokes: 12, example: "ドアを 開ける", hint: "門 に 幵", example_reading: ["あ"] },
    { kanji: "去", readings: ["さ(る)", "キョ"], meaning: "さる", strokes: 5, example: "去年 のこと", hint: "土 と ム", example_reading: ["きょ"] },

    // --- 学校・学習・ことば ---
    { kanji: "育", readings: ["そだ(てる)", "イク"], meaning: "そだてる", strokes: 8, example: "花 を 育てる", hint: "亠 と ム と 月", example_reading: ["そだ"] },
    { kanji: "勉", readings: ["ベン"], meaning: "つとめる、がんばる", strokes: 10, example: "勉強 をする", hint: "免 と 力", example_reading: ["べん"] },
    { kanji: "習", readings: ["なら(う)", "シュウ"], meaning: "ならう", strokes: 11, example: "ピアノ を 習う", hint: "羽 と 白", example_reading: ["なら"] },
    { kanji: "漢", readings: ["カン"], meaning: "むかしのちゅうごく", strokes: 13, example: "漢字 をかく", hint: "さんずい と 廿 と 口 と 夫", example_reading: ["かん"] },
    { kanji: "筆", readings: ["ふで", "ヒツ"], meaning: "ふで", strokes: 12, example: "筆箱 をあける", hint: "たけかんむり に 聿", example_reading: ["ふで"] },
    { kanji: "調", readings: ["しら(べる)", "チョウ"], meaning: "しらべる", strokes: 15, example: "意味 を 調べる", hint: "ごんべん に 周", example_reading: ["しら"] },
    { kanji: "談", readings: ["ダン"], meaning: "はなすこと", strokes: 15, example: "相談 をする", hint: "ごんべん に 炎", example_reading: ["だん"] },
    { kanji: "題", readings: ["ダイ"], meaning: "おだい、なまえ", strokes: 18, example: "問題 をとく", hint: "是 と 頁", example_reading: ["だい"] },
    { kanji: "問", readings: ["と(う)", "モン"], meaning: "きく、しつもん", strokes: 11, example: "質問 をする", hint: "門 のなかに 口", example_reading: ["もん"] },
    { kanji: "究", readings: ["キュウ"], meaning: "ふかくしらべる", strokes: 7, example: "研究 をする", hint: "あなかんむり に 九", example_reading: ["きゅう"] },
    { kanji: "写", readings: ["うつ(す)", "シャ"], meaning: "うつす", strokes: 5, example: "写真 をとる", hint: "わかんむり に 与", example_reading: ["しゃ"] },
    { kanji: "真", readings: ["ま", "シン"], meaning: "ほんとう", strokes: 10, example: "真っ白 なゆき", hint: "十 と 目 と 廾", example_reading: ["ま"] },
    { kanji: "詩", readings: ["シ"], meaning: "うた、ポエム", strokes: 13, example: "詩 をよむ", hint: "ごんべん に 寺", example_reading: ["し"] },
    { kanji: "章", readings: ["ショウ"], meaning: "しるし、ぶんしょう", strokes: 11, example: "文章 をよむ", hint: "立 と 早", example_reading: ["しょう"] },
    { kanji: "注", readings: ["そそ(ぐ)", "チュウ"], meaning: "そそぐ、きをつける", strokes: 8, example: "注意 する", hint: "さんずい に 主", example_reading: ["ちゅう"] },
    { kanji: "意", readings: ["イ"], meaning: "こころ、きもち", strokes: 13, example: "意味 がわかる", hint: "音 と 心", example_reading: ["い"] },
    { kanji: "味", readings: ["あじ", "ミ"], meaning: "あじ", strokes: 8, example: "美味しい 味", hint: "口 と 未", example_reading: ["あじ"] },
    { kanji: "業", readings: ["ギョウ"], meaning: "しごと、おこない", strokes: 13, example: "授業 をうける", hint: "丵 と 木", example_reading: ["ぎょう"] },
    { kanji: "実", readings: ["み", "ジツ"], meaning: "ほんとう、きのみ", strokes: 8, example: "木の実 をたべる", hint: "うかんむり に 夫", example_reading: ["み"] },
    { kanji: "役", readings: ["ヤク"], meaning: "つとめ、やくわり", strokes: 7, example: "主役 になる", hint: "ぎょうにんべん に 殳", example_reading: ["やく"] },
    { kanji: "式", readings: ["シキ"], meaning: "やりかた、ぎしき", strokes: 6, example: "計算式 をかく", hint: "弋 と 工", example_reading: ["しき"] },
    { kanji: "級", readings: ["キュウ"], meaning: "クラス、ランク", strokes: 9, example: "三年生 の 学級", hint: "いとへん に 及", example_reading: ["きゅう"] },
    { kanji: "院", readings: ["イン"], meaning: "たてもの", strokes: 10, example: "病院 にいく", hint: "こざとへん に 完", example_reading: ["いん"] },
    { kanji: "研", readings: ["と(ぐ)", "ケン"], meaning: "みがく、しらべる", strokes: 9, example: "研究 する", hint: "石へん に 幵", example_reading: ["けん"] },
    { kanji: "表", readings: ["おもて", "ヒョウ"], meaning: "おもて、あらわす", strokes: 8, example: "表 をつくる", hint: "土 と 木 と 衣 のまざったかたち", example_reading: ["ひょう"] },
    { kanji: "終", readings: ["お(わる)", "シュウ"], meaning: "おわる", strokes: 11, example: "授業 が 終わる", hint: "いとへん に 冬", example_reading: ["お"] },

    // --- 時間・数・方向 ---
    { kanji: "期", readings: ["キ"], meaning: "きまったじかん", strokes: 12, example: "一学期", hint: "其 と 月", example_reading: ["き"] },
    { kanji: "急", readings: ["いそ(ぐ)", "キュウ"], meaning: "いそぐ", strokes: 9, example: "急いで はしる", hint: "ク と ヨ と 心", example_reading: ["いそ"] },
    { kanji: "速", readings: ["はや(い)", "ソク"], meaning: "はやい", strokes: 10, example: "足 が 速い", hint: "しんにょう に 束", example_reading: ["はや"] },
    { kanji: "定", readings: ["さだ(める)", "テイ"], meaning: "きめる", strokes: 8, example: "予定 をたてる", hint: "うかんむり に 疋", example_reading: ["てい"] },
    { kanji: "度", readings: ["ド"], meaning: "かいすう、おんど", strokes: 9, example: "温度 をはかる", hint: "まだれ と 廿 と 又", example_reading: ["ど"] },
    { kanji: "倍", readings: ["バイ"], meaning: "〜こぶん", strokes: 10, example: "二倍 になる", hint: "にんべん に 咅", example_reading: ["ばい"] },
    { kanji: "秒", readings: ["ビョウ"], meaning: "じかんの単位", strokes: 9, example: "十秒 かぞえる", hint: "のぎへん に 少", example_reading: ["びょう"] },
    { kanji: "平", readings: ["たい(ら)", "ヘイ"], meaning: "たいら", strokes: 5, example: "平和", hint: "干 と ハ", example_reading: ["へい"] },
    { kanji: "予", readings: ["ヨ"], meaning: "あらかじめ", strokes: 4, example: "予約 する", hint: "マ と 亅", example_reading: ["よ"] },
    { kanji: "全", readings: ["まった(く)", "ゼン"], meaning: "すべて", strokes: 6, example: "全部 たべる", hint: "入 と 王", example_reading: ["ぜん"] },
    { kanji: "相", readings: ["あい", "ソウ"], meaning: "おたがい", strokes: 9, example: "相談 する", hint: "木 と 目", example_reading: ["そう"] },
    { kanji: "代", readings: ["か(わる)", "ダイ"], meaning: "かわる", strokes: 5, example: "交代 する", hint: "にんべん に 弋", example_reading: ["たい"] },
    { kanji: "向", readings: ["む(かう)", "コウ"], meaning: "むかう", strokes: 6, example: "前を 向く", hint: "ノ と 冂 と 口", example_reading: ["む"] },
    { kanji: "央", readings: ["オウ"], meaning: "まんなか", strokes: 5, example: "中央", hint: "大 のなかに 冂", example_reading: ["おう"] },
    { kanji: "横", readings: ["よこ", "オウ"], meaning: "よこ", strokes: 15, example: "横断 歩道", hint: "木へん に 黄", example_reading: ["おう"] },
    { kanji: "次", readings: ["つぎ", "ジ"], meaning: "つぎ", strokes: 6, example: "次の ページ", hint: "にすい に 欠", example_reading: ["つぎ"] },
    { kanji: "等", readings: ["ひと(しい)", "トウ"], meaning: "おなじ", strokes: 12, example: "平等 にわける", hint: "たけかんむり に 寺", example_reading: ["どう"] },

    // --- 物・道具・食べ物 ---
    { kanji: "荷", readings: ["に", "カ"], meaning: "にもつ", strokes: 10, example: "荷物 をもつ", hint: "くさかんむり に 何", example_reading: ["に"] },
    { kanji: "具", readings: ["グ"], meaning: "どうぐ", strokes: 8, example: "道具 をつかう", hint: "目 と 一 と ハ", example_reading: ["ぐ"] },
    { kanji: "皿", readings: ["さら", "ベイ"], meaning: "おさら", strokes: 5, example: "皿 をあらう", hint: "血 のした", example_reading: ["さら"] },
    { kanji: "酒", readings: ["さけ", "シュ"], meaning: "おさけ", strokes: 10, example: "お酒 をのむ", hint: "さんずい に 酉", example_reading: ["さけ"] },
    { kanji: "炭", readings: ["すみ", "タン"], meaning: "すみ", strokes: 9, example: "石炭", hint: "山 と 灰", example_reading: ["たん"] },
    { kanji: "鉄", readings: ["テツ"], meaning: "てつ", strokes: 13, example: "地下鉄 にのる", hint: "かねへん に 失", example_reading: ["てつ"] },
    { kanji: "豆", readings: ["まめ", "トウ"], meaning: "まめ", strokes: 7, example: "大豆 をたべる", hint: "一 と 口 と 䒑 と 一", example_reading: ["ず"] },
    { kanji: "湯", readings: ["ゆ", "トウ"], meaning: "おゆ", strokes: 12, example: "お湯 をわかす", hint: "さんずい に 昜", example_reading: ["ゆ"] },
    { kanji: "箱", readings: ["はこ", "ソウ"], meaning: "はこ", strokes: 15, example: "箱 にいれる", hint: "たけかんむり に 相", example_reading: ["はこ"] },
    { kanji: "板", readings: ["いた", "ハン"], meaning: "いた", strokes: 8, example: "黒板 にかく", hint: "木へん に 反", example_reading: ["ばん"] },
    { kanji: "皮", readings: ["かわ", "ヒ"], meaning: "かわ", strokes: 5, example: "みかんの 皮", hint: "尸 と 又 みたい", example_reading: ["かわ"] },
    { kanji: "品", readings: ["しな", "ヒン"], meaning: "しなもの", strokes: 9, example: "商品 をかう", hint: "口 が３つ", example_reading: ["ひん"] },
    { kanji: "服", readings: ["フク"], meaning: "きるもの", strokes: 8, example: "洋服 をきる", hint: "月 と 卩 と 又", example_reading: ["ふく"] },
    { kanji: "物", readings: ["もの", "ブツ"], meaning: "もの", strokes: 8, example: "動物", hint: "牛へん に 勿", example_reading: ["ぶつ"] },
    { kanji: "薬", readings: ["くすり", "ヤク"], meaning: "くすり", strokes: 16, example: "薬 をのむ", hint: "くさかんむり に 楽", example_reading: ["くすり"] },
    { kanji: "油", readings: ["あぶら", "ユ"], meaning: "あぶら", strokes: 8, example: "油 をひく", hint: "さんずい に 由", example_reading: ["あぶら"] },
    { kanji: "羊", readings: ["ひつじ", "ヨウ"], meaning: "ひつじ", strokes: 6, example: "羊 の毛", hint: "ソ と 王 みたい", example_reading: ["ひつじ"] },
    { kanji: "笛", readings: ["ふえ", "テキ"], meaning: "ふえ", strokes: 11, example: "笛 をふく", hint: "たけかんむり に 由", example_reading: ["ふえ"] },
    { kanji: "球", readings: ["たま", "キュウ"], meaning: "ボール", strokes: 11, example: "地球", hint: "王へん に 求", example_reading: ["きゅう"] },
    { kanji: "銀", readings: ["ギン"], meaning: "ぎんいろ、おかね", strokes: 14, example: "銀行 にいく", hint: "かねへん に 艮", example_reading: ["ぎん"] },
    { kanji: "祭", readings: ["まつ(り)", "サイ"], meaning: "おまつり", strokes: 11, example: "お祭り にいく", hint: "月 と 又 のしたに 示", example_reading: ["まつ"] },

    // --- その他・概念 ---
    { kanji: "化", readings: ["ば(ける)", "カ"], meaning: "かわる", strokes: 4, example: "変化 する", hint: "にんべん に ヒ", example_reading: ["か"] },
    { kanji: "和", readings: ["ワ"], meaning: "なごやか、にほん", strokes: 8, example: "平和 なせかい", hint: "のぎへん に 口", example_reading: ["わ"] },
    { kanji: "委", readings: ["イ"], meaning: "まかせる", strokes: 8, example: "委員 になる", hint: "禾 と 女", example_reading: ["い"] },
    { kanji: "係", readings: ["かかり", "ケイ"], meaning: "かかり", strokes: 9, example: "係 のひと", hint: "にんべん に 系", example_reading: ["かかり"] },
    { kanji: "号", readings: ["ゴウ"], meaning: "しるし、なまえ", strokes: 5, example: "信号 をみる", hint: "口 と 丂", example_reading: ["ごう"] },
    { kanji: "始", readings: ["はじ(める)", "シ"], meaning: "はじめる", strokes: 8, example: "開始 する", hint: "女へん に 台", example_reading: ["し"] },
    { kanji: "商", readings: ["あきな(う)", "ショウ"], meaning: "あきない、おみせ", strokes: 11, example: "商店 街", hint: "亠 と ハ と 冂 と 八 と 口", example_reading: ["しょう"] },
    { kanji: "世", readings: ["よ", "セイ"], meaning: "よのなか", strokes: 5, example: "世界", hint: "廿 に L", example_reading: ["せ"] },
    { kanji: "着", readings: ["き(る)", "チャク"], meaning: "きる、つく", strokes: 12, example: "服を 着る", hint: "羊 と 目", example_reading: ["き"] },
    { kanji: "病", readings: ["やまい", "ビョウ"], meaning: "びょうき", strokes: 10, example: "病気 になる", hint: "やまいだれ に 丙", example_reading: ["びょう"] },
    { kanji: "部", readings: ["ブ"], meaning: "わける、グループ", strokes: 11, example: "部屋", hint: "立 と 口 と こざとへん", example_reading: ["へ"] },
    { kanji: "福", readings: ["フク"], meaning: "しあわせ", strokes: 13, example: "幸福", hint: "しめすへん に 畐", example_reading: ["ふく"] },
    { kanji: "面", readings: ["おもて", "メン"], meaning: "かお、おもて", strokes: 9, example: "地面", hint: "一 と ノ と 囗 のなかに 目", example_reading: ["めん"] },
    { kanji: "由", readings: ["ユウ"], meaning: "わけ", strokes: 5, example: "理由 をきく", hint: "田 のうえが つきでる", example_reading: ["ゆう"] },
    { kanji: "有", readings: ["あ(る)", "ユウ"], meaning: "ある", strokes: 6, example: "有名 なひと", hint: "ナ と 月", example_reading: ["ゆう"] },
    { kanji: "様", readings: ["さま", "ヨウ"], meaning: "さま", strokes: 14, example: "お客様", hint: "木へん に 羊 と 水", example_reading: ["さま"] },
    { kanji: "両", readings: ["リョウ"], meaning: "ふたつ、りょうほう", strokes: 6, example: "両手 をあげる", hint: "一 と 冂 と 山 みたい", example_reading: ["りょう"] },
    { kanji: "列", readings: ["レツ"], meaning: "ならぶ", strokes: 6, example: "列 にならぶ", hint: "歹 と 刂", example_reading: ["れつ"] },
    { kanji: "洋", readings: ["ヨウ"], meaning: "がいこく、うみ", strokes: 9, example: "太平洋", hint: "さんずい に 羊", example_reading: ["よう"] },
    { kanji: "曲", readings: ["まが(る)", "キョク"], meaning: "まがる、おんがく", strokes: 6, example: "道が 曲がる", hint: "日 のなかに 縦棒２本", example_reading: ["まが"] },
    { kanji: "感", readings: ["カン"], meaning: "きもちがうごく", strokes: 13, example: "感動 する", hint: "咸 と 心", example_reading: ["かん"] },
    { kanji: "昭", readings: ["ショウ"], meaning: "あきらか", strokes: 9, example: "昭和", hint: "日 と 召", example_reading: ["しょう"] },
    { kanji: "想", readings: ["ソウ"], meaning: "おもう", strokes: 13, example: "想像 する", hint: "相 と 心", example_reading: ["ぞう"] },
    { kanji: "旅", readings: ["たび", "リョ"], meaning: "たび", strokes: 10, example: "旅行 にいく", hint: "方 と ひとやね と 氏", example_reading: ["りょ"] },
    { kanji: "礼", readings: ["レイ"], meaning: "おじぎ、おかえし", strokes: 5, example: "お礼 をいう", hint: "しめすへん に L", example_reading: ["れい"] },
    { kanji: "丁", readings: ["チョウ", "テイ"], meaning: "まちのくぎり", strokes: 2, example: "一丁目", hint: "一 のしたに 亅", example_reading: ["ちょう"] },
    { kanji: "他", readings: ["ほか", "タ"], meaning: "ほかのひとやもの", strokes: 5, example: "他の 人にきく", hint: "にんべん に 也", example_reading: ["ほか"] },
    { kanji: "短", readings: ["みじか(い)", "タン"], meaning: "みじかい", strokes: 12, example: "短い えんぴつ", hint: "矢 と 豆", example_reading: ["みじか"] },
    { kanji: "柱", readings: ["はしら", "チュウ"], meaning: "いえをささえる たてのき", strokes: 9, example: "家の 柱", hint: "木へん に 主", example_reading: ["はしら"] },
    { kanji: "帳", readings: ["チョウ"], meaning: "ノート", strokes: 11, example: "連絡帳 をかく", hint: "巾へん に 長", example_reading: ["ちょう"] },
    { kanji: "昔", readings: ["むかし", "セキ"], meaning: "ずっとまえ", strokes: 8, example: "昔 ばなし", hint: "廿 と 日", example_reading: ["むかし"] },
    { kanji: "第", readings: ["ダイ"], meaning: "じゅんばん", strokes: 11, example: "第一位 になる", hint: "たけかんむり と 弓 に 似た形", example_reading: ["だい"] },
];