// kanji/grade6.js - 6年生の漢字データ（181字）
// 各漢字: kanji, readings(読み方), meaning(意味), strokes(画数), example(例文), hint(覚え方ヒント)

const GRADE6_KANJI = [
    // --- あ行 ---
    { kanji: "異", readings: ["こと(なる)", "イ"], meaning: "ちがう", strokes: 11, example: "異常", hint: "田 と 共" },
    { kanji: "遺", readings: ["のこ(す)", "イ"], meaning: "のこす", strokes: 15, example: "遺跡", hint: "しんにょう に 貴" },
    { kanji: "域", readings: ["イキ"], meaning: "ばしょ、はんい", strokes: 11, example: "地域", hint: "土へん に 或" },
    { kanji: "宇", readings: ["ウ"], meaning: "おおきなやね、そら", strokes: 6, example: "宇宙", hint: "うかんむり に 于" },
    { kanji: "映", readings: ["うつ(る)", "エイ"], meaning: "うつる", strokes: 9, example: "映画", hint: "日へん に 央" },
    { kanji: "延", readings: ["の(びる)", "エン"], meaning: "のびる", strokes: 8, example: "延長", hint: "えんにょう に 正" },
    { kanji: "沿", readings: ["そ(う)", "エン"], meaning: "そう", strokes: 8, example: "沿岸", hint: "さんずい に 㕣" },

    // --- か行 ---
    { kanji: "我", readings: ["われ", "ガ"], meaning: "わたし", strokes: 7, example: "我慢", hint: "手 と 戈" },
    { kanji: "灰", readings: ["はい", "カイ"], meaning: "はい", strokes: 6, example: "灰色", hint: "がんだれ に 火" },
    { kanji: "拡", readings: ["カク"], meaning: "ひろげる", strokes: 8, example: "拡大", hint: "てへん に 広" },
    { kanji: "干", readings: ["ほ(す)", "カン"], meaning: "ほす", strokes: 3, example: "干し草", hint: "二 と 縦棒" },
    { kanji: "株", readings: ["かぶ", "シュ"], meaning: "きのねっこ", strokes: 10, example: "株式会社", hint: "木へん に 朱" },
    { kanji: "割", readings: ["わ(る)", "カツ"], meaning: "わる", strokes: 12, example: "割引", hint: "害 と 刂" },
    { kanji: "閣", readings: ["カク"], meaning: "りっぱなたてもの", strokes: 14, example: "内閣", hint: "門 に 各" },
    { kanji: "革", readings: ["かわ", "カク"], meaning: "かわ", strokes: 9, example: "革靴", hint: "廿 と 口 と 十" },
    { kanji: "巻", readings: ["ま(く)", "カン"], meaning: "まく", strokes: 9, example: "竜巻", hint: "龹 と 己" },
    { kanji: "危", readings: ["あぶ(ない)", "キ"], meaning: "あぶない", strokes: 6, example: "危険", hint: "ク と 厄" },
    { kanji: "机", readings: ["つくえ", "キ"], meaning: "つくえ", strokes: 6, example: "学習机", hint: "木へん に 几" },
    { kanji: "簡", readings: ["カン"], meaning: "ふだがみ、てまがかからない", strokes: 18, example: "簡単", hint: "たけかんむり に 間" },
    { kanji: "看", readings: ["カン"], meaning: "みまもる", strokes: 9, example: "看板", hint: "手 のしたに 目" },
    { kanji: "揮", readings: ["キ"], meaning: "ふるう", strokes: 12, example: "指揮", hint: "てへん に 軍" },
    { kanji: "貴", readings: ["とうと(い)", "キ"], meaning: "ねうちがある", strokes: 12, example: "貴重", hint: "中 と 一 と 貝" },
    { kanji: "疑", readings: ["うたが(う)", "ギ"], meaning: "うたがう", strokes: 14, example: "疑問", hint: "ヒ と 矢 と マ と 疋" },
    { kanji: "吸", readings: ["す(う)", "キュウ"], meaning: "すう", strokes: 6, example: "深呼吸", hint: "口へん に 及" },
    { kanji: "供", readings: ["そな(える)", "キョウ"], meaning: "そなえる、おとも", strokes: 8, example: "子供", hint: "にんべん に 共" },
    { kanji: "筋", readings: ["すじ", "キン"], meaning: "すじ", strokes: 12, example: "筋肉", hint: "たけかんむり に 肋" },
    { kanji: "勤", readings: ["つと(める)", "キン"], meaning: "しごとをする", strokes: 13, example: "通勤", hint: "堇 と 力" },
    { kanji: "郷", readings: ["ゴウ", "キョウ"], meaning: "ふるさと", strokes: 11, example: "故郷", hint: "幺 と 白 と ヒ と こざとへん" },
    { kanji: "胸", readings: ["むね", "キョウ"], meaning: "むね", strokes: 10, example: "胸ぐら", hint: "月へん に 匈" },
    { kanji: "劇", readings: ["ゲキ"], meaning: "おしばい", strokes: 15, example: "演劇", hint: "虍 と 豕 と 刂" },
    { kanji: "系", readings: ["ケイ"], meaning: "つながり", strokes: 7, example: "太陽系", hint: "ノ と 糸" },
    { kanji: "敬", readings: ["うやま(う)", "ケイ"], meaning: "うやまう", strokes: 12, example: "敬語", hint: "苟 と 攵" },
    { kanji: "警", readings: ["ケイ"], meaning: "きをつける", strokes: 19, example: "警察", hint: "敬 と 言" },
    { kanji: "激", readings: ["はげ(しい)", "ゲキ"], meaning: "はげしい", strokes: 16, example: "感激", hint: "さんずい に 敫" },
    { kanji: "穴", readings: ["あな", "ケツ"], meaning: "あな", strokes: 5, example: "落とし穴", hint: "うかんむり に 八" },
    { kanji: "絹", readings: ["きぬ", "ケン"], meaning: "きぬ", strokes: 13, example: "絹糸", hint: "いとへん に 肙" },
    { kanji: "権", readings: ["ケン"], meaning: "けんり", strokes: 15, example: "権利", hint: "木へん に 雚" },
    { kanji: "憲", readings: ["ケン"], meaning: "きまり", strokes: 16, example: "憲法", hint: "うかんむり に 害 と 心" },
    { kanji: "源", readings: ["みなもと", "ゲン"], meaning: "みなもと", strokes: 13, example: "資源", hint: "さんずい に 原" },
    { kanji: "厳", readings: ["きび(しい)", "ゲン"], meaning: "きびしい", strokes: 17, example: "厳しい", hint: "ツ と 厂 と 敢" },
    { kanji: "己", readings: ["おのれ", "コ"], meaning: "じぶん", strokes: 3, example: "自己", hint: "コ と L" },
    { kanji: "呼", readings: ["よ(ぶ)", "コ"], meaning: "よぶ、いきをはく", strokes: 8, example: "呼吸", hint: "口へん に 乎" },
    { kanji: "誤", readings: ["あやま(る)", "ゴ"], meaning: "まちがえる", strokes: 14, example: "誤解", hint: "ごんべん に 呉" },
    { kanji: "后", readings: ["コウ"], meaning: "きさき", strokes: 6, example: "皇后", hint: "厂 と 一 と 口" },
    { kanji: "孝", readings: ["コウ"], meaning: "おやをたいせつにする", strokes: 7, example: "親孝行", hint: "老 のしたに 子" },
    { kanji: "皇", readings: ["コウ"], meaning: "きみ、おおきい", strokes: 9, example: "天皇", hint: "白 と 王" },
    { kanji: "紅", readings: ["べに", "コウ"], meaning: "あか", strokes: 9, example: "紅白", hint: "いとへん に 工" },
    { kanji: "降", readings: ["お(りる)", "コウ"], meaning: "おりる、ふる", strokes: 10, example: "降る", hint: "こざとへん に 夅" },
    { kanji: "刻", readings: ["きざ(む)", "コク"], meaning: "きざむ、じかん", strokes: 8, example: "時刻", hint: "亥 と 刂" },
    { kanji: "鋼", readings: ["はがね", "コウ"], meaning: "はがね", strokes: 16, example: "鉄鋼", hint: "かねへん に 岡" },

    // --- さ行 ---
    { kanji: "座", readings: ["すわ(る)", "ザ"], meaning: "すわるばしょ", strokes: 10, example: "座席", hint: "まだれ に 坐" },
    { kanji: "砂", readings: ["すな", "サ"], meaning: "すな", strokes: 9, example: "砂場", hint: "石へん に 少" },
    { kanji: "困", readings: ["こま(る)", "コン"], meaning: "こまる", strokes: 7, example: "困難", hint: "くにがまえ に 木" },
    { kanji: "骨", readings: ["ほね", "コツ"], meaning: "ほね", strokes: 10, example: "骨折", hint: "冎 と 月" },
    { kanji: "穀", readings: ["コク"], meaning: "たべもののもと", strokes: 14, example: "穀物", hint: "禾 と 几 と 殳" },
    { kanji: "蚕", readings: ["かいこ", "サン"], meaning: "かいこ", strokes: 10, example: "蚕の糸", hint: "天 と 虫" },
    { kanji: "冊", readings: ["サツ"], meaning: "ほんをかぞえる", strokes: 5, example: "一冊", hint: "本がならんでいるかたち" },
    { kanji: "策", readings: ["サク"], meaning: "はかりごと", strokes: 12, example: "対策", hint: "たけかんむり に 刺 のひだり" },
    { kanji: "裁", readings: ["さば(く)", "サイ"], meaning: "きる、さばく", strokes: 12, example: "裁判", hint: "十 と 戈 と 衣" },
    { kanji: "済", readings: ["す(む)", "サイ"], meaning: "おわる", strokes: 11, example: "経済", hint: "さんずい に 斉" },
    { kanji: "至", readings: ["いた(る)", "シ"], meaning: "いたる", strokes: 6, example: "夏至", hint: "一 と ム と 土" },
    { kanji: "私", readings: ["わたし", "シ"], meaning: "わたし", strokes: 7, example: "私服", hint: "のぎへん に ム" },
    { kanji: "姿", readings: ["すがた", "シ"], meaning: "すがた", strokes: 9, example: "姿勢", hint: "次 と 女" },
    { kanji: "視", readings: ["シ"], meaning: "みる", strokes: 11, example: "視力", hint: "示 と 見" },
    { kanji: "詞", readings: ["シ"], meaning: "ことば", strokes: 12, example: "作詞", hint: "ごんべん に 司" },
    { kanji: "誌", readings: ["シ"], meaning: "かきとめる", strokes: 14, example: "雑誌", hint: "ごんべん に 志" },
    { kanji: "磁", readings: ["ジ"], meaning: "じしゃく", strokes: 14, example: "磁石", hint: "石へん に 茲" },
    { kanji: "射", readings: ["い(る)", "シャ"], meaning: "いる、うつ", strokes: 10, example: "注射", hint: "身 と 寸" },
    { kanji: "捨", readings: ["す(てる)", "シャ"], meaning: "すてる", strokes: 11, example: "捨てる", hint: "てへん に 舎" },
    { kanji: "尺", readings: ["シャク"], meaning: "ながさのたんい", strokes: 4, example: "巻尺", hint: "尸 と ヽ" },
    { kanji: "若", readings: ["わか(い)", "ジャク"], meaning: "わかい", strokes: 8, example: "若者", hint: "くさかんむり に 右" },
    { kanji: "樹", readings: ["ジュ"], meaning: "き", strokes: 16, example: "樹木", hint: "木へん と 豆 と 寸" },
    { kanji: "収", readings: ["おさ(める)", "シュウ"], meaning: "おさめる", strokes: 4, example: "吸収", hint: "りっしんべん みたいなの と 攵" },
    { kanji: "宗", readings: ["シュウ"], meaning: "おおもと", strokes: 8, example: "宗教", hint: "うかんむり に 示" },
    { kanji: "就", readings: ["つ(く)", "シュウ"], meaning: "つく", strokes: 12, example: "就職", hint: "京 と 尤" },
    { kanji: "衆", readings: ["シュウ"], meaning: "おおぜい", strokes: 12, example: "群衆", hint: "血 と 衆 のした" },
    { kanji: "従", readings: ["したが(う)", "ジュウ"], meaning: "したがう", strokes: 10, example: "服従", hint: "ぎょうにんべん に 从 と 止" },
    { kanji: "縦", readings: ["たて", "ジュウ"], meaning: "たて", strokes: 16, example: "縦書き", hint: "いとへん に 従" },
    { kanji: "熟", readings: ["う(れる)", "ジュク"], meaning: "うれる、よくにる", strokes: 15, example: "熟語", hint: "孰 と 灬" },
    { kanji: "縮", readings: ["ちぢ(む)", "シュク"], meaning: "ちぢむ", strokes: 17, example: "短縮", hint: "いとへん に 宿" },
    { kanji: "署", readings: ["ショ"], meaning: "やくしょ", strokes: 13, example: "消防署", hint: "罒 と 者" },
    { kanji: "純", readings: ["ジュン"], meaning: "まじりけがない", strokes: 10, example: "純白", hint: "いとへん に 屯" },
    { kanji: "処", readings: ["ショ"], meaning: "おこなう、ところ", strokes: 5, example: "処理", hint: "夂 と 几" },
    { kanji: "諸", readings: ["ショ"], meaning: "いろいろ", strokes: 15, example: "諸島", hint: "ごんべん に 者" },
    { kanji: "除", readings: ["のぞ(く)", "ジョ"], meaning: "のぞく", strokes: 10, example: "掃除", hint: "こざとへん に 余" },
    { kanji: "針", readings: ["はり", "シン"], meaning: "はり", strokes: 10, example: "時計の 針", hint: "かねへん に 十" },
    { kanji: "仁", readings: ["ジン"], meaning: "おもいやり", strokes: 4, example: "仁愛", hint: "にんべん に 二" },
    { kanji: "蒸", readings: ["む(す)", "ジョウ"], meaning: "むす", strokes: 13, example: "水蒸気", hint: "くさかんむり に 烝" },
    { kanji: "城", readings: ["しろ", "ジョウ"], meaning: "しろ", strokes: 9, example: "お城", hint: "土へん に 成" },
    { kanji: "障", readings: ["さわ(る)", "ショウ"], meaning: "ふせぐ、さまたげ", strokes: 14, example: "故障", hint: "こざとへん に 章" },
    { kanji: "将", readings: ["ショウ"], meaning: "ひきいる、これから", strokes: 10, example: "将来 のゆめ", hint: "爿 と ツ と 寸" },
    { kanji: "傷", readings: ["きず", "ショウ"], meaning: "きず", strokes: 13, example: "傷 がなおる", hint: "にんべん に 𠂉 と 日 と 勹" },
    { kanji: "垂", readings: ["た(れる)", "スイ"], meaning: "たれる", strokes: 8, example: "垂直", hint: "ノ と 土 と 廿" },
    { kanji: "推", readings: ["スイ"], meaning: "おす", strokes: 11, example: "推理 する", hint: "てへん に 隹" },
    { kanji: "寸", readings: ["スン"], meaning: "みじかい、ながさ", strokes: 3, example: "寸法", hint: "十 に 点" },
    { kanji: "専", readings: ["セン"], meaning: "もっぱら", strokes: 9, example: "専門", hint: "十 と 恵 のうえ と 寸" },
    { kanji: "宣", readings: ["セン"], meaning: "のべる", strokes: 9, example: "宣言", hint: "うかんむり に 亘" },
    { kanji: "盛", readings: ["さか(ん)", "セイ"], meaning: "さかん", strokes: 11, example: "大盛り", hint: "成 と 皿" },
    { kanji: "聖", readings: ["セイ"], meaning: "きよい、りっぱ", strokes: 13, example: "神聖", hint: "耳 と 口 と 王" },
    { kanji: "誠", readings: ["まこと", "セイ"], meaning: "まこと", strokes: 13, example: "誠実", hint: "ごんべん に 成" },
    { kanji: "泉", readings: ["いずみ", "セン"], meaning: "いずみ", strokes: 9, example: "温泉", hint: "白 と 水" },
    { kanji: "洗", readings: ["あら(う)", "セン"], meaning: "あらう", strokes: 9, example: "洗濯", hint: "さんずい に 先" },
    { kanji: "染", readings: ["そ(める)", "セン"], meaning: "そめる", strokes: 9, example: "伝染", hint: "さんずい に 九 と 木" },
    { kanji: "善", readings: ["よ(い)", "ゼン"], meaning: "よい", strokes: 12, example: "親善", hint: "羊 と ツ と 口" },
    { kanji: "奏", readings: ["かな(でる)", "ソウ"], meaning: "かなでる", strokes: 9, example: "演奏", hint: "三 と 人 と 天" },
    { kanji: "窓", readings: ["まど", "ソウ"], meaning: "まど", strokes: 11, example: "窓ガラス", hint: "あなかんむり に ム と 心" },
    { kanji: "創", readings: ["ソウ"], meaning: "はじめる、つくる", strokes: 12, example: "創造", hint: "倉 と 刂" },
    { kanji: "装", readings: ["よそお(う)", "ソウ"], meaning: "かざる、きるもの", strokes: 12, example: "服装", hint: "壮 と 衣" },
    { kanji: "層", readings: ["ソウ"], meaning: "かさなる", strokes: 14, example: "地層", hint: "しかばね に 曽" },
    { kanji: "操", readings: ["あやつ(る)", "ソウ"], meaning: "あやつる", strokes: 16, example: "体操", hint: "てへん に 品 と 木" },
    { kanji: "蔵", readings: ["くら", "ゾウ"], meaning: "くら、しまう", strokes: 15, example: "冷蔵庫", hint: "くさかんむり に 厂 と 臣 と 戈" },
    { kanji: "臓", readings: ["ゾウ"], meaning: "からだのなかの つくり", strokes: 19, example: "心臓", hint: "月へん に 蔵" },
    { kanji: "存", readings: ["ソン"], meaning: "ある、いる", strokes: 6, example: "保存", hint: "ナ と ノ と 子" },
    { kanji: "尊", readings: ["とうと(い)", "ソン"], meaning: "とうとい、たっとい", strokes: 12, example: "尊敬", hint: "八 と 酉 と 寸" },

    // --- た行 ---
    { kanji: "宅", readings: ["タク"], meaning: "いえ", strokes: 6, example: "自宅", hint: "うかんむり に 乇" },
    { kanji: "担", readings: ["にな(う)", "タン"], meaning: "になう、うけもつ", strokes: 8, example: "担任", hint: "てへん に 旦" },
    { kanji: "探", readings: ["さが(す)", "タン"], meaning: "さがす", strokes: 11, example: "探検", hint: "てへん に 穴 と 木" },
    { kanji: "誕", readings: ["タン"], meaning: "うまれる", strokes: 15, example: "誕生日", hint: "ごんべん に 延" },
    { kanji: "段", readings: ["ダン"], meaning: "きざみ", strokes: 9, example: "階段", hint: "ノ と Ｌ と 殳" },
    { kanji: "暖", readings: ["あたた(かい)", "ダン"], meaning: "あたたかい", strokes: 13, example: "暖房", hint: "日へん に 爰" },
    { kanji: "値", readings: ["ね", "チ"], meaning: "ねだん", strokes: 10, example: "値段", hint: "にんべん に 直" },
    { kanji: "宙", readings: ["チュウ"], meaning: "そら", strokes: 8, example: "宇宙", hint: "うかんむり に 由" },
    { kanji: "忠", readings: ["チュウ"], meaning: "まごころ", strokes: 8, example: "忠実", hint: "中 と 心" },
    { kanji: "著", readings: ["あらわ(す)", "チョ"], meaning: "あらわす、いちじるしい", strokes: 11, example: "著者", hint: "くさかんむり に 者" },
    { kanji: "庁", readings: ["チョウ"], meaning: "やくしょ", strokes: 5, example: "市役所", hint: "まだれ に 丁" },
    { kanji: "頂", readings: ["いただ(く)", "チョウ"], meaning: "いただく、てっぺん", strokes: 11, example: "頂上", hint: "丁 と 頁" },
    { kanji: "潮", readings: ["しお", "チョウ"], meaning: "しお", strokes: 15, example: "満潮", hint: "さんずい に 朝" },
    { kanji: "賃", readings: ["チン"], meaning: "かりるおかね", strokes: 13, example: "家賃", hint: "任 と 貝" },
    { kanji: "痛", readings: ["いた(い)", "ツウ"], meaning: "いたい", strokes: 12, example: "頭痛", hint: "やまいだれ に マ と 用" },
    { kanji: "展", readings: ["テン"], meaning: "ひろげる", strokes: 10, example: "展示", hint: "しかばね に 廿 と 衣 みたい" },
    { kanji: "討", readings: ["う(つ)", "トウ"], meaning: "うつ", strokes: 10, example: "討論", hint: "ごんべん に 寸" },
    { kanji: "党", readings: ["トウ"], meaning: "なかま", strokes: 10, example: "政党", hint: "尚 と 兄" },
    { kanji: "糖", readings: ["トウ"], meaning: "さとう", strokes: 16, example: "砂糖", hint: "米へん に 唐" },
    { kanji: "届", readings: ["とど(く)", "トド"], meaning: "とどく", strokes: 8, example: "送り届ける", hint: "しかばね に 由" },

    // --- な行 ---
    { kanji: "難", readings: ["むずか(しい)", "ナン"], meaning: "むずかしい", strokes: 18, example: "困難", hint: "廿 と 口 と 夫 と 隹" },
    { kanji: "乳", readings: ["ちち", "ニュウ"], meaning: "ちち", strokes: 8, example: "牛乳", hint: "孚 と 乚" },
    { kanji: "認", readings: ["みと(める)", "ニン"], meaning: "みとめる", strokes: 14, example: "確認", hint: "ごんべん に 忍" },
    { kanji: "納", readings: ["おさ(める)", "ノウ"], meaning: "おさめる", strokes: 10, example: "納得", hint: "いとへん に 内" },
    { kanji: "脳", readings: ["ノウ"], meaning: "のうみそ", strokes: 11, example: "頭脳", hint: "月へん に ツ と 凶" },

    // --- は行 ---
    { kanji: "派", readings: ["ハ"], meaning: "わかれる、わかれ", strokes: 9, example: "立派", hint: "さんずい に 𠂢" },
    { kanji: "拝", readings: ["おが(む)", "ハイ"], meaning: "おがむ", strokes: 8, example: "礼拝", hint: "てへん に 丰 と 一" },
    { kanji: "背", readings: ["せ", "ハイ"], meaning: "せなか", strokes: 9, example: "背中", hint: "北 と 月" },
    { kanji: "肺", readings: ["ハイ"], meaning: "はい", strokes: 9, example: "肺活量", hint: "月へん に 市" },
    { kanji: "俳", readings: ["ハイ"], meaning: "わざおぎ", strokes: 10, example: "俳優", hint: "にんべん に 非" },
    { kanji: "班", readings: ["ハン"], meaning: "わける、グループ", strokes: 10, example: "班長", hint: "王 と 刂 と 王" },
    { kanji: "晩", readings: ["バン"], meaning: "よる", strokes: 12, example: "今晩", hint: "日へん に 免" },
    { kanji: "否", readings: ["いな", "ヒ"], meaning: "ちがう", strokes: 7, example: "否定", hint: "不 と 口" },
    { kanji: "批", readings: ["ヒ"], meaning: "うつ", strokes: 7, example: "批判", hint: "てへん に 比" },
    { kanji: "秘", readings: ["ひめ(る)", "ヒ"], meaning: "ひめる、かくす", strokes: 10, example: "秘密", hint: "のぎへん に 必" },
    { kanji: "腹", readings: ["はら", "フク"], meaning: "おなか", strokes: 13, example: "腹痛", hint: "月へん に 復 の右" },
    { kanji: "陛", readings: ["ヘイ"], meaning: "きざはし", strokes: 10, example: "天皇陛下", hint: "こざとへん に 比 と 土" },
    { kanji: "奮", readings: ["ふる(う)", "フン"], meaning: "ふるう", strokes: 16, example: "興奮", hint: "大 と 隹 と 田" },
    { kanji: "並", readings: ["なら(ぶ)", "ヘイ"], meaning: "ならぶ", strokes: 8, example: "並行", hint: "ツ と 一 と 业" },
    { kanji: "閉", readings: ["し(める)", "ヘイ"], meaning: "しめる", strokes: 11, example: "閉会", hint: "門 に 才" },
    { kanji: "片", readings: ["かた", "ヘン"], meaning: "かたほう", strokes: 4, example: "片道", hint: "木 を半分にしたかたち" },
    { kanji: "補", readings: ["おぎな(う)", "ホ"], meaning: "おぎなう", strokes: 12, example: "補助", hint: "ころもへん に 甫" },
    { kanji: "暮", readings: ["く(らす)", "ボ"], meaning: "くらす、ひぐれ", strokes: 14, example: "夕暮れ", hint: "くさかんむり に 日 と 大 と 日" },
    { kanji: "宝", readings: ["たから", "ホウ"], meaning: "たから", strokes: 8, example: "宝物", hint: "うかんむり に 玉" },
    { kanji: "訪", readings: ["おとず(れる)", "ホウ"], meaning: "たずねる", strokes: 11, example: "訪問", hint: "ごんべん に 方" },

    // --- ま行 ---
    { kanji: "亡", readings: ["な(くなる)", "ボウ"], meaning: "なくなる", strokes: 3, example: "死亡", hint: "亠 と L" },
    { kanji: "忘", readings: ["わす(れる)", "ボウ"], meaning: "わすれる", strokes: 7, example: "忘れ物", hint: "亡 と 心" },
    { kanji: "棒", readings: ["ボウ"], meaning: "ぼう", strokes: 12, example: "鉄棒", hint: "木へん に 奉" },
    { kanji: "枚", readings: ["マイ"], meaning: "まい", strokes: 8, example: "一枚", hint: "木へん に 攵" },
    { kanji: "密", readings: ["ミツ"], meaning: "こまかい、ひそか", strokes: 11, example: "秘密", hint: "うかんむり に 必 と 山" },
    { kanji: "幕", readings: ["マク"], meaning: "まく", strokes: 13, example: "開幕", hint: "莫 のしたに 巾" },
    { kanji: "盟", readings: ["メイ"], meaning: "ちかう", strokes: 13, example: "同盟", hint: "明 と 皿" },
    { kanji: "模", readings: ["モ"], meaning: "かたどる", strokes: 14, example: "模様", hint: "木へん に 莫" },

    // --- や行 ---
    { kanji: "訳", readings: ["わけ", "ヤク"], meaning: "わけ、いいかえる", strokes: 11, example: "通訳", hint: "ごんべん に 尺" },
    { kanji: "郵", readings: ["ユウ"], meaning: "しゅくば", strokes: 11, example: "郵便", hint: "垂 と こざとへん" },
    { kanji: "優", readings: ["やさ(しい)", "ユウ"], meaning: "やさしい、すぐれる", strokes: 17, example: "優勝", hint: "にんべん に 憂" },
    { kanji: "幼", readings: ["おさな(い)", "ヨウ"], meaning: "おさない", strokes: 5, example: "幼児", hint: "幺 と 力" },
    { kanji: "欲", readings: ["ほ(しい)", "ヨク"], meaning: "ほしい", strokes: 11, example: "食欲", hint: "谷 と 欠" },
    { kanji: "翌", readings: ["ヨク"], meaning: "つぎの", strokes: 11, example: "翌日", hint: "羽 と 立" },

    // --- ら・わ行 ---
    { kanji: "乱", readings: ["みだ(れる)", "ラン"], meaning: "みだれる", strokes: 7, example: "混乱", hint: "舌 と L" },
    { kanji: "卵", readings: ["たまご", "ラン"], meaning: "たまご", strokes: 7, example: "卵焼き", hint: "卯 のなかに 点々" },
    { kanji: "覧", readings: ["ラン"], meaning: "みる", strokes: 17, example: "展覧会", hint: "臣 と ひとやね と 見" },
    { kanji: "裏", readings: ["うら", "リ"], meaning: "うら", strokes: 13, example: "裏口", hint: "亠 と 里 と 衣のした" },
    { kanji: "律", readings: ["リツ"], meaning: "きまり", strokes: 9, example: "法律", hint: "ぎょうにんべん に 聿" },
    { kanji: "臨", readings: ["のぞ(む)", "リン"], meaning: "のぞむ", strokes: 18, example: "臨時", hint: "臣 と ひとやね と 品" },
    { kanji: "朗", readings: ["ほが(らか)", "ロウ"], meaning: "ほがらか", strokes: 10, example: "朗読", hint: "良 と 月" },
    { kanji: "論", readings: ["ロン"], meaning: "はなしあう", strokes: 15, example: "議論", hint: "ごんべん に 侖" }
];