// kanji/grade2.js - 2年生の漢字データ（160字）
// 各漢字: kanji, readings(読み方), meaning(意味), strokes(画数), example(例文), hint(覚え方ヒント), example_reading(例文での読み方)

const GRADE2_KANJI = [
    // --- 数・量 ---
    { kanji: "万", readings: ["マン", "バン"], meaning: "とても おおきい かず", strokes: 3, example: "一万円 もらった", hint: "一 の した に ノ", example_reading: ["まん"] },
    { kanji: "半", readings: ["ハン", "なか(ば)"], meaning: "はんぶん", strokes: 5, example: "半分こ する", hint: "八 と 十 と 一", example_reading: ["はん"] },
    { kanji: "多", readings: ["おお(い)", "タ"], meaning: "たくさん", strokes: 6, example: "多い ほうが いい", hint: "夕 が ２つ", example_reading: ["おお"] },
    { kanji: "少", readings: ["すく(ない)", "ショウ"], meaning: "すくない", strokes: 4, example: "少し だけ ちょうだい", hint: "小 に ノ がついた", example_reading: ["すこ"] },
    { kanji: "数", readings: ["かず", "スウ"], meaning: "かぞえること", strokes: 13, example: "数 をかぞえる", hint: "米 と 女 と 攵", example_reading: ["かず"] },

    // --- 時間 ---
    { kanji: "時", readings: ["とき", "ジ"], meaning: "じかん", strokes: 10, example: "三時 に会う", hint: "日 と 寺", example_reading: ["じ"] },
    { kanji: "間", readings: ["あいだ", "カン"], meaning: "あいだ、ま", strokes: 12, example: "時間 をまもる", hint: "門 の なかに 日", example_reading: ["かん"] },
    { kanji: "週", readings: ["シュウ"], meaning: "いっしゅうかん", strokes: 11, example: "来週 あそぼう", hint: "しんにょう に 周", example_reading: ["しゅう"] },
    { kanji: "今", readings: ["いま", "コン"], meaning: "いま、このとき", strokes: 4, example: "今 なんじ？", hint: "ひとやね の した に ラ", example_reading: ["いま"] },
    { kanji: "朝", readings: ["あさ", "チョウ"], meaning: "あさ", strokes: 12, example: "朝 ごはんをたべる", hint: "十 と 日 と 十 と 月", example_reading: ["あさ"] },
    { kanji: "昼", readings: ["ひる", "チュウ"], meaning: "ひる、おひるま", strokes: 9, example: "昼 ごはんをたべる", hint: "尺 の あいだに 日", example_reading: ["ひる"] },
    { kanji: "夜", readings: ["よる", "ヤ"], meaning: "よる、くらいとき", strokes: 8, example: "夜 になった", hint: "なべぶた に 人 と 夕", example_reading: ["よる"] },
    { kanji: "毎", readings: ["マイ"], meaning: "いつも、くりかえし", strokes: 6, example: "毎日 がんばる", hint: "ノ と 母", example_reading: ["まい"] },
    { kanji: "前", readings: ["まえ", "ゼン"], meaning: "まえ", strokes: 9, example: "前 にすすむ", hint: "八 と 月 と 刂", example_reading: ["まえ"] },
    { kanji: "後", readings: ["うし(ろ)", "ゴ"], meaning: "うしろ、あと", strokes: 9, example: "後ろ をみる", hint: "ぎょうにんべん に いろいろ", example_reading: ["うし"] },
    { kanji: "午", readings: ["ゴ"], meaning: "ひる", strokes: 4, example: "午前 と 午後", hint: "牛 ににているけど ちょっとちがう", example_reading: ["ご"] },
    { kanji: "春", readings: ["はる", "シュン"], meaning: "はる", strokes: 9, example: "春 がきた", hint: "三 と 人 と 日", example_reading: ["はる"] },
    { kanji: "夏", readings: ["なつ", "カ"], meaning: "なつ", strokes: 10, example: "夏 やすみ", hint: "一 と 自 と 夊", example_reading: ["なつ"] },
    { kanji: "秋", readings: ["あき", "シュウ"], meaning: "あき", strokes: 9, example: "秋 のもみじ", hint: "のぎへん に 火", example_reading: ["あき"] },
    { kanji: "冬", readings: ["ふゆ", "トウ"], meaning: "ふゆ", strokes: 5, example: "冬 はさむい", hint: "にすい の うえに ノ と く", example_reading: ["ふゆ"] },

    // --- 曜日 ---
    { kanji: "曜", readings: ["ヨウ"], meaning: "ようび", strokes: 18, example: "月曜日 がすき", hint: "日 と ヨ と 隹", example_reading: ["よう"] },

    // --- 方向・場所 ---
    { kanji: "東", readings: ["ひがし", "トウ"], meaning: "ひがし", strokes: 8, example: "東 のそら", hint: "木 の なかに 日", example_reading: ["ひがし"] },
    { kanji: "西", readings: ["にし", "セイ"], meaning: "にし", strokes: 6, example: "西 にしずむ", hint: "四 ににているけど うえがあく", example_reading: ["にし"] },
    { kanji: "南", readings: ["みなみ", "ナン"], meaning: "みなみ", strokes: 9, example: "南 のしま", hint: "十 と 冂 と 羊 みたい", example_reading: ["みなみ"] },
    { kanji: "北", readings: ["きた", "ホク"], meaning: "きた", strokes: 5, example: "北 のくに", hint: "ふたり が せなかあわせ", example_reading: ["きた"] },
    { kanji: "方", readings: ["かた", "ホウ"], meaning: "ほうがく、やりかた", strokes: 4, example: "この 方 がいい", hint: "なべぶた の した にノ", example_reading: ["ほう"] },
    { kanji: "地", readings: ["チ", "ジ"], meaning: "じめん、とち", strokes: 6, example: "地面 にすわる", hint: "つちへん に 也", example_reading: ["じ"] },
    { kanji: "場", readings: ["ば", "ジョウ"], meaning: "ばしょ", strokes: 12, example: "広い 場所", hint: "つちへん に 昜", example_reading: ["ば"] },
    { kanji: "里", readings: ["さと", "リ"], meaning: "さと、むら", strokes: 7, example: "ふるさと にかえる", hint: "田 と 土", example_reading: ["さと"] },
    { kanji: "内", readings: ["うち", "ナイ"], meaning: "なか、うち", strokes: 4, example: "家 の 内がわ", hint: "冂 の なかに 人", example_reading: ["うち"] },
    { kanji: "外", readings: ["そと", "ガイ"], meaning: "そと", strokes: 5, example: "外 であそぶ", hint: "夕 と ト", example_reading: ["そと"] },
    { kanji: "遠", readings: ["とお(い)", "エン"], meaning: "とおい", strokes: 13, example: "遠く にみえる", hint: "しんにょう に 袁", example_reading: ["とお"] },
    { kanji: "近", readings: ["ちか(い)", "キン"], meaning: "ちかい", strokes: 7, example: "近く のこうえん", hint: "しんにょう に 斤", example_reading: ["ちか"] },
    { kanji: "門", readings: ["かど", "モン"], meaning: "もん、いりぐち", strokes: 8, example: "門 のまえ", hint: "とびら が ２まい", example_reading: ["もん"] },
    { kanji: "道", readings: ["みち", "ドウ"], meaning: "みち", strokes: 12, example: "道 をわたる", hint: "しんにょう に 首", example_reading: ["みち"] },

    // --- 自然 ---
    { kanji: "雲", readings: ["くも", "ウン"], meaning: "そらにうかぶ しろいもの", strokes: 12, example: "雲 がながれる", hint: "雨 の した に 云", example_reading: ["くも"] },
    { kanji: "雪", readings: ["ゆき", "セツ"], meaning: "ふゆに ふる しろいもの", strokes: 11, example: "雪 がふる", hint: "雨 の した に ヨ", example_reading: ["ゆき"] },
    { kanji: "風", readings: ["かぜ", "フウ"], meaning: "かぜ", strokes: 9, example: "風 がふく", hint: "几 の なかに 虫", example_reading: ["かぜ"] },
    { kanji: "星", readings: ["ほし", "セイ"], meaning: "よぞらの ひかるもの", strokes: 9, example: "星 がきれい", hint: "日 と 生", example_reading: ["ほし"] },
    { kanji: "光", readings: ["ひかり", "コウ"], meaning: "ひかり、かがやき", strokes: 6, example: "光 がさす", hint: "⺌ と 儿", example_reading: ["ひかり"] },
    { kanji: "海", readings: ["うみ", "カイ"], meaning: "ひろい しおみず", strokes: 9, example: "海 でおよぐ", hint: "さんずい に 毎", example_reading: ["うみ"] },
    { kanji: "池", readings: ["いけ", "チ"], meaning: "みずがたまった ところ", strokes: 6, example: "池 のこい", hint: "さんずい に 也", example_reading: ["いけ"] },
    { kanji: "谷", readings: ["たに", "コク"], meaning: "やまと やまの あいだ", strokes: 7, example: "谷川 であそぶ", hint: "ハ と 人 と 口", example_reading: ["たに"] },
    { kanji: "原", readings: ["はら", "ゲン"], meaning: "ひろい のはら", strokes: 10, example: "草原 をはしる", hint: "がんだれ に 白 と 小", example_reading: ["げん"] },
    { kanji: "野", readings: ["の", "ヤ"], meaning: "のはら", strokes: 11, example: "野原 であそぶ", hint: "里 と 予", example_reading: ["の"] },
    { kanji: "岩", readings: ["いわ", "ガン"], meaning: "おおきな いし", strokes: 8, example: "岩 のうえ", hint: "山 と 石", example_reading: ["いわ"] },

    // --- 人・体 ---
    { kanji: "体", readings: ["からだ", "タイ"], meaning: "からだ", strokes: 7, example: "体 をうごかす", hint: "にんべん に 本", example_reading: ["からだ"] },
    { kanji: "顔", readings: ["かお", "ガン"], meaning: "かお", strokes: 18, example: "笑顔 がすてき", hint: "彦 と 頁", example_reading: ["がお"] },
    { kanji: "首", readings: ["くび", "シュ"], meaning: "くび", strokes: 9, example: "首 をまわす", hint: "八 と 自 みたい", example_reading: ["くび"] },
    { kanji: "心", readings: ["こころ", "シン"], meaning: "こころ、きもち", strokes: 4, example: "心 がやさしい", hint: "ハート の かたち", example_reading: ["こころ"] },
    { kanji: "毛", readings: ["け", "モウ"], meaning: "け、かみのけ", strokes: 4, example: "毛糸 であむ", hint: "ノ と 三 みたい", example_reading: ["け"] },
    { kanji: "声", readings: ["こえ", "セイ"], meaning: "こえ、おと", strokes: 7, example: "大きな 声 でよむ", hint: "士 の した に いろいろ", example_reading: ["こえ"] },

    // --- 家族・人 ---
    { kanji: "父", readings: ["ちち", "フ"], meaning: "おとうさん", strokes: 4, example: "父 とははとあそぶ", hint: "ハ と メ", example_reading: ["ちち"] },
    { kanji: "母", readings: ["はは", "ボ"], meaning: "おかあさん", strokes: 5, example: "ちちと母 がはなす", hint: "しかく の なかに てん ２つ", example_reading: ["はは"] },
    { kanji: "兄", readings: ["あに", "ケイ"], meaning: "おにいさん", strokes: 5, example: "兄 とサッカー", hint: "口 の した に 儿", example_reading: ["あに"] },
    { kanji: "弟", readings: ["おとうと", "テイ"], meaning: "おとうと", strokes: 7, example: "ちいさな弟と野球", hint: "弓 に いろいろ", example_reading: ["おとうと"] },
    { kanji: "姉", readings: ["あね", "シ"], meaning: "おねえさん", strokes: 8, example: "姉 にきく", hint: "おんなへん に 市", example_reading: ["あね"] },
    { kanji: "妹", readings: ["いもうと", "マイ"], meaning: "いもうと", strokes: 8, example: "妹 とあそぶ", hint: "おんなへん に 未", example_reading: ["いもうと"] },
    { kanji: "親", readings: ["おや", "シン"], meaning: "おやこ", strokes: 16, example: "親 にそうだん", hint: "立 と 木 と 見", example_reading: ["おや"] },
    { kanji: "友", readings: ["とも", "ユウ"], meaning: "ともだち", strokes: 4, example: "友だち がたくさん", hint: "ナ と 又", example_reading: ["とも"] },

    // --- 動物 ---
    { kanji: "馬", readings: ["うま", "バ"], meaning: "おおきな どうぶつ", strokes: 10, example: "馬 にのる", hint: "うま の かたち", example_reading: ["うま"] },
    { kanji: "牛", readings: ["うし", "ギュウ"], meaning: "ミルクをくれる どうぶつ", strokes: 4, example: "牛 のミルク", hint: "ノ と 二 と たてぼう", example_reading: ["うし"] },
    { kanji: "魚", readings: ["さかな", "ギョ"], meaning: "みずの なかの いきもの", strokes: 11, example: "川で魚 をつる", hint: "⺈ と 田 と 灬", example_reading: ["さかな"] },
    { kanji: "鳥", readings: ["とり", "チョウ"], meaning: "そらをとぶ いきもの", strokes: 11, example: "すきな鳥はカラス ", hint: "とり の かたち", example_reading: ["とり"] },
    { kanji: "羽", readings: ["はね", "ウ"], meaning: "とりの つばさ", strokes: 6, example: "羽 をひろげる", hint: "はね が ２まい", example_reading: ["はね"] },

    // --- 食べ物 ---
    { kanji: "米", readings: ["こめ", "ベイ"], meaning: "おこめ", strokes: 6, example: "米 をたく", hint: "八 と 十 と 八", example_reading: ["こめ"] },
    { kanji: "麦", readings: ["むぎ", "バク"], meaning: "パンのざいりょう", strokes: 7, example: "麦 ばたけ", hint: "十 か ら 夕 と 夊", example_reading: ["むぎ"] },
    { kanji: "茶", readings: ["チャ", "サ"], meaning: "おちゃ", strokes: 9, example: "お茶 をのむ", hint: "くさかんむり に 余", example_reading: ["ちゃ"] },
    { kanji: "肉", readings: ["ニク"], meaning: "おにく", strokes: 6, example: "お肉 をやく", hint: "冂 の なかに 人 ２つ", example_reading: ["にく"] },
    { kanji: "食", readings: ["た(べる)", "ショク"], meaning: "たべること", strokes: 9, example: "食べる のがすき", hint: "ひとやね に 良", example_reading: ["た"] },

    // --- 学校・勉強 ---
    { kanji: "教", readings: ["おし(える)", "キョウ"], meaning: "おしえる", strokes: 11, example: "先生 が 教える", hint: "孝 と 攵", example_reading: ["おし"] },
    { kanji: "読", readings: ["よ(む)", "ドク"], meaning: "よむ", strokes: 14, example: "本 を 読む", hint: "ごんべん に 売", example_reading: ["よ"] },
    { kanji: "書", readings: ["か(く)", "ショ"], meaning: "かく", strokes: 10, example: "字 を 書く", hint: "聿 と 日", example_reading: ["か"] },
    { kanji: "記", readings: ["しる(す)", "キ"], meaning: "しるす、かきとめる", strokes: 10, example: "日記 をかく", hint: "ごんべん に 己", example_reading: ["き"] },
    { kanji: "話", readings: ["はな(す)", "ワ"], meaning: "はなす", strokes: 13, example: "友だち と 話す", hint: "ごんべん に 舌", example_reading: ["はな"] },
    { kanji: "言", readings: ["い(う)", "ゲン"], meaning: "いう、ことば", strokes: 7, example: "何 と 言った？", hint: "口 の うえ に よこぼう", example_reading: ["い"] },
    { kanji: "語", readings: ["かた(る)", "ゴ"], meaning: "ことば", strokes: 14, example: "国語 がすき", hint: "ごんべん に 吾", example_reading: ["ご"] },
    { kanji: "答", readings: ["こた(える)", "トウ"], meaning: "こたえる", strokes: 12, example: "答え をいう", hint: "たけかんむり に 合", example_reading: ["こた"] },
    { kanji: "算", readings: ["サン"], meaning: "かぞえる、けいさん", strokes: 14, example: "算数 がとくい", hint: "たけかんむり に 目 と 廾", example_reading: ["さん"] },
    { kanji: "画", readings: ["ガ", "カク"], meaning: "え、かく", strokes: 8, example: "絵画をみる", hint: "一 と 田 と 凵", example_reading: ["が"] },
    { kanji: "歌", readings: ["うた", "カ"], meaning: "うた", strokes: 14, example: "歌 をうたう", hint: "可 と 欠 が ２つ", example_reading: ["うた"] },
    { kanji: "図", readings: ["ズ", "ト"], meaning: "ず、ちず", strokes: 7, example: "地図 をみる", hint: "くにがまえ の なかに いろいろ", example_reading: ["ず"] },
    { kanji: "工", readings: ["コウ", "ク"], meaning: "つくること", strokes: 3, example: "工作 をする", hint: "カタカナ の エ", example_reading: ["こう"] },
    { kanji: "理", readings: ["リ"], meaning: "ことわり、りゆう", strokes: 11, example: "理科 のじっけん", hint: "王 と 里", example_reading: ["り"] },
    { kanji: "科", readings: ["カ"], meaning: "きょうか", strokes: 9, example: "理科 がすき", hint: "のぎへん に 斗", example_reading: ["か"] },

    // --- 行動 ---
    { kanji: "行", readings: ["い(く)", "コウ"], meaning: "いく", strokes: 6, example: "学校 へ 行く", hint: "ぎょうにんべん に いろいろ", example_reading: ["い"] },
    { kanji: "来", readings: ["く(る)", "ライ"], meaning: "くる", strokes: 7, example: "友だち が 来る", hint: "一 と 米 みたい", example_reading: ["く"] },
    { kanji: "帰", readings: ["かえ(る)", "キ"], meaning: "かえる", strokes: 10, example: "家 に 帰る", hint: "ヨ と 巾 と ヨ", example_reading: ["かえ"] },
    { kanji: "走", readings: ["はし(る)", "ソウ"], meaning: "はしる", strokes: 7, example: "速く 走る", hint: "土 と 止 と し", example_reading: ["はし"] },
    { kanji: "歩", readings: ["ある(く)", "ホ"], meaning: "あるく", strokes: 8, example: "公園 を 歩く", hint: "止 と 少", example_reading: ["ある"] },
    { kanji: "止", readings: ["と(まる)", "シ"], meaning: "とまる、やめる", strokes: 4, example: "止まって ください", hint: "つちへん ににている", example_reading: ["と"] },
    { kanji: "通", readings: ["とお(る)", "ツウ"], meaning: "とおる", strokes: 10, example: "道 を 通る", hint: "しんにょう に マ と 用", example_reading: ["とお"] },
    { kanji: "切", readings: ["き(る)", "セツ"], meaning: "きる", strokes: 4, example: "紙 を 切る", hint: "七 と 刀", example_reading: ["き"] },
    { kanji: "引", readings: ["ひ(く)", "イン"], meaning: "ひく", strokes: 4, example: "ドア を 引く", hint: "弓 と たてぼう", example_reading: ["ひ"] },
    { kanji: "合", readings: ["あ(う)", "ゴウ"], meaning: "あう、あわせる", strokes: 6, example: "力 を 合わせる", hint: "ひとやね に 一 と 口", example_reading: ["あ"] },
    { kanji: "回", readings: ["まわ(る)", "カイ"], meaning: "まわる、かいすう", strokes: 6, example: "三回 やった", hint: "口 の なかに 口", example_reading: ["かい"] },
    { kanji: "考", readings: ["かんが(える)", "コウ"], meaning: "かんがえる", strokes: 6, example: "よく 考える", hint: "耂 に 巧 の へん", example_reading: ["かんが"] },
    { kanji: "知", readings: ["し(る)", "チ"], meaning: "しる", strokes: 8, example: "答え を 知る", hint: "矢 と 口", example_reading: ["し"] },
    { kanji: "作", readings: ["つく(る)", "サク"], meaning: "つくる", strokes: 7, example: "工作 を 作る", hint: "にんべん に 乍", example_reading: ["つく"] },
    { kanji: "当", readings: ["あ(たる)", "トウ"], meaning: "あたる", strokes: 6, example: "くじ が 当たる", hint: "⺌ と ヨ", example_reading: ["あ"] },
    { kanji: "活", readings: ["カツ"], meaning: "いきいき する", strokes: 9, example: "生活 がたのしい", hint: "さんずい に 舌", example_reading: ["かつ"] },
    { kanji: "用", readings: ["もち(いる)", "ヨウ"], meaning: "つかう", strokes: 5, example: "これ を 用いる", hint: "月 に たてぼう", example_reading: ["もち"] },
    { kanji: "組", readings: ["く(む)", "ソ"], meaning: "くむ、グループ", strokes: 11, example: "一組 のこども", hint: "いとへん に 且", example_reading: ["くみ"] },
    { kanji: "交", readings: ["まじ(わる)", "コウ"], meaning: "まじわる", strokes: 6, example: "交差点 をわたる", hint: "なべぶた に 父", example_reading: ["こう"] },
    { kanji: "売", readings: ["う(る)", "バイ"], meaning: "うる", strokes: 7, example: "本 を 売る", hint: "士 と 儿 と 冖", example_reading: ["う"] },
    { kanji: "買", readings: ["か(う)", "バイ"], meaning: "かう", strokes: 12, example: "おかし を 買う", hint: "四 と 貝", example_reading: ["か"] },
    { kanji: "計", readings: ["はか(る)", "ケイ"], meaning: "はかる、けいさん", strokes: 9, example: "時計 をみる", hint: "ごんべん に 十", example_reading: ["けい"] },

    // --- 形容詞・状態 ---
    { kanji: "強", readings: ["つよ(い)", "キョウ"], meaning: "つよい", strokes: 11, example: "強い かぜ", hint: "弓 と ム と 虫", example_reading: ["つよ"] },
    { kanji: "弱", readings: ["よわ(い)", "ジャク"], meaning: "よわい", strokes: 10, example: "弱い こころ", hint: "弓 ２つ に ン ２つ", example_reading: ["よわ"] },
    { kanji: "高", readings: ["たか(い)", "コウ"], meaning: "たかい", strokes: 10, example: "高い やま", hint: "なべぶた に 口 と 冂", example_reading: ["たか"] },
    { kanji: "太", readings: ["ふと(い)", "タイ"], meaning: "ふとい", strokes: 4, example: "太い えだ", hint: "大 に てん がついた", example_reading: ["ふと"] },
    { kanji: "細", readings: ["ほそ(い)", "サイ"], meaning: "ほそい", strokes: 11, example: "細い みち", hint: "いとへん に 田", example_reading: ["ほそ"] },
    { kanji: "長", readings: ["なが(い)", "チョウ"], meaning: "ながい", strokes: 8, example: "長い はなし", hint: "ながい かみのけ みたい", example_reading: ["なが"] },
    { kanji: "広", readings: ["ひろ(い)", "コウ"], meaning: "ひろい", strokes: 5, example: "広い へや", hint: "まだれ に ム", example_reading: ["ひろ"] },
    { kanji: "直", readings: ["なお(す)", "チョク"], meaning: "まっすぐ、なおす", strokes: 8, example: "まちがい を 直す", hint: "十 と 目 と L", example_reading: ["なお"] },
    { kanji: "明", readings: ["あか(るい)", "メイ"], meaning: "あかるい", strokes: 8, example: "明るい へや", hint: "日 と 月", example_reading: ["あか"] },
    { kanji: "新", readings: ["あたら(しい)", "シン"], meaning: "あたらしい", strokes: 13, example: "新しい くつ", hint: "立 と 木 と 斤", example_reading: ["あたら"] },
    { kanji: "古", readings: ["ふる(い)", "コ"], meaning: "ふるい", strokes: 5, example: "古い いえ", hint: "十 と 口", example_reading: ["ふる"] },
    { kanji: "丸", readings: ["まる", "ガン"], meaning: "まるい", strokes: 3, example: "丸い ボール", hint: "九 に てん", example_reading: ["まる"] },
    { kanji: "黒", readings: ["くろ", "コク"], meaning: "くろいろ", strokes: 11, example: "黒い ねこ", hint: "里 の した に 灬", example_reading: ["くろ"] },
    { kanji: "黄", readings: ["き", "コウ"], meaning: "きいろ", strokes: 11, example: "黄色い はな", hint: "廿 と 由 と 八", example_reading: ["き"] },
    { kanji: "同", readings: ["おな(じ)", "ドウ"], meaning: "おなじ", strokes: 6, example: "同じ クラス", hint: "冂 の なかに 一 と 口", example_reading: ["おな"] },
    { kanji: "楽", readings: ["たの(しい)", "ガク"], meaning: "たのしい、おんがく", strokes: 13, example: "楽しい えんそく", hint: "白 と 木 と いろいろ", example_reading: ["たの"] },

    // --- 建物・構造 ---
    { kanji: "家", readings: ["いえ", "カ"], meaning: "いえ、おうち", strokes: 10, example: "家 にかえる", hint: "うかんむり に 豕", example_reading: ["いえ"] },
    { kanji: "室", readings: ["シツ"], meaning: "へや", strokes: 9, example: "教室 にはいる", hint: "うかんむり に 至", example_reading: ["しつ"] },
    { kanji: "戸", readings: ["と", "コ"], meaning: "と、ドア", strokes: 4, example: "戸 をしめる", hint: "とびら の かたち", example_reading: ["と"] },
    { kanji: "店", readings: ["みせ", "テン"], meaning: "おみせ", strokes: 8, example: "店 にいく", hint: "まだれ に 占", example_reading: ["みせ"] },
    { kanji: "寺", readings: ["てら", "ジ"], meaning: "おてら", strokes: 6, example: "お寺 にいく", hint: "土 と 寸", example_reading: ["てら"] },
    { kanji: "京", readings: ["キョウ", "ケイ"], meaning: "みやこ", strokes: 8, example: "東京 にいく", hint: "なべぶた に 口 と 小", example_reading: ["きょう"] },
    { kanji: "国", readings: ["くに", "コク"], meaning: "くに", strokes: 8, example: "日本 は いい 国", hint: "くにがまえ に 玉", example_reading: ["くに"] },
    { kanji: "園", readings: ["その", "エン"], meaning: "そのえん", strokes: 13, example: "公園 であそぶ", hint: "くにがまえ に 袁", example_reading: ["えん"] },
    { kanji: "公", readings: ["コウ"], meaning: "おおやけ", strokes: 4, example: "公園 がすき", hint: "ハ と ム", example_reading: ["こう"] },
    { kanji: "台", readings: ["ダイ", "タイ"], meaning: "だい、うてな", strokes: 5, example: "台 のうえ", hint: "ム と 口", example_reading: ["だい"] },

    // --- 線・形 ---
    { kanji: "線", readings: ["セン"], meaning: "せん、ライン", strokes: 15, example: "まっすぐな線", hint: "いとへん に 泉", example_reading: ["せん"] },
    { kanji: "形", readings: ["かたち", "ケイ"], meaning: "かたち", strokes: 7, example: "四角い 形", hint: "开 と 彡", example_reading: ["かたち"] },
    { kanji: "角", readings: ["かど", "カク"], meaning: "かど、つの", strokes: 7, example: "四角 のはこ", hint: "つの のかたち", example_reading: ["かく"] },
    { kanji: "点", readings: ["テン"], meaning: "てん、ポイント", strokes: 9, example: "百点 をとる", hint: "占 と 灬", example_reading: ["てん"] },
    { kanji: "矢", readings: ["や", "シ"], meaning: "や、やじるし", strokes: 5, example: "矢 をいる", hint: "ノ と 大 に よこぼう", example_reading: ["や"] },
    { kanji: "弓", readings: ["ゆみ", "キュウ"], meaning: "ゆみ", strokes: 3, example: "弓矢 をつかう", hint: "ゆみ の かたち", example_reading: ["ゆみ"] },
    { kanji: "刀", readings: ["かたな", "トウ"], meaning: "かたな", strokes: 2, example: "刀 でたたかう", hint: "カタカナ の カ ににている", example_reading: ["かたな"] },

    // --- その他 ---
    { kanji: "電", readings: ["デン"], meaning: "でんき", strokes: 13, example: "電気 をつける", hint: "雨 と 乚 と 電", example_reading: ["でん"] },
    { kanji: "汽", readings: ["キ"], meaning: "じょうき", strokes: 7, example: "汽車 にのる", hint: "さんずい に 气", example_reading: ["き"] },
    { kanji: "船", readings: ["ふね", "セン"], meaning: "ふね", strokes: 11, example: "船 にのる", hint: "舟 と 八 と 口", example_reading: ["ふね"] },
    { kanji: "自", readings: ["ジ", "シ"], meaning: "じぶん", strokes: 6, example: "自分 でやる", hint: "目 と ノ", example_reading: ["じ"] },
    { kanji: "分", readings: ["わ(ける)", "ブン"], meaning: "わける、ぶん", strokes: 4, example: "半分 にする", hint: "八 と 刀", example_reading: ["ぶん"] },
    { kanji: "何", readings: ["なに", "カ"], meaning: "なに", strokes: 7, example: "何 がすき？", hint: "にんべん に 可", example_reading: ["なに"] },
    { kanji: "才", readings: ["サイ"], meaning: "さいのう、とし", strokes: 3, example: "七才 になった", hint: "十 と ノ", example_reading: ["さい"] },
    { kanji: "番", readings: ["バン"], meaning: "ばんごう", strokes: 12, example: "一番 になる", hint: "釆 と 田", example_reading: ["ばん"] },
    { kanji: "頭", readings: ["あたま", "トウ"], meaning: "あたま", strokes: 16, example: "頭 がいい友だち", hint: "豆 と 頁", example_reading: ["あたま"] },
    { kanji: "思", readings: ["おも(う)", "シ"], meaning: "おもう", strokes: 9, example: "そう 思う", hint: "田 と 心", example_reading: ["おも"] },
    { kanji: "色", readings: ["いろ", "ショク"], meaning: "いろ", strokes: 6, example: "どんな色 がすき？", hint: "⺈ と 巴", example_reading: ["いろ"] },
    { kanji: "紙", readings: ["かみ", "シ"], meaning: "かみ", strokes: 10, example: "おり紙 であそぶ", hint: "いとへん に 氏", example_reading: ["がみ"] },
    { kanji: "絵", readings: ["え", "カイ"], meaning: "え、ピクチャー", strokes: 12, example: "絵 をかく", hint: "いとへん に 会", example_reading: ["え"] },
    { kanji: "市", readings: ["いち", "シ"], meaning: "まち、いちば", strokes: 5, example: "市場 にいく", hint: "なべぶた に 巾", example_reading: ["いち"] },
    { kanji: "会", readings: ["あ(う)", "カイ"], meaning: "あう", strokes: 6, example: "友だち に 会う", hint: "ひとやね に 云", example_reading: ["あ"] },
    { kanji: "社", readings: ["やしろ", "シャ"], meaning: "やしろ、かいしゃ", strokes: 7, example: "神社 にいく", hint: "しめすへん に 土", example_reading: ["じゃ"] },
    { kanji: "元", readings: ["もと", "ゲン"], meaning: "もと、はじめ", strokes: 4, example: "元気 ですか", hint: "二 と 儿", example_reading: ["げん"] },
    { kanji: "晴", readings: ["は(れる)", "セイ"], meaning: "おてんきがよい", strokes: 12, example: "今日は 晴れだ", hint: "日 と 青", example_reading: ["は"] },
    { kanji: "聞", readings: ["き(く)", "ブン"], meaning: "みみできく", strokes: 14, example: "音楽を 聞く", hint: "門 の なかに 耳", example_reading: ["き"] },
    { kanji: "鳴", readings: ["な(く)", "メイ"], meaning: "とりなどが こえをだす", strokes: 14, example: "ことりが 鳴く", hint: "口 と 鳥", example_reading: ["な"] },
];