// kanji/grade6.js - 6年生の漢字データ（181字）
// 各漢字: kanji, readings(読み方), meaning(意味), strokes(画数), example(例文), hint(覚え方ヒント), example_reading(例文での読み方)

const GRADE6_KANJI = [
    // --- あ行 ---
    { kanji: "異", readings: ["こと(なる)", "イ"], meaning: "ちがう", strokes: 11, example: "異常に 気がつく", hint: "田 と 共", example_reading: ["い"] },
    { kanji: "遺", readings: ["のこ(す)", "イ"], meaning: "のこす", strokes: 15, example: "遺跡を めぐる", hint: "しんにょう に 貴", example_reading: ["い"] },
    { kanji: "域", readings: ["イキ"], meaning: "ばしょ、はんい", strokes: 11, example: "地域を まもる", hint: "土へん に 或", example_reading: ["いき"] },
    { kanji: "宇", readings: ["ウ"], meaning: "おおきなやね、そら", strokes: 6, example: "宇宙へ いく", hint: "うかんむり に 于", example_reading: ["う"] },
    { kanji: "映", readings: ["うつ(る)", "エイ"], meaning: "うつる", strokes: 9, example: "映画を みる", hint: "日へん に 央", example_reading: ["えい"] },
    { kanji: "延", readings: ["の(びる)", "エン"], meaning: "のびる", strokes: 8, example: "試合を 延長する", hint: "えんにょう に 正", example_reading: ["えん"] },
    { kanji: "沿", readings: ["そ(う)", "エン"], meaning: "そう", strokes: 8, example: "沿岸を あるく", hint: "さんずい に 㕣", example_reading: ["えん"] },

    // --- か行 ---
    { kanji: "我", readings: ["われ", "ガ"], meaning: "わたし", strokes: 7, example: "我慢 できない", hint: "手 と 戈", example_reading: ["が"] },
    { kanji: "灰", readings: ["はい", "カイ"], meaning: "はい", strokes: 6, example: "灰色の くも", hint: "がんだれ に 火", example_reading: ["はい"] },
    { kanji: "拡", readings: ["カク"], meaning: "ひろげる", strokes: 8, example: "写真を 拡大する", hint: "てへん に 広", example_reading: ["かく"] },
    { kanji: "干", readings: ["ほ(す)", "カン"], meaning: "ほす", strokes: 3, example: "干し草を あつめる", hint: "二 と 縦棒", example_reading: ["ほ"] },
    { kanji: "株", readings: ["かぶ", "シュ"], meaning: "きのねっこ", strokes: 10, example: "株式会社を つくる", hint: "木へん に 朱", example_reading: ["かぶ"] },
    { kanji: "割", readings: ["わ(る)", "カツ"], meaning: "わる", strokes: 12, example: "値段が 割引される", hint: "害 と 刂", example_reading: ["わり"] },
    { kanji: "閣", readings: ["カク"], meaning: "りっぱなたてもの", strokes: 14, example: "内閣を つくる", hint: "門 に 各", example_reading: ["かく"] },
    { kanji: "革", readings: ["かわ", "カク"], meaning: "かわ", strokes: 9, example: "革靴を はく", hint: "廿 と 口 と 十", example_reading: ["かわ"] },
    { kanji: "巻", readings: ["ま(く)", "カン"], meaning: "まく", strokes: 9, example: "竜巻が おきる", hint: "龹 と 己", example_reading: ["まき"] },
    { kanji: "危", readings: ["あぶ(ない)", "キ"], meaning: "あぶない", strokes: 6, example: "危険な ばしょ", hint: "ク と 厄", example_reading: ["き"] },
    { kanji: "机", readings: ["つくえ", "キ"], meaning: "つくえ", strokes: 6, example: "学習机に すわる", hint: "木へん に 几", example_reading: ["づくえ"] },
    { kanji: "簡", readings: ["カン"], meaning: "ふだがみ、てまがかからない", strokes: 18, example: "簡単な もんだい", hint: "たけかんむり に 間", example_reading: ["かん"] },
    { kanji: "看", readings: ["カン"], meaning: "みまもる", strokes: 9, example: "看板を みる", hint: "手 のしたに 目", example_reading: ["かん"] },
    { kanji: "揮", readings: ["キ"], meaning: "ふるう", strokes: 12, example: "音楽を 指揮する", hint: "てへん に 軍", example_reading: ["き"] },
    { kanji: "貴", readings: ["とうと(い)", "キ"], meaning: "ねうちがある", strokes: 12, example: "貴重な たいけん", hint: "中 と 一 と 貝", example_reading: ["き"] },
    { kanji: "疑", readings: ["うたが(う)", "ギ"], meaning: "うたがう", strokes: 14, example: "疑問を もつ", hint: "ヒ と 矢 と マ と 疋", example_reading: ["ぎ"] },
    { kanji: "吸", readings: ["す(う)", "キュウ"], meaning: "すう", strokes: 6, example: "深呼吸を する", hint: "口へん に 及", example_reading: ["きゅう"] },
    { kanji: "供", readings: ["そな(える)", "キョウ"], meaning: "そなえる、おとも", strokes: 8, example: "子供が あそぶ", hint: "にんべん に 共", example_reading: ["ども"] },
    { kanji: "筋", readings: ["すじ", "キン"], meaning: "すじ", strokes: 12, example: "筋肉を きたえる", hint: "たけかんむり に 肋", example_reading: ["きん"] },
    { kanji: "勤", readings: ["つと(める)", "キン"], meaning: "しごとをする", strokes: 13, example: "電車で 通勤する", hint: "堇 と 力", example_reading: ["きん"] },
    { kanji: "郷", readings: ["ゴウ", "キョウ"], meaning: "ふるさと", strokes: 11, example: "故郷へ かえる", hint: "幺 と 白 と ヒ と こざとへん", example_reading: ["きょう"] },
    { kanji: "胸", readings: ["むね", "キョウ"], meaning: "むね", strokes: 10, example: "胸を はる", hint: "月へん に 匈", example_reading: ["むね"] },
    { kanji: "劇", readings: ["ゲキ"], meaning: "おしばい", strokes: 15, example: "演劇を みる", hint: "虍 と 豕 と 刂", example_reading: ["げき"] },
    { kanji: "系", readings: ["ケイ"], meaning: "つながり", strokes: 7, example: "太陽系の ほし", hint: "ノ と 糸", example_reading: ["けい"] },
    { kanji: "敬", readings: ["うやま(う)", "ケイ"], meaning: "うやまう", strokes: 12, example: "敬語で はなす", hint: "苟 と 攵", example_reading: ["けい"] },
    { kanji: "警", readings: ["ケイ"], meaning: "きをつける", strokes: 19, example: "警察を よぶ", hint: "敬 と 言", example_reading: ["けい"] },
    { kanji: "激", readings: ["はげ(しい)", "ゲキ"], meaning: "はげしい", strokes: 16, example: "映画に 感激する", hint: "さんずい に 敫", example_reading: ["げき"] },
    { kanji: "穴", readings: ["あな", "ケツ"], meaning: "あな", strokes: 5, example: "落とし穴に おちる", hint: "うかんむり に 八", example_reading: ["あな"] },
    { kanji: "絹", readings: ["きぬ", "ケン"], meaning: "きぬ", strokes: 13, example: "絹糸で ぬう", hint: "いとへん に 肙", example_reading: ["きぬ"] },
    { kanji: "権", readings: ["ケン"], meaning: "けんり", strokes: 15, example: "権利を まもる", hint: "木へん に 雚", example_reading: ["けん"] },
    { kanji: "憲", readings: ["ケン"], meaning: "きまり", strokes: 16, example: "憲法を まなぶ", hint: "うかんむり に 害 と 心", example_reading: ["けん"] },
    { kanji: "源", readings: ["みなもと", "ゲン"], meaning: "みなもと", strokes: 13, example: "資源を たいせつにする", hint: "さんずい に 原", example_reading: ["げん"] },
    { kanji: "厳", readings: ["きび(しい)", "ゲン"], meaning: "きびしい", strokes: 17, example: "厳しい さむさ", hint: "ツ と 厂 と 敢", example_reading: ["きび"] },
    { kanji: "己", readings: ["おのれ", "コ"], meaning: "じぶん", strokes: 3, example: "自己 しょうかい", hint: "コ と L", example_reading: ["こ"] },
    { kanji: "呼", readings: ["よ(ぶ)", "コ"], meaning: "よぶ、いきをはく", strokes: 8, example: "深く 呼吸する", hint: "口へん に 乎", example_reading: ["こ"] },
    { kanji: "誤", readings: ["あやま(る)", "ゴ"], meaning: "まちがえる", strokes: 14, example: "誤解を とく", hint: "ごんべん に 呉", example_reading: ["ご"] },
    { kanji: "后", readings: ["コウ"], meaning: "きさき", strokes: 6, example: "皇后 さま", hint: "厂 と 一 と 口", example_reading: ["ごう"] },
    { kanji: "孝", readings: ["コウ"], meaning: "おやをたいせつにする", strokes: 7, example: "親孝行を する", hint: "老 のしたに 子", example_reading: ["こう"] },
    { kanji: "皇", readings: ["コウ"], meaning: "きみ、おおきい", strokes: 9, example: "天皇 陛下", hint: "白 と 王", example_reading: ["のう"] },
    { kanji: "紅", readings: ["べに", "コウ"], meaning: "あか", strokes: 9, example: "紅白の はた", hint: "いとへん に 工", example_reading: ["こう"] },
    { kanji: "降", readings: ["お(りる)", "コウ"], meaning: "おりる、ふる", strokes: 10, example: "雨が 降る", hint: "こざとへん に 夅", example_reading: ["ふ"] },
    { kanji: "刻", readings: ["きざ(む)", "コク"], meaning: "きざむ、じかん", strokes: 8, example: "時刻を しらべる", hint: "亥 と 刂", example_reading: ["こく"] },
    { kanji: "鋼", readings: ["はがね", "コウ"], meaning: "はがね", strokes: 16, example: "鉄鋼を つくる", hint: "かねへん に 岡", example_reading: ["こう"] },

    // --- さ行 ---
    { kanji: "座", readings: ["すわ(る)", "ザ"], meaning: "すわるばしょ", strokes: 10, example: "座席に すわる", hint: "まだれ に 坐", example_reading: ["ざ"] },
    { kanji: "砂", readings: ["すな", "サ"], meaning: "すな", strokes: 9, example: "砂場で あそぶ", hint: "石へん に 少", example_reading: ["すな"] },
    { kanji: "困", readings: ["こま(る)", "コン"], meaning: "こまる", strokes: 7, example: "困難に たちむかう", hint: "くにがまえ に 木", example_reading: ["こん"] },
    { kanji: "骨", readings: ["ほね", "コツ"], meaning: "ほね", strokes: 10, example: "うでを 骨折する", hint: "冎 と 月", example_reading: ["こっ"] },
    { kanji: "穀", readings: ["コク"], meaning: "たべもののもと", strokes: 14, example: "穀物を そだてる", hint: "禾 と 几 と 殳", example_reading: ["こく"] },
    { kanji: "蚕", readings: ["かいこ", "サン"], meaning: "かいこ", strokes: 10, example: "蚕の糸を つむぐ", hint: "天 と 虫", example_reading: ["かいこ"] },
    { kanji: "冊", readings: ["サツ"], meaning: "ほんをかぞえる", strokes: 5, example: "本を 一冊かう", hint: "本がならんでいるかたち", example_reading: ["さつ"] },
    { kanji: "策", readings: ["サク"], meaning: "はかりごと", strokes: 12, example: "対策を たてる", hint: "たけかんむり に 刺 のひだり", example_reading: ["さく"] },
    { kanji: "裁", readings: ["さば(く)", "サイ"], meaning: "きる、さばく", strokes: 12, example: "裁判を おこす", hint: "十 と 戈 と 衣", example_reading: ["さい"] },
    { kanji: "済", readings: ["す(む)", "サイ"], meaning: "おわる", strokes: 11, example: "経済の ニュース", hint: "さんずい に 斉", example_reading: ["ざい"] },
    { kanji: "至", readings: ["いた(る)", "シ"], meaning: "いたる", strokes: 6, example: "夏至の ひ", hint: "一 と ム と 土", example_reading: ["し"] },
    { kanji: "私", readings: ["わたし", "シ"], meaning: "わたし", strokes: 7, example: "私服で でかける", hint: "のぎへん に ム", example_reading: ["し"] },
    { kanji: "姿", readings: ["すがた", "シ"], meaning: "すがた", strokes: 9, example: "姿勢を ただす", hint: "次 と 女", example_reading: ["し"] },
    { kanji: "視", readings: ["シ"], meaning: "みる", strokes: 11, example: "視力を はかる", hint: "示 と 見", example_reading: ["し"] },
    { kanji: "詞", readings: ["シ"], meaning: "ことば", strokes: 12, example: "歌を 作詞する", hint: "ごんべん に 司", example_reading: ["し"] },
    { kanji: "誌", readings: ["シ"], meaning: "かきとめる", strokes: 14, example: "雑誌を よむ", hint: "ごんべん に 志", example_reading: ["し"] },
    { kanji: "磁", readings: ["ジ"], meaning: "じしゃく", strokes: 14, example: "磁石が くっつく", hint: "石へん に 茲", example_reading: ["じ"] },
    { kanji: "射", readings: ["い(る)", "シャ"], meaning: "いる、うつ", strokes: 10, example: "注射を うつ", hint: "身 と 寸", example_reading: ["しゃ"] },
    { kanji: "捨", readings: ["す(てる)", "シャ"], meaning: "すてる", strokes: 11, example: "ゴミを 捨てる", hint: "てへん に 舎", example_reading: ["す"] },
    { kanji: "尺", readings: ["シャク"], meaning: "ながさのたんい", strokes: 4, example: "巻尺で はかる", hint: "尸 と ヽ", example_reading: ["じゃく"] },
    { kanji: "若", readings: ["わか(い)", "ジャク"], meaning: "わかい", strokes: 8, example: "元気な 若者", hint: "くさかんむり に 右", example_reading: ["わか"] },
    { kanji: "樹", readings: ["ジュ"], meaning: "き", strokes: 16, example: "樹木が そだつ", hint: "木へん と 豆 と 寸", example_reading: ["じゅ"] },
    { kanji: "収", readings: ["おさ(める)", "シュウ"], meaning: "おさめる", strokes: 4, example: "水分を 吸収する", hint: "りっしんべん みたいなの と 攵", example_reading: ["しゅう"] },
    { kanji: "宗", readings: ["シュウ"], meaning: "おおもと", strokes: 8, example: "宗教を まなぶ", hint: "うかんむり に 示", example_reading: ["しゅう"] },
    { kanji: "就", readings: ["つ(く)", "シュウ"], meaning: "つく", strokes: 12, example: "会社に 就職する", hint: "京 と 尤", example_reading: ["しゅう"] },
    { kanji: "衆", readings: ["シュウ"], meaning: "おおぜい", strokes: 12, example: "群衆の なか", hint: "血 と 衆 のした", example_reading: ["しゅう"] },
    { kanji: "従", readings: ["したが(う)", "ジュウ"], meaning: "したがう", strokes: 10, example: "ルールに 従う", hint: "ぎょうにんべん に 从 と 止", example_reading: ["したが"] },
    { kanji: "縦", readings: ["たて", "ジュウ"], meaning: "たて", strokes: 16, example: "縦書きの ノート", hint: "いとへん に 従", example_reading: ["たて"] },
    { kanji: "熟", readings: ["う(れる)", "ジュク"], meaning: "うれる、よくにる", strokes: 15, example: "四字 熟語", hint: "孰 と 灬", example_reading: ["じゅく"] },
    { kanji: "縮", readings: ["ちぢ(む)", "シュク"], meaning: "ちぢむ", strokes: 17, example: "時間を 短縮する", hint: "いとへん に 宿", example_reading: ["しゅく"] },
    { kanji: "署", readings: ["ショ"], meaning: "やくしょ", strokes: 13, example: "消防署の くるま", hint: "罒 と 者", example_reading: ["しょ"] },
    { kanji: "純", readings: ["ジュン"], meaning: "まじりけがない", strokes: 10, example: "純白の ドレス", hint: "いとへん に 屯", example_reading: ["じゅん"] },
    { kanji: "処", readings: ["ショ"], meaning: "おこなう、ところ", strokes: 5, example: "ゴミを 処理する", hint: "夂 と 几", example_reading: ["しょ"] },
    { kanji: "諸", readings: ["ショ"], meaning: "いろいろ", strokes: 15, example: "南の 諸島", hint: "ごんべん に 者", example_reading: ["しょ"] },
    { kanji: "除", readings: ["のぞ(く)", "ジョ"], meaning: "のぞく", strokes: 10, example: "部屋の 掃除", hint: "こざとへん に 余", example_reading: ["じ"] },
    { kanji: "針", readings: ["はり", "シン"], meaning: "はり", strokes: 10, example: "時計の 針がうごく", hint: "かねへん に 十", example_reading: ["はり"] },
    { kanji: "仁", readings: ["ジン"], meaning: "おもいやり", strokes: 4, example: "仁愛の こころ", hint: "にんべん に 二", example_reading: ["じん"] },
    { kanji: "蒸", readings: ["む(す)", "ジョウ"], meaning: "むす", strokes: 13, example: "水蒸気が でる", hint: "くさかんむり に 烝", example_reading: ["じょう"] },
    { kanji: "城", readings: ["しろ", "ジョウ"], meaning: "しろ", strokes: 9, example: "大きなお城", hint: "土へん に 成", example_reading: ["しろ"] },
    { kanji: "障", readings: ["さわ(る)", "ショウ"], meaning: "ふせぐ、さまたげ", strokes: 14, example: "機械が 故障する", hint: "こざとへん に 章", example_reading: ["しょう"] },
    { kanji: "将", readings: ["ショウ"], meaning: "ひきいる、これから", strokes: 10, example: "将来の ゆめ", hint: "爿 と ツ と 寸", example_reading: ["しょう"] },
    { kanji: "傷", readings: ["きず", "ショウ"], meaning: "きず", strokes: 13, example: "傷が なおる", hint: "にんべん に 𠂉 と 日 と 勹", example_reading: ["きず"] },
    { kanji: "垂", readings: ["た(れる)", "スイ"], meaning: "たれる", strokes: 8, example: "垂直に たてる", hint: "ノ と 土 と 廿", example_reading: ["すい"] },
    { kanji: "推", readings: ["スイ"], meaning: "おす", strokes: 11, example: "事件を 推理する", hint: "てへん に 隹", example_reading: ["すい"] },
    { kanji: "寸", readings: ["スン"], meaning: "みじかい、ながさ", strokes: 3, example: "寸法を はかる", hint: "十 に 点", example_reading: ["すん"] },
    { kanji: "専", readings: ["セン"], meaning: "もっぱら", strokes: 9, example: "専門の おみせ", hint: "十 と 恵 のうえ と 寸", example_reading: ["せん"] },
    { kanji: "宣", readings: ["セン"], meaning: "のべる", strokes: 9, example: "勝利を 宣言する", hint: "うかんむり に 亘", example_reading: ["せん"] },
    { kanji: "盛", readings: ["さか(ん)", "セイ"], meaning: "さかん", strokes: 11, example: "ごはんの 大盛り", hint: "成 と 皿", example_reading: ["も"] },
    { kanji: "聖", readings: ["セイ"], meaning: "きよい、りっぱ", strokes: 13, example: "神聖な ばしょ", hint: "耳 と 口 と 王", example_reading: ["せい"] },
    { kanji: "誠", readings: ["まこと", "セイ"], meaning: "まこと", strokes: 13, example: "誠実な たいど", hint: "ごんべん に 成", example_reading: ["せい"] },
    { kanji: "泉", readings: ["いずみ", "セン"], meaning: "いずみ", strokes: 9, example: "温泉に はいる", hint: "白 と 水", example_reading: ["せん"] },
    { kanji: "洗", readings: ["あら(う)", "セン"], meaning: "あらう", strokes: 9, example: "服を 洗濯する", hint: "さんずい に 先", example_reading: ["せん"] },
    { kanji: "染", readings: ["そ(める)", "セン"], meaning: "そめる", strokes: 9, example: "病気が 伝染する", hint: "さんずい に 九 と 木", example_reading: ["せん"] },
    { kanji: "善", readings: ["よ(い)", "ゼン"], meaning: "よい", strokes: 12, example: "親善 試合", hint: "羊 と ツ と 口", example_reading: ["ぜん"] },
    { kanji: "奏", readings: ["かな(でる)", "ソウ"], meaning: "かなでる", strokes: 9, example: "ピアノを 演奏する", hint: "三 と 人 と 天", example_reading: ["そう"] },
    { kanji: "窓", readings: ["まど", "ソウ"], meaning: "まど", strokes: 11, example: "窓ガラスを ふく", hint: "あなかんむり に ム と 心", example_reading: ["まど"] },
    { kanji: "創", readings: ["ソウ"], meaning: "はじめる、つくる", strokes: 12, example: "新しいものを 創造する", hint: "倉 と 刂", example_reading: ["そう"] },
    { kanji: "装", readings: ["よそお(う)", "ソウ"], meaning: "かざる、きるもの", strokes: 12, example: "服装を ととのえる", hint: "壮 と 衣", example_reading: ["そう"] },
    { kanji: "層", readings: ["ソウ"], meaning: "かさなる", strokes: 14, example: "地層を しらべる", hint: "しかばね に 曽", example_reading: ["そう"] },
    { kanji: "操", readings: ["あやつ(る)", "ソウ"], meaning: "あやつる", strokes: 16, example: "体操を する", hint: "てへん に 品 と 木", example_reading: ["そう"] },
    { kanji: "蔵", readings: ["くら", "ゾウ"], meaning: "くら、しまう", strokes: 15, example: "冷蔵庫を あける", hint: "くさかんむり に 厂 と 臣 と 戈", example_reading: ["ぞう"] },
    { kanji: "臓", readings: ["ゾウ"], meaning: "からだのなかの つくり", strokes: 19, example: "心臓が 動く", hint: "月へん に 蔵", example_reading: ["ぞう"] },
    { kanji: "存", readings: ["ソン"], meaning: "ある、いる", strokes: 6, example: "データを 保存する", hint: "ナ と ノ と 子", example_reading: ["ぞん"] },
    { kanji: "尊", readings: ["とうと(い)", "ソン"], meaning: "とうとい、たっとい", strokes: 12, example: "先生を 尊敬する", hint: "八 と 酉 と 寸", example_reading: ["そん"] },

    // --- た行 ---
    { kanji: "宅", readings: ["タク"], meaning: "いえ", strokes: 6, example: "自宅に かえる", hint: "うかんむり に 乇", example_reading: ["たく"] },
    { kanji: "担", readings: ["にな(う)", "タン"], meaning: "になう、うけもつ", strokes: 8, example: "担任の 先生", hint: "てへん に 旦", example_reading: ["たん"] },
    { kanji: "探", readings: ["さが(す)", "タン"], meaning: "さがす", strokes: 11, example: "森を 探検する", hint: "てへん に 穴 と 木", example_reading: ["たん"] },
    { kanji: "誕", readings: ["タン"], meaning: "うまれる", strokes: 15, example: "誕生日を いわう", hint: "ごんべん に 延", example_reading: ["たん"] },
    { kanji: "段", readings: ["ダン"], meaning: "きざみ", strokes: 9, example: "階段を のぼる", hint: "ノ と Ｌ と 殳", example_reading: ["だん"] },
    { kanji: "暖", readings: ["あたた(かい)", "ダン"], meaning: "あたたかい", strokes: 13, example: "暖房を つける", hint: "日へん に 爰", example_reading: ["だん"] },
    { kanji: "値", readings: ["ね", "チ"], meaning: "ねだん", strokes: 10, example: "値段が たかい", hint: "にんべん に 直", example_reading: ["ね"] },
    { kanji: "宙", readings: ["チュウ"], meaning: "そら", strokes: 8, example: "宇宙へ いきたい", hint: "うかんむり に 由", example_reading: ["ちゅう"] },
    { kanji: "忠", readings: ["チュウ"], meaning: "まごころ", strokes: 8, example: "忠実な いぬ", hint: "中 と 心", example_reading: ["ちゅう"] },
    { kanji: "著", readings: ["あらわ(す)", "チョ"], meaning: "あらわす、いちじるしい", strokes: 11, example: "本の 著者", hint: "くさかんむり に 者", example_reading: ["ちょ"] },
    { kanji: "庁", readings: ["チョウ"], meaning: "やくしょ", strokes: 5, example: "県庁に いく", hint: "まだれ に 丁", example_reading: ["ちょう"] },
    { kanji: "頂", readings: ["いただ(く)", "チョウ"], meaning: "いただく、てっぺん", strokes: 11, example: "山の 頂上", hint: "丁 と 頁", example_reading: ["ちょう"] },
    { kanji: "潮", readings: ["しお", "チョウ"], meaning: "しお", strokes: 15, example: "満潮の うみ", hint: "さんずい に 朝", example_reading: ["ちょう"] },
    { kanji: "賃", readings: ["チン"], meaning: "かりるおかね", strokes: 13, example: "家賃を はらう", hint: "任 と 貝", example_reading: ["ちん"] },
    { kanji: "痛", readings: ["いた(い)", "ツウ"], meaning: "いたい", strokes: 12, example: "頭痛が する", hint: "やまいだれ に マ と 用", example_reading: ["つう"] },
    { kanji: "展", readings: ["テン"], meaning: "ひろげる", strokes: 10, example: "作品を 展示する", hint: "しかばね に 廿 と 衣 みたい", example_reading: ["てん"] },
    { kanji: "討", readings: ["う(つ)", "トウ"], meaning: "うつ", strokes: 10, example: "みんなで 討論する", hint: "ごんべん に 寸", example_reading: ["とう"] },
    { kanji: "党", readings: ["トウ"], meaning: "なかま", strokes: 10, example: "政党の なまえ", hint: "尚 と 兄", example_reading: ["とう"] },
    { kanji: "糖", readings: ["トウ"], meaning: "さとう", strokes: 16, example: "砂糖を いれる", hint: "米へん に 唐", example_reading: ["とう"] },
    { kanji: "届", readings: ["とど(く)", "トド"], meaning: "とどく", strokes: 8, example: "荷物が 届く", hint: "しかばね に 由", example_reading: ["とど"] },

    // --- な行 ---
    { kanji: "難", readings: ["むずか(しい)", "ナン"], meaning: "むずかしい", strokes: 18, example: "困難を のりこえる", hint: "廿 と 口 と 夫 と 隹", example_reading: ["なん"] },
    { kanji: "乳", readings: ["ちち", "ニュウ"], meaning: "ちち", strokes: 8, example: "牛乳を のむ", hint: "孚 と 乚", example_reading: ["にゅう"] },
    { kanji: "認", readings: ["みと(める)", "ニン"], meaning: "みとめる", strokes: 14, example: "安全を 確認する", hint: "ごんべん に 忍", example_reading: ["にん"] },
    { kanji: "納", readings: ["おさ(める)", "ノウ"], meaning: "おさめる", strokes: 10, example: "説明に 納得する", hint: "いとへん に 内", example_reading: ["なっ"] },
    { kanji: "脳", readings: ["ノウ"], meaning: "のうみそ", strokes: 11, example: "優れた 頭脳", hint: "月へん に ツ と 凶", example_reading: ["のう"] },

    // --- は行 ---
    { kanji: "派", readings: ["ハ"], meaning: "わかれる、わかれ", strokes: 9, example: "立派な たてもの", hint: "さんずい に 𠂢", example_reading: ["ぱ"] },
    { kanji: "拝", readings: ["おが(む)", "ハイ"], meaning: "おがむ", strokes: 8, example: "礼拝を する", hint: "てへん に 丰 と 一", example_reading: ["はい"] },
    { kanji: "背", readings: ["せ", "ハイ"], meaning: "せなか", strokes: 9, example: "背中を おす", hint: "北 と 月", example_reading: ["せ"] },
    { kanji: "肺", readings: ["ハイ"], meaning: "はい", strokes: 9, example: "肺活量を はかる", hint: "月へん に 市", example_reading: ["はい"] },
    { kanji: "俳", readings: ["ハイ"], meaning: "わざおぎ", strokes: 10, example: "有名な 俳優", hint: "にんべん に 非", example_reading: ["はい"] },
    { kanji: "班", readings: ["ハン"], meaning: "わける、グループ", strokes: 10, example: "班長に なる", hint: "王 と 刂 と 王", example_reading: ["はん"] },
    { kanji: "晩", readings: ["バン"], meaning: "よる", strokes: 12, example: "今晩の おかず", hint: "日へん に 免", example_reading: ["ばん"] },
    { kanji: "否", readings: ["いな", "ヒ"], meaning: "ちがう", strokes: 7, example: "意見を 否定する", hint: "不 と 口", example_reading: ["ひ"] },
    { kanji: "批", readings: ["ヒ"], meaning: "うつ", strokes: 7, example: "批判を うける", hint: "てへん に 比", example_reading: ["ひ"] },
    { kanji: "秘", readings: ["ひめ(る)", "ヒ"], meaning: "ひめる、かくす", strokes: 10, example: "秘密の ばしょ", hint: "のぎへん に 必", example_reading: ["ひ"] },
    { kanji: "腹", readings: ["はら", "フク"], meaning: "おなか", strokes: 13, example: "腹痛で 休む", hint: "月へん に 復 の右", example_reading: ["ふく"] },
    { kanji: "陛", readings: ["ヘイ"], meaning: "きざはし", strokes: 10, example: "天皇陛下に おあいする", hint: "こざとへん に 比 と 土", example_reading: ["へい"] },
    { kanji: "奮", readings: ["ふる(う)", "フン"], meaning: "ふるう", strokes: 16, example: "興奮して さけぶ", hint: "大 と 隹 と 田", example_reading: ["ふん"] },
    { kanji: "並", readings: ["なら(ぶ)", "ヘイ"], meaning: "ならぶ", strokes: 8, example: "並んで 歩く", hint: "ツ と 一 と 业", example_reading: ["なら"] },
    { kanji: "閉", readings: ["し(める)", "ヘイ"], meaning: "しめる", strokes: 11, example: "ドアを 閉める", hint: "門 に 才", example_reading: ["し"] },
    { kanji: "片", readings: ["かた", "ヘン"], meaning: "かたほう", strokes: 4, example: "片道の きっぷ", hint: "木 を半分にしたかたち", example_reading: ["かた"] },
    { kanji: "補", readings: ["おぎな(う)", "ホ"], meaning: "おぎなう", strokes: 12, example: "補助輪を はずす", hint: "ころもへん に 甫", example_reading: ["ほ"] },
    { kanji: "暮", readings: ["く(らす)", "ボ"], meaning: "くらす、ひぐれ", strokes: 14, example: "夕暮れの そら", hint: "くさかんむり に 日 と 大 と 日", example_reading: ["ぐ"] },
    { kanji: "宝", readings: ["たから", "ホウ"], meaning: "たから", strokes: 8, example: "宝物を さがす", hint: "うかんむり に 玉", example_reading: ["たから"] },
    { kanji: "訪", readings: ["おとず(れる)", "ホウ"], meaning: "たずねる", strokes: 11, example: "会社を 訪問する", hint: "ごんべん に 方", example_reading: ["ほう"] },

    // --- ま行 ---
    { kanji: "亡", readings: ["な(くなる)", "ボウ"], meaning: "なくなる", strokes: 3, example: "人が 亡くなる", hint: "亠 と L", example_reading: ["な"] },
    { kanji: "忘", readings: ["わす(れる)", "ボウ"], meaning: "わすれる", strokes: 7, example: "忘れ物を さがす", hint: "亡 と 心", example_reading: ["わす"] },
    { kanji: "棒", readings: ["ボウ"], meaning: "ぼう", strokes: 12, example: "鉄棒で あそぶ", hint: "木へん に 奉", example_reading: ["ぼう"] },
    { kanji: "枚", readings: ["マイ"], meaning: "まい", strokes: 8, example: "紙を 一枚とる", hint: "木へん に 攵", example_reading: ["まい"] },
    { kanji: "密", readings: ["ミツ"], meaning: "こまかい、ひそか", strokes: 11, example: "秘密を まもる", hint: "うかんむり に 必 と 山", example_reading: ["みつ"] },
    { kanji: "幕", readings: ["マク"], meaning: "まく", strokes: 13, example: "試合が 開幕する", hint: "莫 のしたに 巾", example_reading: ["まく"] },
    { kanji: "盟", readings: ["メイ"], meaning: "ちかう", strokes: 13, example: "同盟を むすぶ", hint: "明 と 皿", example_reading: ["めい"] },
    { kanji: "模", readings: ["モ"], meaning: "かたどる", strokes: 14, example: "花の 模様", hint: "木へん に 莫", example_reading: ["も"] },

    // --- や行 ---
    { kanji: "訳", readings: ["わけ", "ヤク"], meaning: "わけ、いいかえる", strokes: 11, example: "英語を 通訳する", hint: "ごんべん に 尺", example_reading: ["やく"] },
    { kanji: "郵", readings: ["ユウ"], meaning: "しゅくば", strokes: 11, example: "郵便を だす", hint: "垂 と こざとへん", example_reading: ["ゆう"] },
    { kanji: "優", readings: ["やさ(しい)", "ユウ"], meaning: "やさしい、すぐれる", strokes: 17, example: "大会で 優勝する", hint: "にんべん に 憂", example_reading: ["ゆう"] },
    { kanji: "幼", readings: ["おさな(い)", "ヨウ"], meaning: "おさない", strokes: 5, example: "幼児が あそぶ", hint: "幺 と 力", example_reading: ["よう"] },
    { kanji: "欲", readings: ["ほ(しい)", "ヨク"], meaning: "ほしい", strokes: 11, example: "食欲が ある", hint: "谷 と 欠", example_reading: ["よく"] },
    { kanji: "翌", readings: ["ヨク"], meaning: "つぎの", strokes: 11, example: "翌日に 出発する", hint: "羽 と 立", example_reading: ["よく"] },

    // --- ら・わ行 ---
    { kanji: "乱", readings: ["みだ(れる)", "ラン"], meaning: "みだれる", strokes: 7, example: "頭が 混乱する", hint: "舌 と L", example_reading: ["らん"] },
    { kanji: "卵", readings: ["たまご", "ラン"], meaning: "たまご", strokes: 7, example: "卵焼きを つくる", hint: "卯 のなかに 点々", example_reading: ["たまご"] },
    { kanji: "覧", readings: ["ラン"], meaning: "みる", strokes: 17, example: "展覧会に いく", hint: "臣 と ひとやね と 見", example_reading: ["らん"] },
    { kanji: "裏", readings: ["うら", "リ"], meaning: "うら", strokes: 13, example: "裏口から はいる", hint: "亠 と 里 と 衣のした", example_reading: ["うら"] },
    { kanji: "律", readings: ["リツ"], meaning: "きまり", strokes: 9, example: "法律を まもる", hint: "ぎょうにんべん に 聿", example_reading: ["りつ"] },
    { kanji: "臨", readings: ["のぞ(む)", "リン"], meaning: "のぞむ", strokes: 18, example: "臨時の ニュース", hint: "臣 と ひとやね と 品", example_reading: ["りん"] },
    { kanji: "朗", readings: ["ほが(らか)", "ロウ"], meaning: "ほがらか", strokes: 10, example: "本を 朗読する", hint: "良 と 月", example_reading: ["ろう"] },
    { kanji: "論", readings: ["ロン"], meaning: "はなしあう", strokes: 15, example: "みんなで 議論する", hint: "ごんべん に 侖", example_reading: ["ろん"] }
];