// kanji/grade4.js - 4年生の漢字データ（完全版：200字）
// 各漢字: kanji, readings(読み方), meaning(意味), strokes(画数), example(例文), hint(覚え方ヒント), example_reading(例文での読み方)

const GRADE4_KANJI = [
    // --- あ行 ---
    { kanji: "愛", readings: ["アイ"], meaning: "かわいがる", strokes: 13, example: "愛情 をそそぐ", hint: "心 をまんなかに うける", example_reading: ["あい"] },
    { kanji: "案", readings: ["アン"], meaning: "かんがえ", strokes: 10, example: "名案 をおもいつく", hint: "安 と 木", example_reading: ["あん"] },
    { kanji: "以", readings: ["イ"], meaning: "〜より", strokes: 5, example: "これ 以上 はむり", hint: "レ と ト と 人 みたい", example_reading: ["い"] },
    { kanji: "衣", readings: ["ころも", "イ"], meaning: "きるもの", strokes: 6, example: "衣服 をととのえる", hint: "なべぶた に ひとやね と レ", example_reading: ["い"] },
    { kanji: "位", readings: ["くらい", "イ"], meaning: "じゅんばん、ばしょ", strokes: 7, example: "第一位 になる", hint: "にんべん に 立", example_reading: ["い"] },
    { kanji: "囲", readings: ["かこ(む)", "イ"], meaning: "まわりをかこむ", strokes: 7, example: "周りを 囲む", hint: "くにがまえ に 井", example_reading: ["かこ"] },
    { kanji: "胃", readings: ["イ"], meaning: "たべものを しょうかするところ", strokes: 9, example: "胃腸 がよわい", hint: "田 のしたに 月", example_reading: ["い"] },
    { kanji: "印", readings: ["しるし", "イン"], meaning: "しるし、ハンコ", strokes: 6, example: "目印 をつける", hint: "E と 卩 みたい", example_reading: ["じるし"] },
    { kanji: "英", readings: ["エイ"], meaning: "すぐれている、イギリス", strokes: 8, example: "英語 をはなす", hint: "くさかんむり に 央", example_reading: ["えい"] },
    { kanji: "栄", readings: ["さか(える)", "エイ"], meaning: "さかえる", strokes: 9, example: "栄養 をとる", hint: "ツ と ワ と 木", example_reading: ["えい"] },
    { kanji: "塩", readings: ["しお", "エン"], meaning: "しょっぱい ちょうみりょう", strokes: 13, example: "塩 をふりかける", hint: "土 と 人 と 口 と 皿", example_reading: ["しお"] },
    { kanji: "億", readings: ["オク"], meaning: "万のつぎの おおきなかず", strokes: 15, example: "一億 円", hint: "にんべん に 意", example_reading: ["おく"] },

    // --- か行 ---
    { kanji: "加", readings: ["くわ(える)", "カ"], meaning: "たす、ふえる", strokes: 5, example: "力を 加える", hint: "力 と 口", example_reading: ["くわ"] },
    { kanji: "果", readings: ["は(たす)", "カ"], meaning: "くだもの、おわり", strokes: 8, example: "果物 をたべる", hint: "田 のしたに 木", example_reading: ["くだ"] },
    { kanji: "貨", readings: ["カ"], meaning: "おかね、にもつ", strokes: 11, example: "貨物 列車", hint: "化 と 貝", example_reading: ["か"] },
    { kanji: "課", readings: ["カ"], meaning: "わりあてられた しごと", strokes: 15, example: "放課 後にあそぶ", hint: "ごんべん に 果", example_reading: ["か"] },
    { kanji: "芽", readings: ["め", "ガ"], meaning: "しょくぶつの め", strokes: 8, example: "芽 がでる", hint: "くさかんむり に 牙", example_reading: ["め"] },
    { kanji: "改", readings: ["あらた(める)", "カイ"], meaning: "あたらしくする", strokes: 7, example: "心を 改める", hint: "己 と 攵", example_reading: ["あらた"] },
    { kanji: "械", readings: ["カイ"], meaning: "しかけ、どうぐ", strokes: 11, example: "機械 をうごかす", hint: "木へん に 戒", example_reading: ["かい"] },
    { kanji: "害", readings: ["ガイ"], meaning: "きずつける、わるいこと", strokes: 10, example: "公害 をなくす", hint: "うかんむり と 丰 と 口", example_reading: ["がい"] },
    { kanji: "街", readings: ["まち", "ガイ"], meaning: "にぎやかな まち", strokes: 12, example: "商店 街", hint: "行 のまんなかに 圭", example_reading: ["がい"] },
    { kanji: "各", readings: ["おのおの", "カク"], meaning: "それぞれ", strokes: 6, example: "各自 でよういする", hint: "夂 と 口", example_reading: ["かく"] },
    { kanji: "覚", readings: ["おぼ(える)", "カク"], meaning: "おぼえる、めざめる", strokes: 12, example: "漢字を 覚える", hint: "ツ と ワ と 見", example_reading: ["おぼ"] },
    { kanji: "完", readings: ["カン"], meaning: "おわる、すべてそろう", strokes: 7, example: "完成 する", hint: "うかんむり に 元", example_reading: ["かん"] },
    { kanji: "官", readings: ["カン"], meaning: "やくしょ、やくにん", strokes: 8, example: "警察 官", hint: "うかんむり に 𠂤", example_reading: ["かん"] },
    { kanji: "管", readings: ["くだ", "カン"], meaning: "つつ", strokes: 14, example: "水道 管", hint: "たけかんむり に 官", example_reading: ["かん"] },
    { kanji: "関", readings: ["せき", "カン"], meaning: "かかわる", strokes: 14, example: "関係 がある", hint: "門 のなかに 关", example_reading: ["かん"] },
    { kanji: "観", readings: ["み(る)", "カン"], meaning: "よくみる", strokes: 18, example: "観察 する", hint: "雚 と 見", example_reading: ["かん"] },
    { kanji: "願", readings: ["ねが(う)", "ガン"], meaning: "ねがう", strokes: 19, example: "お願い する", hint: "原 と 頁", example_reading: ["ねが"] },
    { kanji: "希", readings: ["キ"], meaning: "ねがう、めずらしい", strokes: 7, example: "希望 をもつ", hint: "メ と 布", example_reading: ["き"] },
    { kanji: "季", readings: ["キ"], meaning: "きせつ", strokes: 8, example: "季節 がかわる", hint: "禾 と 子", example_reading: ["き"] },
    { kanji: "紀", readings: ["キ"], meaning: "すじみち、とし", strokes: 9, example: "世紀", hint: "いとへん に 己", example_reading: ["き"] },
    { kanji: "喜", readings: ["よろこ(ぶ)", "キ"], meaning: "うれしくおもう", strokes: 12, example: "喜んで てつだう", hint: "士 と 口 と 䒑 と 口", example_reading: ["よろこ"] },
    { kanji: "旗", readings: ["はた", "キ"], meaning: "はた", strokes: 14, example: "国旗 をあげる", hint: "方 と ひとやね と 其", example_reading: ["き"] },
    { kanji: "器", readings: ["うつわ", "キ"], meaning: "いれもの、どうぐ", strokes: 15, example: "楽器 をえんそうする", hint: "口 が４つと 犬", example_reading: ["き"] },
    { kanji: "機", readings: ["はた", "キ"], meaning: "しかけ、タイミング", strokes: 16, example: "飛行 機", hint: "木へん と 幾", example_reading: ["き"] },
    { kanji: "議", readings: ["ギ"], meaning: "はなしあう", strokes: 20, example: "会議 をひらく", hint: "ごんべん に 義", example_reading: ["ぎ"] },
    { kanji: "求", readings: ["もと(める)", "キュウ"], meaning: "もとめる", strokes: 7, example: "助けを 求める", hint: "水 にてん と ノ", example_reading: ["もと"] },
    { kanji: "泣", readings: ["な(く)", "キュウ"], meaning: "なく", strokes: 8, example: "大声で 泣く", hint: "さんずい に 立", example_reading: ["な"] },
    { kanji: "救", readings: ["すく(う)", "キュウ"], meaning: "たすける", strokes: 11, example: "命を 救う", hint: "求 と 攵", example_reading: ["すく"] },
    { kanji: "給", readings: ["キュウ"], meaning: "あたえる", strokes: 12, example: "給食 をたべる", hint: "いとへん に 合", example_reading: ["きゅう"] },
    { kanji: "挙", readings: ["あ(げる)", "キョ"], meaning: "あげる", strokes: 10, example: "手を 挙げる", hint: "ツ と 与 と 手", example_reading: ["あ"] },
    { kanji: "漁", readings: ["ギョ", "リョウ"], meaning: "さかなをとる", strokes: 14, example: "漁業 をいとなむ", hint: "さんずい に 魚", example_reading: ["ぎょ"] },
    { kanji: "共", readings: ["とも", "キョウ"], meaning: "いっしょに", strokes: 6, example: "共に あゆむ", hint: "廿 と ハ", example_reading: ["とも"] },
    { kanji: "協", readings: ["キョウ"], meaning: "ちからをあわせる", strokes: 8, example: "協力 する", hint: "十 と 力 が３つ", example_reading: ["きょう"] },
    { kanji: "鏡", readings: ["かがみ", "キョウ"], meaning: "かがみ", strokes: 19, example: "鏡 をみる", hint: "かねへん に 竟", example_reading: ["かがみ"] },
    { kanji: "競", readings: ["きそ(う)", "キョウ"], meaning: "きそう", strokes: 20, example: "かけっこで 競う", hint: "立 と 兄 が２つ", example_reading: ["きそ"] },
    { kanji: "極", readings: ["きわ(める)", "キョク"], meaning: "はて、いちばんさき", strokes: 12, example: "北極 にいく", hint: "木へん に 亟", example_reading: ["きょく"] },
    { kanji: "訓", readings: ["クン"], meaning: "おしえ", strokes: 10, example: "訓読み", hint: "ごんべん に 川", example_reading: ["くん"] },
    { kanji: "軍", readings: ["グン"], meaning: "いくさのなかま", strokes: 9, example: "軍手 をはめる", hint: "ワかんむり に 車", example_reading: ["ぐん"] },
    { kanji: "郡", readings: ["グン"], meaning: "まちのくぎり", strokes: 10, example: "〇〇 郡", hint: "君 と こざとへん", example_reading: ["ぐん"] },
    { kanji: "径", readings: ["ケイ"], meaning: "みち、さしわたし", strokes: 8, example: "直径 をはかる", hint: "ぎょうにんべん に 圣", example_reading: ["けい"] },
    { kanji: "型", readings: ["かた", "ケイ"], meaning: "かたち", strokes: 9, example: "大型 トラック", hint: "刑 と 土", example_reading: ["がた"] },
    { kanji: "景", readings: ["ケイ"], meaning: "けしき", strokes: 12, example: "景色 がきれい", hint: "日 のしたに 京", example_reading: ["けし"] },
    { kanji: "芸", readings: ["ゲイ"], meaning: "わざ", strokes: 7, example: "手品を 芸 にする", hint: "くさかんむり に 云", example_reading: ["げい"] },
    { kanji: "欠", readings: ["か(ける)", "ケツ"], meaning: "たりない", strokes: 4, example: "授業を 欠席 する", hint: "ク と 人 みたい", example_reading: ["けっ"] },
    { kanji: "結", readings: ["むす(ぶ)", "ケツ"], meaning: "むすぶ", strokes: 12, example: "ひもを 結ぶ", hint: "いとへん に 吉", example_reading: ["むす"] },
    { kanji: "建", readings: ["た(てる)", "ケン"], meaning: "たてる", strokes: 9, example: "家を 建てる", hint: "えんにょう に 聿", example_reading: ["た"] },
    { kanji: "健", readings: ["すこ(やか)", "ケン"], meaning: "からだがじょうぶ", strokes: 11, example: "健康 にきをつける", hint: "にんべん に 建", example_reading: ["けん"] },
    { kanji: "験", readings: ["ケン"], meaning: "ためす", strokes: 18, example: "実験 をする", hint: "馬へん に 僉", example_reading: ["けん"] },
    { kanji: "固", readings: ["かた(い)", "コ"], meaning: "かたい", strokes: 8, example: "固い 石", hint: "くにがまえ に 古", example_reading: ["かた"] },
    { kanji: "功", readings: ["コウ"], meaning: "てがら", strokes: 5, example: "大 成功", hint: "工 と 力", example_reading: ["こう"] },
    { kanji: "好", readings: ["この(む)", "コウ"], meaning: "すき", strokes: 6, example: "好きな たべもの", hint: "女へん に 子", example_reading: ["す"] },
    { kanji: "候", readings: ["コウ"], meaning: "きせつ、うかがう", strokes: 10, example: "気候 がいい", hint: "にんべん に 矦", example_reading: ["こう"] },
    { kanji: "航", readings: ["コウ"], meaning: "ふねやひこうきで すすむ", strokes: 10, example: "航空 機", hint: "舟へん に 亢", example_reading: ["こう"] },
    { kanji: "康", readings: ["コウ"], meaning: "じょうぶ、やすらか", strokes: 11, example: "健康 だ", hint: "まだれ に 隶", example_reading: ["こう"] },
    { kanji: "告", readings: ["つ(げる)", "コク"], meaning: "しらせる", strokes: 7, example: "広告 をみる", hint: "牛 のしたに 口", example_reading: ["こく"] },

    // --- さ行 ---
    { kanji: "差", readings: ["さ(す)", "サ"], meaning: "ちがい、さす", strokes: 10, example: "傘を 差す", hint: "羊 と 工", example_reading: ["さ"] },
    { kanji: "菜", readings: ["な", "サイ"], meaning: "おかず、やさい", strokes: 11, example: "野菜 をたべる", hint: "くさかんむり に 采", example_reading: ["さい"] },
    { kanji: "最", readings: ["もっと(も)", "サイ"], meaning: "いちばん", strokes: 12, example: "最高 にたのしい", hint: "日 と 取", example_reading: ["さい"] },
    { kanji: "材", readings: ["ザイ"], meaning: "ざいりょう", strokes: 7, example: "材料 をあつめる", hint: "木へん に 才", example_reading: ["ざい"] },
    { kanji: "昨", readings: ["サク"], meaning: "きのう、まえのとし", strokes: 9, example: "昨日 のこと", hint: "日へん に 乍", example_reading: ["きのう"] },
    { kanji: "札", readings: ["ふだ", "サツ"], meaning: "かみきれ", strokes: 5, example: "千円 札", hint: "木へん に L", example_reading: ["さつ"] },
    { kanji: "刷", readings: ["す(る)", "サツ"], meaning: "こする、印刷する", strokes: 8, example: "ポスターを 印刷 する", hint: "尸 と 巾 と 刂", example_reading: ["さつ"] },
    { kanji: "殺", readings: ["ころ(す)", "サツ"], meaning: "いのちをたつ", strokes: 10, example: "必殺 わざ", hint: "メ と 木 と 殳", example_reading: ["さつ"] },
    { kanji: "察", readings: ["サツ"], meaning: "よくみる、おしはかる", strokes: 14, example: "警察 にいく", hint: "うかんむり に 祭", example_reading: ["さつ"] },
    { kanji: "参", readings: ["まい(る)", "サン"], meaning: "いく、くわわる", strokes: 8, example: "参加 する", hint: "ム と 大 と 彡", example_reading: ["さん"] },
    { kanji: "産", readings: ["う(む)", "サン"], meaning: "うみだす", strokes: 11, example: "お米を 生産 する", hint: "文 と 厂 と 生", example_reading: ["さん"] },
    { kanji: "散", readings: ["ち(る)", "サン"], meaning: "ばらばらになる", strokes: 12, example: "散歩 する", hint: "林 みたいだけど少し違う と 攵", example_reading: ["さん"] },
    { kanji: "残", readings: ["のこ(る)", "ザン"], meaning: "のこる", strokes: 10, example: "ご飯が 残る", hint: "歹 と 戔", example_reading: ["のこ"] },
    { kanji: "士", readings: ["シ"], meaning: "おとこ、りっぱなひと", strokes: 3, example: "武士", hint: "十 のしたに 長いよこぼう", example_reading: ["し"] },
    { kanji: "氏", readings: ["うじ", "シ"], meaning: "みょうじ", strokes: 4, example: "彼氏", hint: "ノ と Ｌ と 一", example_reading: ["し"] },
    { kanji: "史", readings: ["シ"], meaning: "むかしのきろく", strokes: 5, example: "歴史 をまなぶ", hint: "口 のしたに メ みたい", example_reading: ["し"] },
    { kanji: "司", readings: ["シ"], meaning: "やくめ、つかさどる", strokes: 5, example: "司会 をする", hint: "司会 の し", example_reading: ["し"] },
    { kanji: "試", readings: ["ため(す)", "シ"], meaning: "ためす", strokes: 13, example: "試合 にでる", hint: "ごんべん に 式", example_reading: ["し"] },
    { kanji: "児", readings: ["ジ"], meaning: "こども", strokes: 7, example: "児童 会館", hint: "旧 と 儿", example_reading: ["じ"] },
    { kanji: "治", readings: ["おさ(める)", "ジ"], meaning: "なおす、おさめる", strokes: 8, example: "虫歯を 治す", hint: "さんずい に 台", example_reading: ["なお"] },
    { kanji: "辞", readings: ["や(める)", "ジ"], meaning: "ことば、やめる", strokes: 13, example: "辞典 をひく", hint: "舌 と 辛", example_reading: ["じ"] },
    { kanji: "失", readings: ["うしな(う)", "シツ"], meaning: "なくす、まちがえる", strokes: 5, example: "失敗 する", hint: "ノ と 夫", example_reading: ["しっ"] },
    { kanji: "借", readings: ["か(りる)", "シャク"], meaning: "かりる", strokes: 10, example: "本を 借りる", hint: "にんべん に 昔", example_reading: ["か"] },
    { kanji: "種", readings: ["たね", "シュ"], meaning: "たね、しゅるい", strokes: 14, example: "花の 種", hint: "のぎへん に 重", example_reading: ["たね"] },
    { kanji: "周", readings: ["まわ(り)", "シュウ"], meaning: "まわり", strokes: 8, example: "周り をみる", hint: "冂 と 吉", example_reading: ["まわ"] },
    { kanji: "祝", readings: ["いわ(う)", "シュク"], meaning: "お祝いする", strokes: 9, example: "誕生日を 祝う", hint: "しめすへん に 兄", example_reading: ["いわ"] },
    { kanji: "順", readings: ["ジュン"], meaning: "したがう、じゅんばん", strokes: 12, example: "順番 をまもる", hint: "川 と 頁", example_reading: ["じゅん"] },
    { kanji: "初", readings: ["はじ(め)", "ショ"], meaning: "はじめ", strokes: 7, example: "初めて のおつかい", hint: "ころもへん に 刀", example_reading: ["はじ"] },
    { kanji: "松", readings: ["まつ", "ショウ"], meaning: "まつのき", strokes: 8, example: "松の木", hint: "木へん に 公", example_reading: ["まつ"] },
    { kanji: "笑", readings: ["わら(う)", "ショウ"], meaning: "わらう", strokes: 10, example: "大声で 笑う", hint: "たけかんむり に 夭", example_reading: ["わら"] },
    { kanji: "唱", readings: ["とな(える)", "ショウ"], meaning: "こえにだす", strokes: 11, example: "合唱 する", hint: "口 と 昌", example_reading: ["しょう"] },
    { kanji: "象", readings: ["ゾウ"], meaning: "ぞう、かたち", strokes: 12, example: "動物の 象", hint: "ク と 扁 みたい", example_reading: ["ぞう"] },
    { kanji: "焼", readings: ["や(く)", "ショウ"], meaning: "やく、もえる", strokes: 12, example: "肉を 焼く", hint: "火へん に 尭", example_reading: ["や"] },
    { kanji: "照", readings: ["て(らす)", "ショウ"], meaning: "てらす", strokes: 13, example: "太陽が 照らす", hint: "昭 と 灬", example_reading: ["て"] },
    { kanji: "賞", readings: ["ショウ"], meaning: "ほうび", strokes: 15, example: "賞状 をもらう", hint: "尚 と 貝", example_reading: ["しょう"] },
    { kanji: "臣", readings: ["シン"], meaning: "けらい", strokes: 7, example: "大臣 になる", hint: "巨 のなかに 縦棒と横棒", example_reading: ["じん"] },
    { kanji: "信", readings: ["シン"], meaning: "まこと、しんじる", strokes: 9, example: "信号 をまもる", hint: "にんべん に 言", example_reading: ["しん"] },
    { kanji: "成", readings: ["な(る)", "セイ"], meaning: "なる、できあがる", strokes: 6, example: "完成 する", hint: "万 と 戊", example_reading: ["せい"] },
    { kanji: "省", readings: ["はぶ(く)", "ショウ"], meaning: "はぶく、かえりみる", strokes: 9, example: "反省 する", hint: "少 と 目", example_reading: ["せい"] },
    { kanji: "清", readings: ["きよ(い)", "セイ"], meaning: "きよい", strokes: 11, example: "清い こころ", hint: "さんずい に 青", example_reading: ["きよ"] },
    { kanji: "静", readings: ["しず(か)", "セイ"], meaning: "しずか", strokes: 14, example: "静か なよる", hint: "青 と 争", example_reading: ["しず"] },
    { kanji: "席", readings: ["セキ"], meaning: "すわるばしょ", strokes: 10, example: "座席 につく", hint: "まだれ に 廿 と 巾", example_reading: ["せき"] },
    { kanji: "積", readings: ["つ(む)", "セキ"], meaning: "つむ、かさなる", strokes: 16, example: "雪が 積もる", hint: "のぎへん に 責", example_reading: ["つ"] },
    { kanji: "折", readings: ["お(る)", "セツ"], meaning: "おる、まがる", strokes: 7, example: "折り紙 をおる", hint: "てへん に 斤", example_reading: ["お"] },
    { kanji: "節", readings: ["ふし", "セツ"], meaning: "ふし、きせつ", strokes: 13, example: "季節 がかわる", hint: "たけかんむり に 即", example_reading: ["せつ"] },
    { kanji: "説", readings: ["と(く)", "セツ"], meaning: "とく、はなし", strokes: 14, example: "説明 をきく", hint: "ごんべん に 兌", example_reading: ["せつ"] },
    { kanji: "浅", readings: ["あさ(い)", "セン"], meaning: "あさい", strokes: 9, example: "浅い 川", hint: "さんずい に 戔", example_reading: ["あさ"] },
    { kanji: "戦", readings: ["たたか(う)", "セン"], meaning: "たたかう", strokes: 13, example: "戦い にかつ", hint: "単 と 戈", example_reading: ["たたか"] },
    { kanji: "選", readings: ["えら(ぶ)", "セン"], meaning: "えらぶ", strokes: 15, example: "選手 に 選ばれる", hint: "しんにょう に 巽", example_reading: ["せん", "えら"] },
    { kanji: "然", readings: ["ゼン"], meaning: "そのままのようす", strokes: 12, example: "自然 をまもる", hint: "肙 と 犬 と 灬", example_reading: ["ぜん"] },
    { kanji: "争", readings: ["あらそ(う)", "ソウ"], meaning: "あらそう", strokes: 6, example: "競争 する", hint: "ク と ヨ と 亅", example_reading: ["そう"] },
    { kanji: "倉", readings: ["くら", "ソウ"], meaning: "くら", strokes: 10, example: "倉庫 にしまう", hint: "ひとやね に ヨ と 口", example_reading: ["そう"] },
    { kanji: "巣", readings: ["す", "ソウ"], meaning: "とりなどの す", strokes: 11, example: "鳥の 巣", hint: "ツ と 田 と 木", example_reading: ["す"] },
    { kanji: "束", readings: ["たば", "ソク"], meaning: "たば、しばる", strokes: 7, example: "花束 をあげる", hint: "木 のなかに 口", example_reading: ["たば"] },
    { kanji: "側", readings: ["がわ", "ソク"], meaning: "そば、わき", strokes: 11, example: "右側 をあるく", hint: "にんべん に 則", example_reading: ["がわ"] },
    { kanji: "続", readings: ["つづ(く)", "ゾク"], meaning: "つづく", strokes: 13, example: "続き をよむ", hint: "いとへん に 売", example_reading: ["つづ"] },
    { kanji: "卒", readings: ["ソツ"], meaning: "おえる", strokes: 8, example: "卒業 する", hint: "亠 と 人 が２つ と 十", example_reading: ["そつ"] },
    { kanji: "孫", readings: ["まご", "ソン"], meaning: "まご", strokes: 10, example: "お孫 さん", hint: "子へん に 系", example_reading: ["まご"] },

    // --- た行 ---
    { kanji: "帯", readings: ["おび", "タイ"], meaning: "おび", strokes: 10, example: "帯 をしめる", hint: "廿 と ワ と 巾", example_reading: ["おび"] },
    { kanji: "隊", readings: ["タイ"], meaning: "なかまのあつまり", strokes: 12, example: "探検 隊", hint: "こざとへん に 𧢲", example_reading: ["たい"] },
    { kanji: "達", readings: ["たち", "タツ"], meaning: "とどく、〜たち", strokes: 12, example: "友だち", hint: "しんにょう に 羊", example_reading: ["だち"] },
    { kanji: "単", readings: ["タン"], meaning: "ひとつ", strokes: 9, example: "簡単 なもんだい", hint: "ツ と 田 と 十", example_reading: ["たん"] },
    { kanji: "置", readings: ["お(く)", "チ"], meaning: "おく", strokes: 13, example: "本を 置く", hint: "罒 と 直", example_reading: ["お"] },
    { kanji: "仲", readings: ["なか", "チュウ"], meaning: "ひととのつながり", strokes: 6, example: "仲良し", hint: "にんべん に 中", example_reading: ["なか"] },
    { kanji: "貯", readings: ["た(める)", "チョ"], meaning: "たくわえる", strokes: 12, example: "貯金 をする", hint: "貝へん に 宁", example_reading: ["ちょ"] },
    { kanji: "兆", readings: ["きざ(し)", "チョウ"], meaning: "きざし、おおきなかず", strokes: 6, example: "一兆 円", hint: "儿 と ハ と 冫", example_reading: ["ちょう"] },
    { kanji: "腸", readings: ["チョウ"], meaning: "おなかのはたらくところ", strokes: 13, example: "胃腸 のちょうし", hint: "月へん に 昜", example_reading: ["ちょう"] },
    { kanji: "低", readings: ["ひく(い)", "テイ"], meaning: "ひくい", strokes: 7, example: "背が 低い", hint: "にんべん に 氏 と 一", example_reading: ["ひく"] },
    { kanji: "底", readings: ["そこ", "テイ"], meaning: "いちばんした", strokes: 8, example: "海の 底", hint: "まだれ に 氏 と 一", example_reading: ["そこ"] },
    { kanji: "停", readings: ["テイ"], meaning: "とまる", strokes: 11, example: "バスの 停留所", hint: "にんべん に 亭", example_reading: ["てい"] },
    { kanji: "的", readings: ["まと", "テキ"], meaning: "まと", strokes: 8, example: "目的 をきめる", hint: "白 と 勺", example_reading: ["てき"] },
    { kanji: "典", readings: ["テン"], meaning: "きまり、ほん", strokes: 8, example: "辞典 をひく", hint: "曲 と 八", example_reading: ["てん"] },
    { kanji: "伝", readings: ["つた(える)", "デン"], meaning: "つたえる", strokes: 6, example: "手紙で 伝える", hint: "にんべん に 云", example_reading: ["つた"] },
    { kanji: "徒", readings: ["ト"], meaning: "あるく、なかま", strokes: 10, example: "生徒 になる", hint: "ぎょうにんべん に 走", example_reading: ["と"] },
    { kanji: "努", readings: ["つと(める)", "ド"], meaning: "がんばる", strokes: 7, example: "努力 する", hint: "奴 と 力", example_reading: ["ど"] },
    { kanji: "灯", readings: ["ひ", "トウ"], meaning: "あかり", strokes: 6, example: "電灯 をつける", hint: "火へん に 丁", example_reading: ["とう"] },
    { kanji: "堂", readings: ["ドウ"], meaning: "おおきなたてもの", strokes: 11, example: "食堂 でたべる", hint: "尚 と 土", example_reading: ["どう"] },
    { kanji: "働", readings: ["はたら(く)", "ドウ"], meaning: "はたらく", strokes: 13, example: "よく 働く", hint: "にんべん に 動", example_reading: ["はたら"] },
    { kanji: "特", readings: ["トク"], meaning: "とくべつ", strokes: 10, example: "特別 なひ", hint: "牛へん に 寺", example_reading: ["とく"] },
    { kanji: "得", readings: ["え(る)", "トク"], meaning: "てにいれる", strokes: 11, example: "得意 なこと", hint: "ぎょうにんべん に 旦 と 寸", example_reading: ["とく"] },
    { kanji: "毒", readings: ["ドク"], meaning: "からだにわるいもの", strokes: 8, example: "毒 キノコ", hint: "生 と 母", example_reading: ["どく"] },

    // --- な行 ---
    { kanji: "熱", readings: ["あつ(い)", "ネツ"], meaning: "あつい、ねつ", strokes: 15, example: "熱 がでる", hint: "勢 の下に 灬", example_reading: ["ねつ"] },
    { kanji: "念", readings: ["ネン"], meaning: "おもう", strokes: 8, example: "残念 だ", hint: "今 と 心", example_reading: ["ねん"] },

    // --- は行 ---
    { kanji: "敗", readings: ["やぶ(れる)", "ハイ"], meaning: "まける", strokes: 11, example: "勝敗 がきまる", hint: "貝 と 攵", example_reading: ["はい"] },
    { kanji: "梅", readings: ["うめ", "バイ"], meaning: "うめのき", strokes: 10, example: "梅 のはな", hint: "木へん に 毎", example_reading: ["うめ"] },
    { kanji: "博", readings: ["ハク"], meaning: "ひろくしる", strokes: 12, example: "博物館", hint: "十 と 甫 と 寸", example_reading: ["はく"] },
    { kanji: "飯", readings: ["めし", "ハン"], meaning: "ごはん", strokes: 12, example: "ご飯 をたべる", hint: "食へん に 反", example_reading: ["はん"] },
    { kanji: "飛", readings: ["と(ぶ)", "ヒ"], meaning: "とぶ", strokes: 9, example: "空を 飛ぶ", hint: "羽 みたいに飛ぶかたち", example_reading: ["と"] },
    { kanji: "費", readings: ["つい(やす)", "ヒ"], meaning: "つかう", strokes: 12, example: "参加 費", hint: "弗 と 貝", example_reading: ["ひ"] },
    { kanji: "必", readings: ["かなら(ず)", "ヒツ"], meaning: "かならず", strokes: 5, example: "必ず いく", hint: "心 に ノ", example_reading: ["かなら"] },
    { kanji: "票", readings: ["ヒョウ"], meaning: "ふだ", strokes: 11, example: "投票 する", hint: "西 と 示", example_reading: ["ひょう"] },
    { kanji: "標", readings: ["ヒョウ"], meaning: "めじるし", strokes: 15, example: "目標 をきめる", hint: "木へん に 票", example_reading: ["ひょう"] },
    { kanji: "不", readings: ["フ"], meaning: "〜ない", strokes: 4, example: "不安 になる", hint: "一 と ノ と 縦棒と てん", example_reading: ["ふ"] },
    { kanji: "夫", readings: ["おっと", "フ"], meaning: "おとこのひと", strokes: 4, example: "夫婦 になる", hint: "二 と 人", example_reading: ["ふう"] },
    { kanji: "付", readings: ["つ(く)", "フ"], meaning: "つける", strokes: 5, example: "おまけが 付く", hint: "にんべん に 寸", example_reading: ["つ"] },
    { kanji: "府", readings: ["フ"], meaning: "やくしょ、おおきなまち", strokes: 8, example: "大阪 府", hint: "まだれ に 付", example_reading: ["ふ"] },
    { kanji: "副", readings: ["フク"], meaning: "そえる、ふたつめ", strokes: 11, example: "副 社長", hint: "畐 と 刂", example_reading: ["ふく"] },
    { kanji: "粉", readings: ["こな", "フン"], meaning: "こな", strokes: 10, example: "小麦 粉", hint: "米へん に 分", example_reading: ["こ"] },
    { kanji: "兵", readings: ["ヘイ"], meaning: "へいたい", strokes: 7, example: "兵士 になる", hint: "丘 と 八", example_reading: ["へい"] },
    { kanji: "別", readings: ["わか(れる)", "ベツ"], meaning: "わかれる、ちがう", strokes: 7, example: "特別な 日", hint: "口 と 力 と 刂", example_reading: ["べつ"] },
    { kanji: "辺", readings: ["あた(り)", "ヘン"], meaning: "あたり、ふち", strokes: 5, example: "この 辺り", hint: "しんにょう に 刀", example_reading: ["あた"] },
    { kanji: "変", readings: ["か(わる)", "ヘン"], meaning: "かわる、おかしい", strokes: 9, example: "変化 する", hint: "亦 と 攵", example_reading: ["へん"] },
    { kanji: "便", readings: ["たよ(り)", "ベン"], meaning: "たより、つごうがいい", strokes: 9, example: "便利 などうぐ", hint: "にんべん に 更", example_reading: ["べん"] },
    { kanji: "包", readings: ["つつ(む)", "ホウ"], meaning: "つつむ", strokes: 5, example: "包み 紙", hint: "勹 に 己", example_reading: ["つつ"] },
    { kanji: "法", readings: ["ホウ"], meaning: "きまり、やりかた", strokes: 8, example: "方法 をかんがえる", hint: "さんずい に 去", example_reading: ["ほう"] },
    { kanji: "望", readings: ["のぞ(む)", "ボウ"], meaning: "のぞむ", strokes: 11, example: "希望 をもつ", hint: "亡 と 月 と 王", example_reading: ["ぼう"] },
    { kanji: "牧", readings: ["まき", "ボク"], meaning: "うしやうまを かう", strokes: 8, example: "牧場 にいく", hint: "牛へん に 攵", example_reading: ["ぼく"] },

    // --- ま行 ---
    { kanji: "末", readings: ["すえ", "マツ"], meaning: "おわり", strokes: 5, example: "週末 にあそぶ", hint: "木 のうえの横棒が 長い", example_reading: ["まつ"] },
    { kanji: "満", readings: ["み(ちる)", "マン"], meaning: "いっぱいになる", strokes: 12, example: "満点 をとる", hint: "さんずい に 廿 と 両", example_reading: ["まん"] },
    { kanji: "未", readings: ["ミ"], meaning: "まだ〜ない", strokes: 5, example: "未来 のこと", hint: "木 のうえの横棒が 短い", example_reading: ["み"] },
    { kanji: "脈", readings: ["ミャク"], meaning: "すじ", strokes: 10, example: "山脈", hint: "月へん に 𠂢", example_reading: ["みゃく"] },
    { kanji: "民", readings: ["たみ", "ミン"], meaning: "ひとびと", strokes: 5, example: "国民", hint: "コ と 氏", example_reading: ["みん"] },
    { kanji: "無", readings: ["な(い)", "ム"], meaning: "ない", strokes: 12, example: "無料 であそべる", hint: "大 の下に 灬 みたいなかたち", example_reading: ["む"] },

    // --- や行 ---
    { kanji: "約", readings: ["ヤク"], meaning: "むすぶ、ちぢめる", strokes: 9, example: "約束 をまもる", hint: "いとへん に 勺", example_reading: ["やく"] },
    { kanji: "勇", readings: ["いさ(む)", "ユウ"], meaning: "いさましい", strokes: 9, example: "勇気 をだす", hint: "マ と 男", example_reading: ["ゆう"] },
    { kanji: "要", readings: ["い(る)", "ヨウ"], meaning: "かなめ、ひつよう", strokes: 9, example: "重要 なこと", hint: "西 と 女", example_reading: ["よう"] },
    { kanji: "養", readings: ["やしな(う)", "ヨウ"], meaning: "そだてる", strokes: 15, example: "栄養 をとる", hint: "羊 と 良", example_reading: ["よう"] },
    { kanji: "浴", readings: ["あ(びる)", "ヨク"], meaning: "あびる", strokes: 10, example: "お風呂に 浴びる", hint: "さんずい に 谷", example_reading: ["あ"] },

    // --- ら行 ---
    { kanji: "利", readings: ["き(く)", "リ"], meaning: "よくきく、もうけ", strokes: 7, example: "便利 なもの", hint: "禾 と 刂", example_reading: ["り"] },
    { kanji: "陸", readings: ["リク"], meaning: "おか、じめん", strokes: 11, example: "陸上 きょうぎ", hint: "こざとへん に 坴", example_reading: ["りく"] },
    { kanji: "良", readings: ["よ(い)", "リョウ"], meaning: "よい", strokes: 7, example: "良い こども", hint: "点 と 艮", example_reading: ["よ"] },
    { kanji: "料", readings: ["リョウ"], meaning: "はかる、ざいりょう", strokes: 10, example: "材料", hint: "米へん に 斗", example_reading: ["りょう"] },
    { kanji: "量", readings: ["はか(る)", "リョウ"], meaning: "かさ、おもさ", strokes: 12, example: "重さを 量る", hint: "日 と 一 と 里", example_reading: ["はか"] },
    { kanji: "輪", readings: ["わ", "リン"], meaning: "わっか", strokes: 15, example: "車輪 をまわす", hint: "車へん に 侖", example_reading: ["りん"] },
    { kanji: "類", readings: ["たぐい", "ルイ"], meaning: "なかま、しゅるい", strokes: 18, example: "種類 がおおい", hint: "米 と 大 と 頁", example_reading: ["るい"] },
    { kanji: "令", readings: ["レイ"], meaning: "いいつける", strokes: 5, example: "号令 をかける", hint: "ひとやね と マ", example_reading: ["れい"] },
    { kanji: "冷", readings: ["つめ(たい)", "レイ"], meaning: "つめたい", strokes: 7, example: "冷たい アイス", hint: "にすい に 令", example_reading: ["つめ"] },
    { kanji: "例", readings: ["たと(える)", "レイ"], meaning: "たとえる", strokes: 8, example: "例えば", hint: "にんべん に 列", example_reading: ["たと"] },
    { kanji: "歴", readings: ["レキ"], meaning: "へてくること", strokes: 14, example: "歴史 のほん", hint: "まだれ に 林 と 止", example_reading: ["れき"] },
    { kanji: "連", readings: ["つら(なる)", "レン"], meaning: "つらなる、つれる", strokes: 10, example: "連休 にあそぶ", hint: "しんにょう に 車", example_reading: ["れん"] },
    { kanji: "老", readings: ["お(いる)", "ロウ"], meaning: "おいる", strokes: 6, example: "敬老 のひ", hint: "土 と ノ と ヒ", example_reading: ["ろう"] },
    { kanji: "労", readings: ["ロウ"], meaning: "はたらく、つかれる", strokes: 7, example: "労働 する", hint: "ツ と ワ と 力", example_reading: ["ろう"] },
    { kanji: "録", readings: ["ロク"], meaning: "しるす", strokes: 16, example: "記録 をとる", hint: "かねへん に 彔", example_reading: ["ろく"] }
];