// kanji/grade5.js - 5年生の漢字データ（185字）
// 各漢字: kanji, readings(読み方), meaning(意味), strokes(画数), example(例文), hint(覚え方ヒント)

const GRADE5_KANJI = [
    // --- あ行 ---
    { kanji: "移", readings: ["うつ(る)", "イ"], meaning: "うつる", strokes: 11, example: "移動 する", hint: "のぎへん に 多" },
    { kanji: "圧", readings: ["アツ"], meaning: "おしつける", strokes: 5, example: "血圧 をはかる", hint: "がんだれ に 土" },
    { kanji: "因", readings: ["イン"], meaning: "もとになること", strokes: 6, example: "原因 をさぐる", hint: "くにがまえ に 大" },
    { kanji: "永", readings: ["なが(い)", "エイ"], meaning: "じかんがながい", strokes: 5, example: "永遠", hint: "水 にてん がつく" },
    { kanji: "営", readings: ["いとな(む)", "エイ"], meaning: "しごとをする", strokes: 12, example: "営業 時間", hint: "ツ と ワ と 呂" },
    { kanji: "液", readings: ["エキ"], meaning: "しる", strokes: 11, example: "液体", hint: "さんずい に 夜" },
    { kanji: "演", readings: ["エン"], meaning: "やってみせる", strokes: 14, example: "演技 をする", hint: "さんずい に 寅" },
    { kanji: "衛", readings: ["エイ"], meaning: "まもる", strokes: 16, example: "人工 衛星", hint: "行 のなかに 韋" },
    { kanji: "易", readings: ["やさ(しい)", "エキ"], meaning: "かんたん", strokes: 8, example: "容易 なもんだい", hint: "日 と 勿" },
    { kanji: "益", readings: ["エキ"], meaning: "ためになること", strokes: 10, example: "利益", hint: "八 と 王 と 皿" },
    { kanji: "応", readings: ["こた(える)", "オウ"], meaning: "こたえる", strokes: 7, example: "応援 する", hint: "まだれ と 心" },
    { kanji: "往", readings: ["オウ"], meaning: "いく", strokes: 8, example: "往復", hint: "ぎょうにんべん に 主" },
    { kanji: "桜", readings: ["さくら", "オウ"], meaning: "さくらのき", strokes: 10, example: "桜 の花", hint: "木へん に ツ と 女" },
    { kanji: "恩", readings: ["オン"], meaning: "ありがたいこと", strokes: 10, example: "恩返し", hint: "因 と 心" },

    // --- か行 ---
    { kanji: "可", readings: ["カ"], meaning: "よい", strokes: 5, example: "可能", hint: "丁 と 口" },
    { kanji: "仮", readings: ["かり", "カ"], meaning: "かり", strokes: 6, example: "仮 のすがた", hint: "にんべん に 反" },
    { kanji: "価", readings: ["あたい", "カ"], meaning: "ねだん", strokes: 8, example: "価値 がある", hint: "にんべん に 西" },
    { kanji: "河", readings: ["かわ", "カ"], meaning: "おおきなかわ", strokes: 8, example: "河川", hint: "さんずい に 可" },
    { kanji: "過", readings: ["す(ぎる)", "カ"], meaning: "すぎる", strokes: 12, example: "過去 のこと", hint: "しんにょう に 咼" },
    { kanji: "賀", readings: ["ガ"], meaning: "いわう", strokes: 12, example: "年賀状", hint: "加 と 貝" },
    { kanji: "快", readings: ["こころよ(い)", "カイ"], meaning: "きもちいい", strokes: 7, example: "快適", hint: "りっしんべん に 夬" },
    { kanji: "解", readings: ["と(く)", "カイ"], meaning: "わかる、ほどく", strokes: 13, example: "解決 する", hint: "角 と 刀 と 牛" },
    { kanji: "格", readings: ["カク"], meaning: "きまり", strokes: 10, example: "合格", hint: "木へん に 各" },
    { kanji: "確", readings: ["たし(か)", "カク"], meaning: "たしか", strokes: 15, example: "確認 する", hint: "石へん に 隺" },
    { kanji: "額", readings: ["ひたい", "ガク"], meaning: "ひたい、おかね", strokes: 18, example: "金額", hint: "客 と 頁" },
    { kanji: "刊", readings: ["カン"], meaning: "ほんをだす", strokes: 5, example: "朝刊 をよむ", hint: "干 と 刂" },
    { kanji: "眼", readings: ["め", "ガン"], meaning: "め", strokes: 11, example: "眼科", hint: "目へん に 艮" },
    { kanji: "基", readings: ["もと", "キ"], meaning: "もと", strokes: 11, example: "基本", hint: "其 と 土" },
    { kanji: "寄", readings: ["よ(る)", "キ"], meaning: "よる", strokes: 11, example: "立ち 寄る", hint: "うかんむり に 奇" },
    { kanji: "慣", readings: ["な(れる)", "カン"], meaning: "なれる", strokes: 14, example: "習慣", hint: "りっしんべん に 貫" },
    { kanji: "幹", readings: ["みき", "カン"], meaning: "みき", strokes: 13, example: "新幹線", hint: "幸 のなかに 木" },
    { kanji: "逆", readings: ["さか(らう)", "ギャク"], meaning: "はんたい", strokes: 9, example: "逆立ち", hint: "しんにょう に 屰" },
    { kanji: "規", readings: ["キ"], meaning: "きまり", strokes: 11, example: "規則 をまもる", hint: "夫 と 見" },
    { kanji: "技", readings: ["わざ", "ギ"], meaning: "わざ", strokes: 7, example: "技術", hint: "てへん に 支" },
    { kanji: "義", readings: ["ギ"], meaning: "ただしい", strokes: 13, example: "正義", hint: "羊 と 我" },
    { kanji: "境", readings: ["さかい", "キョウ"], meaning: "さかいめ", strokes: 14, example: "国境", hint: "土へん に 竟" },
    { kanji: "旧", readings: ["キュウ"], meaning: "ふるい", strokes: 5, example: "旧正月", hint: "1 と 日" },
    { kanji: "居", readings: ["い(る)", "キョ"], meaning: "いる", strokes: 8, example: "居間", hint: "しかばね に 古" },
    { kanji: "久", readings: ["ひさ(しい)", "キュウ"], meaning: "ながいじかん", strokes: 3, example: "久しぶり", hint: "ク と ノ" },
    { kanji: "許", readings: ["ゆる(す)", "キョ"], meaning: "ゆるす", strokes: 11, example: "許可 をとる", hint: "ごんべん に 午" },
    { kanji: "均", readings: ["キン"], meaning: "おなじ", strokes: 7, example: "平均", hint: "土へん に 匀" },
    { kanji: "禁", readings: ["キン"], meaning: "してはいけない", strokes: 13, example: "禁止", hint: "林 と 示" },
    { kanji: "句", readings: ["ク"], meaning: "ことば", strokes: 5, example: "俳句 をよむ", hint: "勹 に 口" },
    { kanji: "群", readings: ["むれ", "グン"], meaning: "むれ", strokes: 13, example: "群れ をなす", hint: "君 と 羊" },
    { kanji: "経", readings: ["へ(る)", "ケイ"], meaning: "とおる", strokes: 11, example: "経験", hint: "いとへん に 巠" },
    { kanji: "潔", readings: ["ケツ"], meaning: "きれい", strokes: 15, example: "清潔", hint: "さんずい に 絜" },
    { kanji: "件", readings: ["ケン"], meaning: "ことがら", strokes: 6, example: "事件", hint: "にんべん に 牛" },
    { kanji: "券", readings: ["ケン"], meaning: "チケット", strokes: 8, example: "乗車券", hint: "龹 と 刀" },
    { kanji: "険", readings: ["けわ(しい)", "ケン"], meaning: "けわしい", strokes: 11, example: "危険", hint: "こざとへん に 僉" },
    { kanji: "検", readings: ["ケン"], meaning: "しらべる", strokes: 12, example: "検査 する", hint: "木へん に 僉" },
    { kanji: "限", readings: ["かぎ(る)", "ゲン"], meaning: "かぎり", strokes: 9, example: "限界", hint: "こざとへん に 艮" },
    { kanji: "現", readings: ["あらわ(れる)", "ゲン"], meaning: "あらわれる", strokes: 11, example: "現在", hint: "王へん に 見" },
    { kanji: "減", readings: ["へ(る)", "ゲン"], meaning: "へる", strokes: 12, example: "減少 する", hint: "さんずい に 咸" },
    { kanji: "故", readings: ["ゆえ", "コ"], meaning: "むかし、わけ", strokes: 9, example: "事故", hint: "古 と 攵" },
    { kanji: "個", readings: ["コ"], meaning: "ひとつ", strokes: 10, example: "個人", hint: "にんべん に 固" },
    { kanji: "効", readings: ["き(く)", "コウ"], meaning: "ききめ", strokes: 8, example: "効果", hint: "交 と 力" },
    { kanji: "護", readings: ["ゴ"], meaning: "まもる", strokes: 20, example: "保護 する", hint: "ごんべん と 蒦" },
    { kanji: "鉱", readings: ["コウ"], meaning: "こうぶつ", strokes: 13, example: "鉱石", hint: "かねへん に 広" },
    { kanji: "耕", readings: ["たがや(す)", "コウ"], meaning: "たがやす", strokes: 10, example: "耕運機", hint: "耒 と 井" },
    { kanji: "厚", readings: ["あつ(い)", "コウ"], meaning: "ぶあつい", strokes: 9, example: "厚い 本", hint: "がんだれ に 日 と 子" },

    // --- さ行 ---
    { kanji: "興", readings: ["キョウ"], meaning: "おこす", strokes: 16, example: "興味 をもつ", hint: "同 のまわりに いろいろ" },
    { kanji: "構", readings: ["かま(える)", "コウ"], meaning: "かまえる、くみたてる", strokes: 14, example: "構造", hint: "木へん に 冓" },
    { kanji: "講", readings: ["コウ"], meaning: "はなす", strokes: 17, example: "講演 会", hint: "ごんべん に 冓" },
    { kanji: "混", readings: ["ま(ざる)", "コン"], meaning: "まざる", strokes: 11, example: "混雑", hint: "さんずい に 昆" },
    { kanji: "査", readings: ["サ"], meaning: "しらべる", strokes: 9, example: "調査 する", hint: "木 と 且" },
    { kanji: "再", readings: ["ふたた(び)", "サイ"], meaning: "もういちど", strokes: 6, example: "再び", hint: "一 と 冂 と 王" },
    { kanji: "災", readings: ["わざわ(い)", "サイ"], meaning: "わざわい", strokes: 7, example: "災害", hint: "く と く と く と 火" },
    { kanji: "妻", readings: ["つま", "サイ"], meaning: "おくさん", strokes: 8, example: "夫妻", hint: "十 と ヨ と 女" },
    { kanji: "採", readings: ["と(る)", "サイ"], meaning: "とる", strokes: 11, example: "昆虫 採集", hint: "てへん に 采" },
    { kanji: "際", readings: ["きわ", "サイ"], meaning: "きわ、〜のとき", strokes: 14, example: "国際", hint: "こざとへん に 祭" },
    { kanji: "在", readings: ["あ(る)", "ザイ"], meaning: "ある", strokes: 6, example: "存在", hint: "ナ と ノ と 土" },
    { kanji: "罪", readings: ["つみ", "ザイ"], meaning: "つみ", strokes: 13, example: "犯罪", hint: "四 みたい なのと 非" },
    { kanji: "雑", readings: ["ザツ"], meaning: "まざる", strokes: 14, example: "複雑", hint: "九 と 木 と 隹" },
    { kanji: "財", readings: ["ザイ"], meaning: "おかね", strokes: 10, example: "財布", hint: "貝へん に 才" },
    { kanji: "酸", readings: ["サン"], meaning: "すっぱい", strokes: 14, example: "酸素", hint: "酉へん に 夋" },
    { kanji: "賛", readings: ["サン"], meaning: "さんせいする", strokes: 15, example: "賛成", hint: "夫 と 夫 と 貝" },
    { kanji: "支", readings: ["ささ(える)", "シ"], meaning: "ささえる", strokes: 4, example: "支持", hint: "十 と 又" },
    { kanji: "志", readings: ["こころざし", "シ"], meaning: "こころざし", strokes: 7, example: "意志", hint: "士 と 心" },
    { kanji: "枝", readings: ["えだ", "シ"], meaning: "えだ", strokes: 8, example: "木の 枝", hint: "木へん に 支" },
    { kanji: "師", readings: ["シ"], meaning: "先生", strokes: 10, example: "医師", hint: "𠂤 と 帀" },
    { kanji: "資", readings: ["シ"], meaning: "もとで", strokes: 13, example: "資金", hint: "次 と 貝" },
    { kanji: "飼", readings: ["か(う)", "シ"], meaning: "えさをあげる", strokes: 13, example: "飼育", hint: "食へん に 司" },
    { kanji: "示", readings: ["しめ(す)", "シ"], meaning: "しめす", strokes: 5, example: "指示", hint: "二 と 小" },
    { kanji: "似", readings: ["に(る)", "ジ"], meaning: "にている", strokes: 7, example: "似顔絵", hint: "にんべん に 以" },
    { kanji: "識", readings: ["シキ"], meaning: "しる", strokes: 19, example: "知識", hint: "ごんべん に 音 と 戈" },
    { kanji: "質", readings: ["シツ"], meaning: "なかみ", strokes: 15, example: "質問", hint: "斤 と 斤 と 貝" },
    { kanji: "述", readings: ["の(べる)", "ジュツ"], meaning: "はなす", strokes: 8, example: "記述", hint: "しんにょう に 朮" },
    { kanji: "修", readings: ["おさ(める)", "シュウ"], meaning: "なおす", strokes: 10, example: "修理", hint: "イ と ｜ と 攵 と 彡" },
    { kanji: "準", readings: ["ジュン"], meaning: "めやす", strokes: 13, example: "準備", hint: "さんずい と 隹 と 十" },
    { kanji: "舎", readings: ["シャ"], meaning: "いえ", strokes: 8, example: "校舎", hint: "人 と 舌" },
    { kanji: "術", readings: ["ジュツ"], meaning: "わざ", strokes: 11, example: "手術", hint: "行 のなかに 朮" },
    { kanji: "謝", readings: ["あやま(る)", "シャ"], meaning: "あやまる", strokes: 17, example: "感謝", hint: "ごんべん に 射" },
    { kanji: "授", readings: ["さず(ける)", "ジュ"], meaning: "あたえる", strokes: 11, example: "授業", hint: "てへん に 受" },
    { kanji: "招", readings: ["まね(く)", "ショウ"], meaning: "よぶ", strokes: 8, example: "招待", hint: "てへん に 召" },
    { kanji: "序", readings: ["ジョ"], meaning: "じゅんばん", strokes: 7, example: "順序", hint: "まだれ に 予" },
    { kanji: "証", readings: ["ショウ"], meaning: "しょうめいする", strokes: 12, example: "証明", hint: "ごんべん に 正" },
    { kanji: "承", readings: ["うけたまわ(る)", "ショウ"], meaning: "うける", strokes: 8, example: "承知", hint: "乙 と 水 みたいなかたち" },
    { kanji: "常", readings: ["つね", "ジョウ"], meaning: "いつも", strokes: 11, example: "日常", hint: "尚 と 巾" },
    { kanji: "条", readings: ["ジョウ"], meaning: "すじ", strokes: 7, example: "条件", hint: "夂 と 木" },
    { kanji: "状", readings: ["ジョウ"], meaning: "ようす", strokes: 7, example: "状況", hint: "冫 と 犬" },
    { kanji: "情", readings: ["なさ(け)", "ジョウ"], meaning: "きもち", strokes: 11, example: "友情", hint: "りっしんべん に 青" },
    { kanji: "職", readings: ["ショク"], meaning: "しごと", strokes: 18, example: "職業", hint: "耳 と 音 と 戈" },
    { kanji: "織", readings: ["お(る)", "シキ"], meaning: "ぬのを おる", strokes: 18, example: "組織", hint: "いとへん に 音 と 戈" },
    { kanji: "制", readings: ["セイ"], meaning: "きまり", strokes: 8, example: "制度", hint: "牛 と 巾 と 刂" },
    { kanji: "性", readings: ["セイ", "ショウ"], meaning: "うまれつきの せいしつ", strokes: 8, example: "性格", hint: "りっしんべん に 生" },
    { kanji: "政", readings: ["まつりごと", "セイ"], meaning: "くにを おさめる", strokes: 9, example: "政治", hint: "正 と 攵" },
    { kanji: "勢", readings: ["いきお(い)", "セイ"], meaning: "いきおい", strokes: 13, example: "勢い がある", hint: "執 のしたに 力" },
    { kanji: "精", readings: ["セイ", "ショウ"], meaning: "まじりけのない", strokes: 14, example: "妖精", hint: "米へん に 青" },
    { kanji: "製", readings: ["セイ"], meaning: "つくる", strokes: 14, example: "製品", hint: "制 のしたに 衣" },
    { kanji: "税", readings: ["ゼイ"], meaning: "くにに おさめるおかね", strokes: 12, example: "消費税", hint: "のぎへん に 兌" },
    { kanji: "責", readings: ["せ(める)", "セキ"], meaning: "せめる、つとめ", strokes: 11, example: "責任 をもつ", hint: "主 と 貝" },
    { kanji: "績", readings: ["セキ"], meaning: "つむぐ、てがら", strokes: 17, example: "成績", hint: "いとへん に 責" },
    { kanji: "接", readings: ["つ(ぐ)", "セツ"], meaning: "くっつく", strokes: 11, example: "直接", hint: "てへん に 妾" },
    { kanji: "設", readings: ["もう(ける)", "セツ"], meaning: "つくる", strokes: 11, example: "設計 する", hint: "ごんべん に 殳" },
    { kanji: "舌", readings: ["した", "ゼツ"], meaning: "した", strokes: 6, example: "舌 をだす", hint: "千 と 口" },
    { kanji: "絶", readings: ["た(える)", "ゼツ"], meaning: "たえる", strokes: 12, example: "絶対", hint: "いとへん に 色" },
    { kanji: "総", readings: ["ソウ"], meaning: "すべて", strokes: 14, example: "総合", hint: "いとへん に 公 と 心" },
    { kanji: "素", readings: ["ソ", "ス"], meaning: "もと", strokes: 10, example: "素直 なこころ", hint: "主 と 糸" },
    { kanji: "祖", readings: ["ソ"], meaning: "ごせんぞさま", strokes: 9, example: "祖父", hint: "しめすへん に 且" },
    { kanji: "銭", readings: ["ぜに", "セン"], meaning: "おかね", strokes: 14, example: "小銭", hint: "かねへん に 戔" },

    // --- た行 ---
    { kanji: "造", readings: ["つく(る)", "ゾウ"], meaning: "つくる", strokes: 10, example: "造形", hint: "しんにょう に 告" },
    { kanji: "像", readings: ["ゾウ"], meaning: "かたち、すがた", strokes: 14, example: "想像 する", hint: "にんべん に 象" },
    { kanji: "増", readings: ["ふ(える)", "ゾウ"], meaning: "ふえる", strokes: 14, example: "増加", hint: "土へん に 曽" },
    { kanji: "則", readings: ["ソク"], meaning: "きまり", strokes: 9, example: "規則", hint: "貝 と 刂" },
    { kanji: "測", readings: ["はか(る)", "ソク"], meaning: "はかる", strokes: 12, example: "測定", hint: "さんずい に 則" },
    { kanji: "損", readings: ["そこ(なう)", "ソン"], meaning: "へる、わるくする", strokes: 13, example: "損害", hint: "てへん に 員" },
    { kanji: "退", readings: ["しりぞ(く)", "タイ"], meaning: "さがる", strokes: 9, example: "退学", hint: "しんにょう に 艮" },
    { kanji: "属", readings: ["ゾク"], meaning: "なかまに はいる", strokes: 12, example: "所属", hint: "尸 と 禹" },
    { kanji: "率", readings: ["ひき(いる)", "ソツ", "リツ"], meaning: "ひきいる、わりあい", strokes: 11, example: "確率", hint: "玄 のまわりに 点々 と 十" },
    { kanji: "貸", readings: ["か(す)", "タイ"], meaning: "かす", strokes: 12, example: "貸し出し", hint: "代 と 貝" },
    { kanji: "態", readings: ["タイ"], meaning: "ようす", strokes: 14, example: "態度", hint: "能 と 心" },
    { kanji: "築", readings: ["きず(く)", "チク"], meaning: "たてる", strokes: 16, example: "建築", hint: "竹 と 筑 と 木" },
    { kanji: "断", readings: ["た(つ)", "ダン"], meaning: "きる、ことわる", strokes: 11, example: "横断 歩道", hint: "米 と L と 斤" },
    { kanji: "団", readings: ["ダン"], meaning: "あつまり", strokes: 6, example: "団体", hint: "くにがまえ に 寸" },
    { kanji: "張", readings: ["は(る)", "チョウ"], meaning: "はる", strokes: 11, example: "頑張る", hint: "弓へん に 長" },
    { kanji: "程", readings: ["ほど", "テイ"], meaning: "めやす、きまり", strokes: 12, example: "程度", hint: "のぎへん に 呈" },
    { kanji: "提", readings: ["さ(げる)", "テイ"], meaning: "だす", strokes: 12, example: "提出 する", hint: "てへん に 是" },
    { kanji: "適", readings: ["テキ"], meaning: "あてはまる", strokes: 14, example: "適当", hint: "しんにょう に 啇" },
    { kanji: "敵", readings: ["てき", "テキ"], meaning: "あいて", strokes: 15, example: "ライバルは 敵", hint: "啇 と 攵" },
    { kanji: "統", readings: ["す(べる)", "トウ"], meaning: "まとめる", strokes: 12, example: "統一", hint: "いとへん に 充" },
    { kanji: "銅", readings: ["ドウ"], meaning: "あかがね", strokes: 14, example: "銅メダル", hint: "かねへん に 同" },
    { kanji: "導", readings: ["みちび(く)", "ドウ"], meaning: "みちびく", strokes: 15, example: "案内して 導く", hint: "道 のしたに 寸" },
    { kanji: "徳", readings: ["トク"], meaning: "りっぱなおこない", strokes: 14, example: "道徳", hint: "ぎょうにんべん に 悳" },
    { kanji: "独", readings: ["ひと(り)", "ドク"], meaning: "ひとり", strokes: 9, example: "独立", hint: "けものへん に 虫" },

    // --- な行 ---
    { kanji: "任", readings: ["まか(せる)", "ニン"], meaning: "まかせる", strokes: 6, example: "担任 の先生", hint: "にんべん に 壬" },
    { kanji: "燃", readings: ["も(える)", "ネン"], meaning: "もえる", strokes: 16, example: "燃える ゴミ", hint: "火へん に 然" },
    { kanji: "能", readings: ["ノウ"], meaning: "できる、はたらき", strokes: 10, example: "可能 性", hint: "ム と 月 と ヒ ２つ" },

    // --- は行 ---
    { kanji: "破", readings: ["やぶ(る)", "ハ"], meaning: "やぶる", strokes: 10, example: "紙を 破る", hint: "石へん に 皮" },
    { kanji: "犯", readings: ["おか(す)", "ハン"], meaning: "きまりを やぶる", strokes: 5, example: "犯人", hint: "けものへん に 卩" },
    { kanji: "判", readings: ["ハン"], meaning: "みわける", strokes: 7, example: "判断 する", hint: "半 と 刂" },
    { kanji: "版", readings: ["ハン"], meaning: "いた、いんさつ", strokes: 8, example: "出版", hint: "片 と 反" },
    { kanji: "比", readings: ["くら(べる)", "ヒ"], meaning: "くらべる", strokes: 4, example: "比較 する", hint: "ヒ が ２つ" },
    { kanji: "備", readings: ["そな(える)", "ビ"], meaning: "よういする", strokes: 12, example: "準備", hint: "にんべん に 𤰔" },
    { kanji: "非", readings: ["ヒ"], meaning: "あらず", strokes: 8, example: "非常口", hint: "はね みたい なかたち" },
    { kanji: "肥", readings: ["こ(える)", "ヒ"], meaning: "ふとる、こえる", strokes: 8, example: "肥料", hint: "月へん に 巴" },
    { kanji: "評", readings: ["ヒョウ"], meaning: "ねうちをきめる", strokes: 12, example: "評判", hint: "ごんべん に 平" },
    { kanji: "俵", readings: ["たわら", "ヒョウ"], meaning: "たわら", strokes: 10, example: "米 俵", hint: "にんべん に 表" },
    { kanji: "婦", readings: ["フ"], meaning: "おんなのひと", strokes: 11, example: "主婦", hint: "女へん に 帚" },
    { kanji: "布", readings: ["ぬの", "フ"], meaning: "ぬの", strokes: 5, example: "毛布", hint: "ナ と 巾" },
    { kanji: "貧", readings: ["まず(しい)", "ヒン"], meaning: "まずしい", strokes: 11, example: "貧乏", hint: "分 と 貝" },
    { kanji: "武", readings: ["ブ", "ム"], meaning: "たたかい", strokes: 8, example: "武士", hint: "一 と 止 と 戈" },
    { kanji: "復", readings: ["フク"], meaning: "もとに もどる", strokes: 12, example: "復習 する", hint: "ぎょうにんべん に 複 の右側" },
    { kanji: "富", readings: ["とみ", "フ"], meaning: "ゆたかになる", strokes: 12, example: "富士 山", hint: "うかんむり に 畐" },
    { kanji: "複", readings: ["フク"], meaning: "かさなる", strokes: 14, example: "複雑", hint: "ころもへん に 復 の右側" },
    { kanji: "仏", readings: ["ほとけ", "ブツ"], meaning: "ほとけさま", strokes: 4, example: "大仏", hint: "にんべん に ム" },
    { kanji: "編", readings: ["あ(む)", "ヘン"], meaning: "あむ、まとめる", strokes: 15, example: "毛糸を 編む", hint: "いとへん に 扁" },
    { kanji: "弁", readings: ["ベン"], meaning: "はなす、わける", strokes: 5, example: "お弁当", hint: "ム と 廾" },
    { kanji: "貿", readings: ["ボウ"], meaning: "やりとりする", strokes: 12, example: "貿易", hint: "卯 と 貝" },
    { kanji: "防", readings: ["ふせ(ぐ)", "ボウ"], meaning: "ふせぐ", strokes: 7, example: "予防", hint: "こざとへん に 方" },
    { kanji: "保", readings: ["たも(つ)", "ホ"], meaning: "まもる、たもつ", strokes: 9, example: "保健 室", hint: "にんべん に 呆" },
    { kanji: "墓", readings: ["はか", "ボ"], meaning: "おはか", strokes: 13, example: "お墓 まいり", hint: "莫 のしたに 土" },
    { kanji: "報", readings: ["むく(いる)", "ホウ"], meaning: "しらせる", strokes: 12, example: "報告 する", hint: "幸 と 丸 みたい なの と 又" },
    { kanji: "豊", readings: ["ゆた(か)", "ホウ"], meaning: "ゆたか", strokes: 13, example: "豊か なしぜん", hint: "曲 と 豆" },

    // --- ま行 ---
    { kanji: "務", readings: ["つと(める)", "ム"], meaning: "つとめ", strokes: 11, example: "事務所", hint: "矛 と 攵 と 力" },
    { kanji: "暴", readings: ["あば(れる)", "ボウ"], meaning: "あばれる", strokes: 15, example: "乱暴", hint: "日 と 共 と 水 みたい" },
    { kanji: "夢", readings: ["ゆめ", "ム"], meaning: "ゆめ", strokes: 13, example: "夢 をみる", hint: "くさかんむり と 罒 と ワ と 夕" },
    { kanji: "迷", readings: ["まよ(う)", "メイ"], meaning: "まよう", strokes: 9, example: "迷子", hint: "しんにょう に 米" },
    { kanji: "綿", readings: ["わた", "メン"], meaning: "わた", strokes: 14, example: "綿 あめ", hint: "いとへん に 白 と 巾" },

    // --- や行 ---
    { kanji: "輸", readings: ["ユ"], meaning: "はこぶ", strokes: 16, example: "輸入", hint: "車へん に 兪" },
    { kanji: "余", readings: ["あま(る)", "ヨ"], meaning: "あまる", strokes: 7, example: "余裕", hint: "人 と 一 と ホ" },
    { kanji: "預", readings: ["あず(ける)", "ヨ"], meaning: "あずける", strokes: 13, example: "預金", hint: "予 と 頁" },
    { kanji: "容", readings: ["ヨウ"], meaning: "かたち、いれる", strokes: 10, example: "内容", hint: "うかんむり に 谷" },

    // --- ら行 ---
    { kanji: "略", readings: ["リャク"], meaning: "はぶく", strokes: 11, example: "省略 する", hint: "田 と 各" },
    { kanji: "留", readings: ["と(める)", "リュウ"], meaning: "とどめる", strokes: 10, example: "留守 番", hint: "卯 と 田" },
    { kanji: "領", readings: ["リョウ"], meaning: "おさめる", strokes: 14, example: "領収 書", hint: "令 と 頁" }
];